#!/bin/sh

if [ $# -lt 1 ]; then
    echo "Usage: install_igpsftk_links [TARGET_DIR [ARCH] ]"
    #echo "Press Enter to continue ..."
    #read -p "$*"
else
   cd $1
fi


TARGETDIR=`pwd` 

#Get current system information
arch=`uname -s`
#echo $arch
sys=`uname`
#echo $sys
if [ "${sys}" = "SunOS" ]; then
    arch="${arch}_`uname -i`_`isainfo -b`"
elif [ "${sys}" = "Darwin" ]; then
    arch="${arch}_`uname -p`"    
else
    arch="${arch}_`uname -i`"
fi

echo "Creating iGPS FTK executables links in ${TARGETDIR}/bin/${arch} ..."
mkdir -p $TARGETDIR/bin/${arch}
cd $TARGETDIR/bin/${arch}
echo "Current directory is `pwd`"

if [ $# -lt 2 ]; then
  echo "Press Enter to continue or Ctrl+C to abort ..."
  read -p "$*"
fi

if [ $# -ge 1 ]; then
    TARGETDIR=$1
fi
if [ $# -ge 2 ]; then
    arch=$2
fi
 
#searching executables
files=`find $TARGETDIR -name "*\.${arch}" | grep -v "Makefile" | grep -v "\.a\."`
for file in $files; do
   echo creating link for $file
   ofile=`basename $file | awk -F".${arch}" '{print $1}'`
   \rm -f $ofile
   echo "ln -s $file $ofile"|sh
done



echo 'Links done.'
echo "Please append the below path to your PATH variable."
echo "#Path for GPSF executables:"
echo "$TARGETDIR/bin/${arch}"
