PRO DEF_IGPS_SYSV,IGPS_ROOT
  ;PRINT,!PATH
  DEFSYSV,'!IGPS_ROOT',EXISTS=IS_EXIST
  ;PRINT,IS_EXIST
  IF IS_EXIST NE 1 THEN BEGIN
    DEFSYSV,'!IGPS_ROOT',IGPS_ROOT
  ENDIF
  
  DEFSYSV,'!IS_IMSL',EXISTS=IS_EXIST
  ;PRINT,IS_EXIST
  IF IS_EXIST NE 1 THEN BEGIN
    DEFSYSV,'!IS_IMSL',TEST_IMSL()
  ENDIF
  
END