#!/bin/sh

# Name:
#   cron_node_safe2kml
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
. ${HOME}/.bashrc
echo $PATH

PROG=cron_node_safe2kml

path=/sar/esa.sentinel-1/metainfo/manifest.safe
opath=/sar/esa.sentinel-1/metainfo/footprint.kml

path=/sar/s1/metainfo/manifest.safe/
opath=/sar/s1/metainfo/track.footprint/

echo $IDL_DIR

#idl -e "SAR_S1_MANIFEST2OUTLINES,'/sar/s1/metainfo/manifest.safe/','/sar/s1/metainfo/track.footprint/'"
cmdstr="$IDL_DIR/bin/idl -e \"SAR_S1_MANIFEST2OUTLINES,'$path','$opath'\""
echo $cmdstr
echo $cmdstr | sh
exit

cd $opath/plot/
./plot_s1_footprint

#rsync -avP /sar/esa.sentinel-1/metainfo/footprint.kml 10.4.134.16:/cygdrive/i/INSAR/sar/esa.sentinel-1/metainfo/
