#!/bin/sh

# Name:
#   cron_sync_ac8_up
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

rsync -avP --delete /g11i/D/gsar jiang@210.31.68.9:/cygdrive/d/FTP/

