#!/bin/sh

# Name:
#   cron_node_sync_to_weiyun
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

. ${HOME}/.bashrc


PROG=cron_node_sync_to_weiyun

rsync -avP /sar/user/tianyf/admin 10.4.134.16:/cygdrive/i/INSAR/sar/

cron_node_safe2kml
