#!/bin/sh

# Name:
#   
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
. ${HOME}/.bashrc
#. ${HOME}/.proxy.sh



if [ "$esa_data" = "" ]; then
    echo "ESA environment esa_data variable not set! Stopped!!"
    exit 1
fi


this_host=`hostname`
user=tianyunfeng

roi_file=${esa_data}/vector/L_.roi_china_east.kml
roi_file=${esa_data}/vector/roi_china_20210216.kml
roi_file=${esa_data}/vector/L0.roi_tibet_20210327.kml
roi_file=${esa_data}/vector/L0.roi_tibet_20220325.kml
#roi_file=${esa_data}/vector/L0.roi_tibet.kml
#roi_file=${esa_data}/vector/L0.roi_tibet.arv.kml
#roi_file=${esa_data}/vector/L0.roi_tibet_20210327_chuandian.psxy




orb_types='ASCENDING DESCENDING'
case $this_host in
  gpsac15)
    #orb_types='ASCENDIGN'
    path=/g15a/gsar/china_east/S1.3
    ;;
  gpsac12)
    orb_types='ASCENDING'
    path=/g14i/esa.data/china_east/S1.3
    path=/g18h/gsar/tmp
    path=/g19b/gsar/tmp/
    ;;
  gpsac8)
    #orb_types='DESCENDING'
    orb_types='ASCENDING'
    #roi_file=${esa_data}/vector/L0.roi_tibet.arv.kml
    #path=/g8g/gsar/asf_tibet/S1
    #path=/g17b/gsar/asf_tibet/S1/
    path=/g11c/gsar/asf_tibet_alos/
    ;;
  SNOW1)
    #orb_types='DESCENDING'
    path=/cygdrive/d/esa.data/asf_tibet/S1
    ;;
  gpsac16|gpsac4)
    orb_types='DESCENDING'
    path=/g18h/gsar/tmp2/
    path=/g19b/gsar/tmp2/
    ;; 
  gpsac18)
    #orb_types='DESCENDING'
    path=/g18h/gsar/tmp/
    ;;
  *)
    echo "[$PROG]ERROR: wrong host ($this_host)!!"
    exit 1
    ;;
esac
echo host $this_host orb_types $orb_types
#exit


w1=3
w2=0


while [ "$1" != "" ]; do
  case $1 in
    -config)
      config_file=$2
      ;;
    -user)
      user=$2
      ;;
    -path)
      path=$2
      ;;
    -roi)
      roi_file=$2
      ;;
    -w1)
      w1=$2
      ;;
    -w2)
      w2=$2
      ;;
    *)
      echo "[]ERROR: invalid option ($1)!!"
      exit 1
      ;;
  esac
  shift 2

done

user=`echo $tmp | awk '{print $5}'`
echo user is $user

opath=${path}
echo $opath
echo $user
if [ "$user" == "" ];then
  user=tianyunfeng
fi
echo user is $user

#exit
#mkdir -p ${opath}
#exit
cd $opath
pwd

lckfile="${opath}/_cron_asf_china_east.lock"
if [ -s $lckfile ]; then
  echo "[]WARNING: a previous session is already running !! Quit."
  exit 1
fi

echo "[]INFO: downloading data for $track at $this_host ..." > $lckfile
#exit

for orb_type in $orb_types; do
  echo orb_type is $orb_type
  sh_esa_s1_query_asf -roi_file $roi_file -roi_type polygon -orb_type $orb_type -out_type KML -out_file ${orb_type}.kml  -sat ALOS
  #sh_esa_s1_query_asf -roi_file $roi_file -roi_type polygon -out_type KML -out_file ${orb_type}.kml -weeks $w1 -eweeks $w2


  sh_esa_s1_query_asf -roi_file $roi_file -roi_type polygon -orb_type $orb_type -out_file ${orb_type}.py   -sat ALOS
  #sh_esa_s1_query_asf -roi_file $roi_file -roi_type polygon -out_file ${orb_type}.py -weeks $w1 -eweeks $w2

  sh_esa_s1_query_asf -roi_file $roi_file -roi_type polygon -orb_type $orb_type -out_type CSV -out_file ${orb_type}.csv  -sat ALOS
  
  #continue
  #break
  #sh_esa_s1_get_data_py_asf ${orb_type}.py $opath $user
done

\rm -f $lckfile
