#!/bin/sh

# Name:
#   cron_sar_node_link_s1_files_nas50t
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

. ${HOME}/.bashrc


PROG=cron_sar_node_link_s1_files_nas50t

path=/g4f

dirs=`find $path -maxdepth 1 -type d -name "[0-9]*"|sort`
for dir in $dirs; do
  echo $dir
  echo sh_sar_node_link_s1_files_by_path_frame2 -path $dir
  echo sh_sar_node_link_s1_files_by_path_frame2 -path $dir | sh
  #exit
  
done
