#!/bin/sh

# Name:
#   cron_sar_node_extract_manifest_safe_by_track_frame
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

. ~/.bashrc

PROG=cron_sar_node_extract_manifest_safe_by_track_frame

sh_esa_s1_unzip_manifest_track -path /sar/s1/


idl -e "SAR_S1_MANIFEST2OUTLINES,'/sar/s1/metainfo/manifest.safe','/sar/s1/metainfo/footprint.kml'"

cd /sar/s1/metainfo/footprint.kml/plot/
date
./plot_s1_footprint
date
