#!/bin/sh

# Name:
#   cron_sync_ac4_down
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

. ${HOME}/.bashrc


#rsync -avP -e 'ssh -p 2222'  jiang@210.31.68.9:/cygdrive/d/esa.data/aux_poeorb/2022 /g4d/esa.data/aux_poeorb/
#rsync -avP -e 'ssh -p 2222'  jiang@210.31.68.9:/cygdrive/d/esa.data/aux_poeorb/2021 /g4d/esa.data/aux_poeorb/
#rsync -avP -e 'ssh -p 2222'  jiang@210.31.68.9:/cygdrive/d/esa.data/aux_resorb/2022 /g4d/esa.data/aux_resorb/
#rsync -avP -e 'ssh -p 2222'  jiang@210.31.68.9:/cygdrive/d/esa.data/aux_resorb/2021 /g4d/esa.data/aux_resorb/


#rsync -avP -e 'ssh -p 2222'  jiang@210.31.68.9:/cygdrive/d/esa.data/meta4 /g4d/esa.data/
#rsync -avP -e 'ssh -p 2222'  jiang@210.31.68.9:/cygdrive/d/esa.data/metainfo/metalink /g4d/esa.data/metainfo
#rsync -avP -e 'ssh -p 2222'  jiang@210.31.68.9:/cygdrive/d/esa.data/metainfo/xml /g4d/esa.data/metainfo
#rsync -avP -e 'ssh -p 2222'  jiang@210.31.68.9:/cygdrive/d/esa.data/vector /g4d/esa.data/


#upload
#rsync -avP -e 'ssh -p 2222'  /g4d/esa.data/metainfo/xml jiang@210.31.68.9:/cygdrive/d/esa.data/metainfo
#rsync -avP -e 'ssh -p 2222'  /g4d/esa.data/metainfo/metalink jiang@210.31.68.9:/cygdrive/d/esa.data/metainfo
#rsync -avP -e 'ssh -p 2222'  /g4d/esa.data/meta4 jiang@210.31.68.9:/cygdrive/d/esa.data/
#rsync -avP -e 'ssh -p 2222'  /g4d/esa.data/vector jiang@210.31.68.9:/cygdrive/d/esa.data/





#sh_esa_s1_link_g4d
sh_esa_s1_link_g4d -group S1.2
#sh_esa_s1_link_g4d -group S1.3
sh_esa_s1_unzip_manifest_ac
#sh_esa_s1_unzip_manifest_ac -path /g4d/esa.data/s1.2
#sh_esa_s1_unzip_manifest_ac -path /g4d/esa.data/s1.3


#rsync -avP -e 'ssh -p 2222'  /g4d/esa.data/metainfo/manifest.safe /g4d/esa.data/safe/all/
#rsync -avP -e 'ssh -p 2222'  /g4d/esa.data/safe/S1.2/ /g4d/esa.data/safe/all/
