#!/bin/sh

# Name:
#   sh_link_s1_files
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

. ${HOME}/.bashrc


PROG=sh_link_s1_files

path=/sar/esa.sentinel-1
opath=/sar/s1

dirs=`find $path -maxdepth 1 -type d -name "[AD]*"|sort`
for dir in $dirs; do
  echo $dir
  echo sh_sar_node_link_s1_files_by_path_frame -path $dir -opath $opath
  echo sh_sar_node_link_s1_files_by_path_frame -path $dir -opath $opath | sh
  
done
