#!/bin/sh

# Name:
#   
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

echo esa_data=${esa_data}
if [ "$esa_data" = "" ]; then
    . ${HOME}/.bashrc
    echo esa_data=${esa_data}
    if [ "$esa_data" = "" ]; then
        echo "ESA environment esa_data variable not set! Stopped!!"
        exit 1
    fi
fi

path=/sar/esa.sentinel-1/in-progress


while [ "$1" != "" ]; do
  case $1 in
    -path)
      path=$2
      ;;
    *)
      echo "[]ERROR: invalide option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
done

dirs=`find $path -maxdepth 1 -type d -name "[ad][0-9]*"`

oldpath=`pwd`
for cur_dir in $dirs; do
  echo processing $cur_dir
  if [ ! -s ${cur_dir}/md5.OK.txt ]; then
    continue
  fi

  mkdir -p ${cur_dir}/ok/
  cat ${cur_dir}/md5.OK.txt | awk -F: '{print "mv",cur_dir"/"$1,cur_dir"/ok/"}' cur_dir=$cur_dir | sh
  #cat ${cur_dir}/md5.OK.txt >> ${cur_dir}/ok/md5.OK.txt
  #\rm -rf ${cur_dir}/md5.OK.txt
  #cd ${cur_dir}/ok
  ls -l ${cur_dir}/ok/S1*.zip >> ${esa_data}/s1.2.list
  sh_esa_s1_unzip_manifest ${cur_dir}/ok ${cur_dir}/ok
  sh_esa_s1_mv_by_track -path ${cur_dir}/ok
  #cat ${cur_dir}/ok/md5.OK.txt >> ${esa_data}/meta4/md5.OK.txt
  #\rm -rf ${cur_dir}/ok/md5.OK.txt
  #\mv -f ${cur_dir}/ok/*.safe ${esa_data}/safe/all/

  cd $oldpath

  #exit
done
