#!/bin/sh

. ${HOME}/.bashrc

orb_type=res

while [ "$1" != "" ]; do
  case $1 in
    -orb_type)
      orb_type=$2
      ;;
    *)
      echo "[]ERROR: invalid option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
done

ORB_TYPE=`echo $orb_type | awk '{print toupper($1)}'`

opath=${esa_data}/aux_${orb_type}orb/2022

if [ ! -e $opath ]; then
  mkdir -p $opath
fi

if [ ! -e $opath ]; then
  echo "[]ERROR: output path not exist ($opath)!!"
  exit 1
fi

oldpath=`pwd`
cd $opath
pwd

time1=`date -u +%FT%T -d last-month`
time1=`date -u +%FT%T -d "today -29 days"`
time2=`date -u +%FT%T`

\rm query_*.txt #results.txt query_list.txt query_count.txt

echo in
qstr="https://scihub.copernicus.eu/gnss/odata/v1/Products/\$count?\$filter=startswith(Name, 'S1') and substringof('"${ORB_TYPE}"ORB', Name) and ContentDate/Start ge datetime'"$time1"' and ContentDate/End le datetime'"$time2"'"
#qstr="https://scihub.copernicus.eu/gnss/odata/v1/Products/\$count"

wget --no-check-certificate --content-disposition --continue  --user=gnssguest --password=gnssguest  --output-document=query_count.txt "$qstr"
nrec=`cat query_count.txt`
echo "nrec $nrec"
if [ "$nrec" == "" ]; then
  echo "[$PROG]ERROR: cannot get account of orbit files!!"
  exit 1
fi
#nrec=201
nper=100

if [ $nper -gt $nrec ]; then
  npg=1
  nper=$nrec
else
  npg=`echo $nrec $nper | awk '{if( (($1/$2)-int($1/$2))<0.00001){print int($1/$2)}else{print int($1/$2)+1} }'`
fi

#npg=1
echo $npg
#exit

pi=1
while [ $pi -le $npg ]; do
  PI=`echo $pi | awk '{printf("%04d",$1)}'`
  echo page $pi
  skip=`echo $pi $nper | awk '{print ($1-1)*$2+0}'`
  
  qstr="https://scihub.copernicus.eu/gnss/odata/v1/Products?\$skip=$skip&\$top=100&\$filter=startswith(Name, 'S1') and substringof('"${ORB_TYPE}"ORB', Name) and ContentDate/Start ge datetime'"$time1"' and ContentDate/End le datetime'"$time2"'"
  echo qstr $qstr
  wget --no-check-certificate --content-disposition --continue  --user=gnssguest --password=gnssguest  --output-document=query_results_$pi.txt "$qstr"
  cat query_results_$pi.txt | sed -e s'/>/>\n/g' | grep Id | grep -v '<d' | awk -F\< '{print $1}' > query_id_$pi.txt
  cat query_results_$pi.txt | sed -e s'/>/>\n/g' | grep Name | grep -v '<d' | awk -F\< '{print $1}' > query_name_$pi.txt
  paste query_id_$pi.txt query_name_$pi.txt > query_list_$pi.txt
  
  wc -l query_list_$pi.txt

  while read line; do
    id=`echo $line | awk '{print $1}'`
    name=`echo $line | awk '{print $2}'`
    echo $id $name
    
    ofile=${name}.EOF
    
    if [ -s $ofile ]; then
      echo "[]INFO: already exist ($ofile). Skipped."
      continue
    fi
    
    echo wget --no-check-certificate --content-disposition --continue  --user=gnssguest --password=gnssguest --tries=5 --progress=dot -e dotbytes=1M --output-file=./log.txt "https://scihub.copernicus.eu/gnss/odata/v1/Products('"$id"')/\$value"
    wget --no-check-certificate --content-disposition --continue  --user=gnssguest --password=gnssguest --tries=5 --progress=dot -e dotbytes=1M  "https://scihub.copernicus.eu/gnss/odata/v1/Products('"$id"')/\$value"

  done < query_list_$pi.txt


    pi=`expr $pi + 1`
done


#ls -lh *.EOF


