#!/bin/sh

# Name:
#   cron_sar_node_check_in_progress
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

PROG=cron_sar_node_check_in_progress


echo esa_data=${esa_data}
if [ "$esa_data" = "" ]; then
    . ${HOME}/.bashrc
    echo esa_data=${esa_data}
    if [ "$esa_data" = "" ]; then
        echo "ESA environment esa_data variable not set! Stopped!!"
        exit 1
    fi
fi

path=/sar/esa.sentinel-1/in-progress

file_lock=$path/_tmp_${PROG}.lock

if [ -s $file_lock ]; then
  echo "[$PROG]ERROR: session locked by $file_lock!!"
  exit 1
fi

date > $file_lock
hostname >> $file_lock

#dirs=`find $path -maxdepth 1 -type d -name "[ad][0-9]*"`


while [ "$1" != "" ]; do
  case $1 in
    -page)
      page=$2
      ;;
    *)
      echo "[]ERROR: invalide option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
done

/home/tianyf/iGPS/sh/cron_sar_node_get_metalink

/home/tianyf/iGPS/sh/sh_esa_s1_metalink_to_md5 -path /sar/esa.sentinel-1/in-progress/d000/
/home/tianyf/iGPS/sh/sh_esa_s1_metalink_to_md5 -path /sar/esa.sentinel-1/in-progress/d001/
/home/tianyf/iGPS/sh/sh_esa_s1_metalink_to_md5 -path /sar/esa.sentinel-1/in-progress/d002/


#exit
/home/tianyf/iGPS/sh/cron_sar_node_check_md5
/home/tianyf/iGPS/sh/cron_sar_node_mv_ok_s1

#ll /sar/esa.sentinel-1/alll/*.zip > /g4d/esa.data/s1.2.list

\rm -f $file_lock
