#!/bin/sh

# Name:
#   
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

echo esa_data=${esa_data}
if [ "$esa_data" = "" ]; then
    . ${HOME}/.bashrc
    echo esa_data=${esa_data}
    if [ "$esa_data" = "" ]; then
        echo "ESA environment esa_data variable not set! Stopped!!"
        exit 1
    fi
fi

path=/sar/esa.sentinel-1/in-progress
dirs=`find $path -maxdepth 1 -type d -name "[ad][0-9]*"`


while [ "$1" != "" ]; do
  case $1 in
    -page)
      page=$2
      ;;
    *)
      echo "[]ERROR: invalide option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
done

for cur_dir in $dirs; do
  #echo processing $cur_dir
  echo sh_esa_s1_get_metalink -path $cur_dir
  echo sh_esa_s1_get_metalink -path $cur_dir | sh

done
