#!/bin/sh

# Name:
#   cron_esa_s1_zip_check
#   

# Purpose:
#   Given a path contains S1*.zip files:
#   1). download the metalink file from ASF for each file;
#   2). extract md5 information from *.metalink files;
#   3). use md5sum program to check the file intergrity of S1 zip file;
#   4). update cache list (add good files).
#

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

. ${HOME}/.bashrc

PROG=cron_esa_s1_zip_check

path=`pwd`
oldpath=$path
apath=


this_host=`hostname`
case $this_host in
  gpsac15)
    path=/g15a/gsar/china_east/S1.3/
    apath=/g15a/esa.data/S1.3/
    ;;
  gpsac14)
    path=/g14f/esa.data/china_east/S1.3/
    apath=/g14f/esa.data/S1.3/
    ;;
  gpsac8)
    path=/g8g/gsar/asf_tibet/S1/
    apath=/g8g/esa.data/S1/
    ;;

  *)
    echo "[$PROG]ERROR: wrong host ($this_host)!!"
    exit 1
    ;;
esac



while [ "$1" != "" ]; do
    case $1 in
  -path)
      if [ ! -d $2 ]; then
        echo "[$PROG]ERROR: path not exist ($2)!!"
        exit 1
      fi
      cd $2
      if [ $? -ne 0 ]; then
        echo "[$PROG]ERROR: error when entering $2!!"
        cd $oldpath
        exit 1
      fi
      path=`pwd`
      cd $oldpath
      ;;
  *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      exit 1
      ;;
    esac
    shift 2
    
done

lck_file=$path/_cron_esa_s1_zip_check.lock
if [ -s $lck_file ]; then
  echo "[]ERROR: already running!!"
  exit 1
fi
echo "running at `hostname`"> $lck_file
echo "  since `date`" >> $lck_file

#cd $path

echo sh_esa_s1_get_metalink -path $path -opath $path
sh_esa_s1_get_metalink -path $path -opath $path 

echo sh_esa_s1_metalink_to_md5 -path $path
sh_esa_s1_metalink_to_md5 -path $path

echo sh_esa_s1_check_md5 -path $path
sh_esa_s1_check_md5 -path $path -local n

wc -l ${path}/md*
  
echo processing $path
if [ ! -s ${path}/md5.OK.txt ]; then
  continue
fi

cat ${path}/md5.OK.txt | awk -F: '{print path$1}' path=$path >> ${esa_data}/s1.2.list
cat ${path}/md5.OK.txt | awk -F: '{print "mv",path"/"$1,apath}' path=$path apath=$apath | sh
if [ $? -eq 0 ]; then
  #\rm -f ${path}/md5.OK.txt
  #\rm -f ${path}/*.metalink
  #\rm -f ${path}/md*
  echo remove sth
fi


\rm -rf $lck_file
