#!/bin/sh

# Name:
#   cron_node_remove_old_s1_zip
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
. ${HOME}/.bashrc

PROG=cron_node_remove_old_s1_zip

path=/sar/esa.sentinel-1/ok/
ndays=25

echo "[$PROG]INFO: remove S1 zip files $ndays days old from $path"

jd_cur=`doy | tail -3 | head -1 | awk '{print $8}'`

files=`find $path -maxdepth 1 -type f -name "S1*.zip" |sort`
np=0
for file in $files; do
  #echo $file
  bname=`basename $file`
  #echo bname $bname
  year=`echo $bname | awk -F_ '{print substr($6,1,4)}'`
  mon=`echo $bname | awk -F_ '{print substr($6,5,2)}'`
  day=`echo $bname | awk -F_ '{print substr($6,7,2)}'`
  hh=`echo $bname | awk -F_ '{print substr($6,10,2)}'`
  mm=`echo $bname | awk -F_ '{print substr($6,12,2)}'`
  ss=`echo $bname | awk -F_ '{print substr($6,14,2)}'`
  ms=`echo $bname | awk -F_ '{print substr($6,12,2)+substr($6,14,2)/60.}'`


  #echo year $year $mon $day $hh $mm $ss $ms
  jd_i=`doy $year $mon $day $hh $ms | tail -3 | head -1 | awk '{print $8}'`
  #echo $jd_cur $jd_i
  is_out=`echo $jd_cur $jd_i $ndays | awk '{if(sqrt(($1-$2)*($1-$2))>$3){print 1}else {print 0}}'`
  #echo is_out $is_out
  if [ $is_out -eq 1 ]; then
    #grep -H $bname ${esa_data}/metainfo/md5.OK.txt
    #grep -H $bname ${esa_data}/s1.2.list
    #grep -H $bname ${esa_data}/s1.list
    echo "[$PROG]INFO: remove $bname from ${esa_data}/s1.2.list"
    sed -i "/${bname}/d" ${esa_data}/s1.2.list

    echo "[$PROG]INFO: remove $bname from ${esa_data}/metainfo/md5.OK.txt"
    sed -i "/${bname}/d" ${esa_data}/metainfo/md5.OK.txt

    echo "[$PROG]INFO: remove zip data file $bname"
    echo "\rm -rf $file" | sh

    echo "[$PROG]INFO: remove link in /sar/esa.sentinel-1/alll/"
    echo "\rm -rf /sar/esa.sentinel-1/alll/${bname}" | sh

    echo "[$PROG]INFO: remove safe info in /sar/esa.sentinel-1/metainfo/manifest.safe/"
    echo "\rm -rf /sar/esa.sentinel-1/metainfo/manifest.safe/ok/`echo ${bname}| sed -e 's/.zip/.manifest.safe/g'` " | sh


    np=`expr $np + 1`
  fi
  #exit
done
echo "[$PROG]INFO: #$np S1 zip files in $path removed."
