#!/bin/sh

# Name:
#   cron_sar_check_slc_md5_g16h
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

. ~/.bashrc

PROG=cron_sar_check_slc_md5_g16h

oldpath=`pwd`

path_root=/g14g/gsar/dlasf

while [ "$1" != "" ]; do
    case $1 in
  -path)
      if [ ! -d $2 ]; then
        echo "[$PROG]ERROR: path not exist ($2)!!"
        exit 1
      fi
      cd $2
      if [ $? -ne 0 ]; then
        echo "[$PROG]ERROR: error when entering $2!!"
        cd $oldpath
        exit 1
      fi
      path_root=`pwd`
      cd $oldpath
      ;;
  *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      exit 1
      ;;
    esac
    shift 2

done

if [ ! -d $path_root ]; then
  echo "[]ERROR: path not exist ($path_root)!!"
  exit 1
fi

lck_file=$path_root/_cron_sar_check_slc_md5_g16e.lock
if [ -s $lck_file ]; then
  echo "[]ERROR: already running!!"
  exit 1
fi
echo "running at `hostname`"> $lck_file
echo "  since `date`" >> $lck_file

paths=`find ${path_root} -maxdepth 1 -type d -name "SLC20*"|sort`
for path in $paths; do
  echo $path
  cd $path
  pwd

  echo "sh_esa_s1_get_metalink -path $path -opath $path"
  echo "sh_esa_s1_get_metalink -path $path -opath $path" | sh
  echo "sh_esa_s1_metalink_to_md5 -path $path"
  echo "sh_esa_s1_metalink_to_md5 -path $path" |sh
  echo "sh_esa_s1_check_md5 -path $path"
  echo "sh_esa_s1_check_md5 -path $path" | sh
  
  echo processing $path
  if [ ! -s ${path}/md5.OK.txt ]; then
    continue
  fi

  cat ${path}/md5.OK.txt | awk -F: '{print "../../../esa.data/S1.3/"$1}' >> ${esa_data}/s1.2.list
  cat ${path}/md5.OK.txt | awk -F: '{print "mv",path"/"$1,"../../../esa.data/S1.3/"}' path=$path | sh
  if [ $? -eq 0 ]; then
    \rm -f ${path}/md5*
    rsync -avP *.metalink /g4d/esa.data/metainfo/metalink/
    \rm -f ${path}/*.metalink
    echo remove sth
  fi
  
  #exit
done

\rm -rf $lck_file
