#!/bin/sh

# Name:
#   cron_esa_s1_get_orb
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

echo esa_data=${esa_data}
if [ "$esa_data" = "" ]; then
    . ${HOME}/.bashrc
    echo esa_data=${esa_data}
    if [ "$esa_data" = "" ]; then
        echo "ESA environment esa_data variable not set! Stopped!!"
        exit 1
    fi
fi

path=${esa_data}/aux_poeorb/
cd $path
if [ $? -ne 0 ]; then
  ehco "Error!"
  exit 1
fi
pwd

page=1

while [ "$1" != "" ]; do
  case $1 in
    -page)
      page=$2
      ;;
    *)
      echo "[]ERROR: invalide option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
done
echo page is $page

ofile=index.html
rm -f $ofile
wget --no-check-certificate -O $ofile https://qc.sentinel1.eo.esa.int/aux_poeorb/?page=${page}
#wget --no-check-certificate https://qc.sentinel1.eo.esa.int/aux_poeorb/page=2
#grep EOF index.html | awk -F\" '{print " https://qc.sentinel1.eo.esa.int/aux_poeorb/"$2}' > eof.list
grep EOF $ofile | awk -F\" '{print " "$2}' > eof.list
sh_esa_s1_get_orb eof.list

