#!/bin/sh

# Name:
#   cron_ac6_backup_gmtsar
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
timestr=`date "+%Y%m%d-%H%M%S"`
cd /usr/local
pwd
tar jcf /home/tianyf/tmp/gmt5sar20200529-${timestr}.tar.bz2 gmt5sar20200529

rsync -avP /home/tianyf/tmp/gmt5sar20200529-${timestr}.tar.bz2 10.4.134.16:/cygdrive/i/INSAR/sar/software/GMTSAR/
rsync -avP gmt5sar20200529/README.tyf.txt 10.4.134.16:/cygdrive/i/INSAR/sar/software/GMTSAR/


rsync -avP /home/tianyf/tmp/gmt5sar20200529-${timestr}.tar.bz2 node1:/sar/software/GMTSAR/
rsync -avP gmt5sar20200529/README.tyf.txt node1:/sar/software/GMTSAR/

