#!/bin/sh

# Name:
#   cron_esa_s1_arp
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
# 
  
PROG=cron_esa_s1_arp

. ${HOME}/.bashrc

if [ "$igps_arp" = "" ]; then
    echo "iGPS environment variable igps_arp not set! Stopped!!"
    exit 1
fi

echo "[$PROG]INFO: running at `date`"

tmp=`date | sed -e 's/ /_/g' | sed -e 's/:/-/g'`


np=`grep '^ ' ${igps_arp}/events/count | tail -1 | awk '{print $1}'`
npc=`ls ${igps_arp}/events/*.txt | wc -l`

if [ $np -lt $npc ]; then
    echo $npc| awk '{print "",$1}' > ${igps_arp}/events/count
    echo sh_esa_s1_arp
    echo "output log to ${igps_arp}/log/log.arp.${tmp}"
    sh sh_esa_s1_arp >& ${igps_arp}/log/log.arp.${tmp} &
else
    echo "[$PROG]INFO: no new events."
fi

