#!/bin/sh

# Name:
#   cron_ac8_download_j9_asf_tibet
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
. ${HOME}/.bashrc

PROG=cron_ac8_download_j9_asf_tibet

while [ "$1" != "" ]; do
  case $1 in
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      echo "[$PROG]Usage: ${PROG} "
      echo "[$PROG]Usage: e.g.,"
      echo "[$PROG]Usage: ${PROG} "
      exit 1
      ;;
  esac
  shift 2  
done

path=/g11b/gsar/
if [ ! -d $path/asf_tibet/S1 ]; then
  echo "[]ERROR: path NOT exist ($path/asf_tibet/S1)!!"
  exit 1
fi

echo rsync -avP jiang@j9:/cygdrive/d/esa.data/asf_tibet/S1 $path/asf_tibet/
echo rsync -avP jiang@j9:/cygdrive/d/esa.data/asf_tibet/S1 $path/asf_tibet/ | sh


cd $path/asf_tibet/S1
pwd

sh_esa_s1_get_metalink
sh_esa_s1_metalink_to_md5
sh_esa_s1_check_md5 -local n

mkdir -p ok
cat md5.OK.txt | awk -F: '{print "mv",$1,"./ok/"}'
cat md5.OK.txt | awk -F: '{print "mv",$1,"./ok/"}' | sh
ls -l ok/*.zip >> ${esa_data}/s1.list
cd ok
ls *.zip > zips_ok
rsync -avP zips_ok jiang@j9:/cygdrive/d/esa.data/asf_tibet/S1/zips
#exit
ssh jiang@j9 'cat /cygdrive/d/esa.data/asf_tibet/S1/zips >> /cygdrive/d/esa.data/s1.list'
ssh jiang@j9 'cd /cygdrive/d/esa.data/asf_tibet/S1 && sh_touch_zips -local y -force y'
ssh jiang@j9 'cd /cygdrive/d/esa.data/asf_tibet/S1/ && cat zips | xargs rm'
#cmdstr="cat /cygdrive/d/esa.data/asf_tibet/S1/zips | awk '{print \"rm\",$1}'"
#echo $cmdstr
#exit

cd $path/asf_tibet/S1
pwd
echo mv ok/*.zip /g11b/esa.data/S1/
echo mv ok/*.zip /g11b/esa.data/S1/ | sh

echo rm md* *.metalink *.aria2
echo rm md* *.metalink *.aria2 | sh
