#!/bin/sh

# Name:
#   cron_gnss_check_rinex_ok
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=cron_gnss_check_rinex_ok

local_root=${IGS_ROOT}/rinex/

logfile=${IGS_ROOT}/rinex/chk_size.txt
#\rm -f $logfile

year=1998
while [ $year -le 2020 ]; do
  paths=`find $local_root/$year -maxdepth 1 -type d -name "[0-3]??" | sort`
  #paths=/g3c/pub/rinex/2020/305.3
  for path in $paths; do
    echo $path
    files=`find $path -maxdepth 1 -type f -name "*.??d.*[zZ]"`
    for file in $files; do
      echo $file
      bname=`basename $file`
      tmp=`grep $bname $logfile | grep '^ GOOD'`
      if [ "$tmp" != "" ]; then
        continue
      fi

      tmp=`sh_chk_size $file`
      echo " $tmp" >> $logfile
    done
  done

  year=`expr $year + 1`
  
done

