#!/bin/sh

# Name:
#   cron_esa_s1_asf_get_csv
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

. ${HOME}/.bashrc


PROG=cron_esa_s1_asf_get_csv

roi_file=${esa_data}/vector/roi_china_20210307.kml

while [ "$1" != ""  ]; do
  case $1 in
    -roi)
      roi_file=$2
      ;;
    *)
      echo "[]ERROR: invalid option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
done

mkdir -p ${esa_data}/metainfo/csv/tmp/
ofile=${esa_data}/metainfo/csv/tmp/asf.csv

file_lock=${esa_data}/metainfo/csv/tmp/_tmp_${PROG}.lock
if [ -s $file_lock ]; then
  echo "[$PROG]WARNING: already running!"
  exit
fi
hostname > $file_lock
date >> $file_lock


echo sh_esa_s1_query_asf -roi_file $roi_file -out_type CSV -roi_type polygon -out_file $ofile -weeks 9
echo sh_esa_s1_query_asf -roi_file $roi_file -out_type CSV -roi_type polygon -out_file $ofile -weeks 9 | sh

echo sh_asf_csv_all_to_ones -path ${esa_data}/metainfo/csv/tmp/
echo sh_asf_csv_all_to_ones -path ${esa_data}/metainfo/csv/tmp/ | sh

\rm -f $file_lock
