#!/bin/bash

# Name:
#   news
#   

# Purpose:
#   +

# Example:
#   

# Modifications:
#   +

# Algorithm:
#   +

# Dependency:
#   +
#


PROG=news

timestamp=`date | sed -e "s/ /_/g" | sed -e "s/:/-/g"`

path_old=`pwd`

usage_of_it(){
  echo "[$PROG]HELP: ${PROG} "
  echo "[$PROG]HELP: e.g.,"
  echo "[$PROG]HELP:   ${PROG} "
}

while [ "$1" != "" ]; do
  case $1 in
    *)
      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
      usage_of_it
      exit 1
      ;;
  esac
  shift 2  
done


echo "[$PROG]INFO: done."
