#!/bin/sh

# Name:
#   
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

path=`pwd`/..


if [ "$GMT_pub" = "" ]; then
  echo "[]ERROR:GMT_pub variable not set!!"
  #exit 1
fi


#(1)
echo "(1) change the DEM path if necessary"
path_dem=${GMT_pub}/dem.gmt/ETOPO1_Ice_g_gmt4.3min



#(3)
echo "(3) set the plot range for location map"
X_MAX=150
X_MIN=60

Y_MAX=65
Y_MIN=-5

#X_MAX=150
#Y_MAX=65
#X_MIN=50
#Y_MIN=0


echo "create colormap for InSAR LOS rate map"
colortable=no_green
gmt makecpt -C${colortable} -T-10/10/.001 -Z -I > my.cpt

echo "create colormap for DEM"
#dem colormap
colortable=rainbow
colortable=
#colortable=seafloor
colortable=globe
#colortable=gebco
#colortable=etopo1
#colortable=dem3
#colortable=gray
#colortable=relief
#colortable=cyclic
#colortable=panoply
#colortable=sealand
colortable=topo
gmt makecpt -C${colortable} -T-2500/9800/5 -Z -I > mytopo.cpt



gmt gmtset PS_MEDIA = a0
gmt gmtset FONT_TITLE = 12p
gmt gmtset FONT_LABEL         = 8p
gmt gmtset FONT_ANNOT_PRIMARY = 9p
gmt gmtset MAP_FRAME_PEN               = .5p
gmt gmtset MAP_FRAME_WIDTH             = 0.1c
gmt gmtset MAP_TICK_LENGTH = .1c
gmt gmtset MAP_TITLE_OFFSET = .1051c
##gmt gmtset ANNOT_FONT_SIZE_PRIMARY = 11p
##gmt gmtset HEADER_FONT_SIZE        = 16p
##gmt gmtset LABEL_FONT_SIZE         = 14p
##gmt gmtset PAPER_MEDIA             = a0
##gmt gmtset LABEL_OFFSET            = 0.2c




R=-R${X_MIN}/${X_MAX}/${Y_MIN}/${Y_MAX}
echo range of location map is $R
B=-B10f5/10f5


tracks=`ls ${path} |grep "^[AD][0-9]*"|sort|tac`

files_dem=`find $path_dem -name "*.grd"`
	
for track in $tracks; do
  echo $track
	ofile=${track}.ps
	echo output to $ofile
	
	
  nf=`ls ../../manifest.safe/$track/*safe | wc -l` #number of scenes
  date1=`ls ../../manifest.safe/$track/*safe | awk -F_ '{print substr($7,1,8)}' | sort|uniq|head -1`
  date2=`ls ../../manifest.safe/$track/*safe | awk -F_ '{print substr($7,1,8)}' | sort|uniq|tail -1`

	#first, plot DEM on the location map	

	fir=1
	for file_dem in $files_dem; do
	    tfile=`basename $file_dem`-${fir}
            if [ ! -s $tfile ]; then
              echo clip dem file
	      grdclip $file_dem  -G${tfile} $R -Sb-9999/NaN #-Ishaded.grd
	      grdgradient $tfile -A50  -Ne.316 -Gshaded.grd
            fi
	    if [ $fir -eq 1 ]; then
		gmt grdimage $file_dem -Cmytopo.cpt $R -JQ9i -Y2i -Ishaded.grd    ${B}:"":/10f5:""::."":WSEN -K -P   > ${ofile}
		fir=0
	    else
		gmt grdimage $file_dem -Cmytopo.cpt -R -J    -K -O >> ${ofile}
	    fi
	done
	
	echo "adding bounaries to the location map"
	gmt pscoast  -R -Dh -I1 -J -Swhite   -K -O  >> ${ofile}


	file=${path}/${track}/outline_ascending.kml
	if [ -s $file ]; then
	  echo "adding acending kml $file"
          kml2gmt $file > .tmp.gmt        
          wc -l .tmp.gmt
	  gmt psxy -R -J -O -K .tmp.gmt -W1p,red   >> $ofile 
	fi
	file=${path}/${track}/outline_descending.kml
	if [ -s $file ]; then
	  echo "adding descending kml $file"
          kml2gmt $file > .tmp.gmt              
	  gmt psxy -R -J -O -K .tmp.gmt -W1p,blue  >> $ofile   
	fi    
	



	echo adding fault lines
	echo dextral faults
	file=${GMT_pub}/vector/HimaTibetMap-1.0/GMT/HimaTibetMap-1.0_gmt/dextral_faults.gmt
	gmt psxy -R -J -O -Sf1i/.25+r+s+o.25i -W.25p,red -K  $file >> $ofile
	echo sinistral faults
	file=${GMT_pub}/vector/HimaTibetMap-1.0/GMT/HimaTibetMap-1.0_gmt/sinistral_faults.gmt
	gmt psxy -R -J -O -Sf2i/.25+l+s+o.5i -W.25p,red -K  $file >> $ofile
	echo normal faults
	file=${GMT_pub}/vector/HimaTibetMap-1.0/GMT/HimaTibetMap-1.0_gmt/normal_faults.gmt
	gmt psxy -R -J -O -W.25p,red -K  $file >> $ofile
	#gmt psxy -R -J -O -K -Sf.51/.0512+l+t -Gred -W.25p,red $file >> $ofile
	

	echo adding gps velocity map
	file=${GMT_pub}/gps/vel.lhasa.2016jul
	#file=../../tibet.velrot/vel.tibet_cgps_sgps
	#*Station   Longitude   Latitude Ve_init Ve_incr    Ve     dVe   Vn_init Vn_incr    Vn     dVn   Cen
	# AIRA_GPS  130.5996   31.8241   -19.3    15.5   -34.8     0.2    23.2    27.6    -4.4     0.0
	grep "^ " $file | awk '{if($7<10) {print $2,$3,$6,$10,$7,$7,0.0,tolower(substr($1,1,4)) }}' > .tmp
	#gmt psxy -R -J -Sc0.12c -W.5p -Gwhite .tmp -O -K -H1 >> $ofile
	
	#file=${GMT_pub}/gps/Supp_Table_S1.gmt psvelo
	#cat $file > .tmp

	gmt psvelo -R -J -W0.35p,navy -Glightblue -Se.02/0.95/0   -L -A6p+e -V .tmp -O -K>> $ofile

	echo adding north arrow
	###gmt pscoast  -R -Df -J  -V  -K -O -T90.5/32.5/.2i -L88.5/28.5/28.5/200+lkm -Wblack >> ${ofile}
	
	echo adding scale bar for InSAR rate
	#gmt psscale -D1.2i/.4i/3c/.23ch  -O -Cmy.cpt -K   -B5f1::/:"mm/a":  >> $ofile

	echo plot scale bar for gps velocity
	gmt psvelo <<end -R -J -W0.35p,navy -Glightblue -Se.02/0.95/0   -L -A6p+e  -V -O -K >> $ofile
	70.1 5 20 0 0 0 0 
end
	gmt pstext <<EOF -R -J -F+f+a+j -Gwhite@20 -O -K  >> $ofile
	70.1 6 10 0 1  20mm/a
	65 60 16p 0 LM  $track ($nf scenes) $date1 - $date2
EOF
###
###

	psvelo -R -J -W1p,red -Gred -Se1/0.95/0   -L -A9p+e -V <<eof -O -K>> $ofile 
65.1  20.11 -.2 0.866 0 0 0 ASC
eof
psvelo -R -J -W1p,red -Gwhite -Se1/0.95/0   -L -A9p+e -V <<eof -O -K>> $ofile 
65.1  20.11 0.6 0.14 0 0 0 LOS Direction
eof
pstext <<EOF -R -JQ -N -F+f+a+j -O -K  >> $ofile
64.25 22.52 8 13 LB ASC
67. 20.612 8 13 LB LOS
EOF

	
psvelo -R -J -W1p,blue -Gblue -Se1/0.95/0   -L -A9p+e -V <<eof -O -K>> $ofile 
145.4  55.48 -.2 -0.866 0 0 0 DES
eof
psvelo -R -J -W1p,blue -Gwhite -Se1/0.95/0   -L -A9p+e -V <<eof -O -K>> $ofile 
145.4  55.48 -0.6 0.14 0 0 0 LOS 
eof
pstext <<EOF -R -JQ -N -F+f+a+j -O -K  >> $ofile
143.7 55.53 8 -13 RB LOS
145.35 52.35 8 -13 RB DES
EOF



#add an annotation text
fig_cap= #blank
gmt pstext -R0/100/0/100 -JX4.6i -F+f8p+a0+jCM   -Y-.7i -X-0i -O  <<end >> $ofile
50 2   ${fig_cap}
end
	
	echo "converting JPEG ..."
	gmt ps2raster -A -Tj -Z $ofile
	echo "converting PDF ..."
	#psconvert -A -Tf -Z $ofile
	

  #exit
done
