#!/bin/sh

# Name:
#   
#   

# Purpose:
#   Unzip ALOS data files.

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
# 


if [ "$esa_unzip" = "" ]; then
    echo "ESA environment esa_unzip variable not set! Stopped!!"
    exit 1
fi


if [ "$ALOS_DATA" = "" ]; then
    echo "ALOS environment esa_data variable not set! Stopped!!"
    exit 1
fi

if [ "$1" == "" ]; then
    echo "Usage: sh_alos_unzip file"
    exit
fi

file=$1

grep '^ ' $file | awk '{print $1}' > .tmp
while read line; do
    #echo $line
    dfile="${line}.zip"
    #echo ${path_esa}/${dfile}
    file ${ALOS_DATA}/${dfile}
    if [ ! -s ${ALOS_DATA}/${dfile} ]; then
	echo "ERROR:data not found [${ALOS_DATA}/${dfile}]!!"
        continue
	exit 1
    fi

    ofile="$line"
    #echo ${opath_esa}/${ofile}
    if [ -d ${esa_unzip}/${ofile} ]; then
	echo "INFO:already done [${esa_unzip}/${ofile}]. Skipped."
	continue
    fi
    echo "unzip ${ALOS_DATA}/${dfile}"
    unzip ${ALOS_DATA}/${dfile} -x *IMG-HV-* -d ${esa_unzip}
    #exit
done < .tmp

