#!/bin/sh

# Name:
#   sh_alos_link_raw
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


if [ ! -d "./raw" ]; then
    echo "Usage: sh_alos_prep_preproc"
    echo "Please make sure the the raw directory exist!!"
    exit 1
fi


if [ "$1" == "" ]; then
    echo "Usage: sh_alos_prep_preproc alos_scenes "
    exit 1
fi
file_alos_list=$1

grep '^ ' $file_alos_list | awk '{print $1}' > .tmp1
ls -l raw/IMG-HH-*__[AD] > .tmp

tfile=./_alos_pre_process.sh
echo "cd raw" > $tfile
while read line; do
    echo $line
    line1=`cat .tmp | grep $line | awk '{print $9}'`
    if [ "$line1" = "" ]; then
        echo "[]ERROR: not found $line!!"
        exit 1
    fi
    file=`basename $line1`
    file2="LED-`echo $file | awk '{print substr($0,8)}'`"
    echo "ALOS_pre_process $file $file2" >> $tfile
done < .tmp1
cat $tfile
cat $tfile | sh
