#!/bin/sh

# Name:
#   sh_alos_link_raw
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


if [ ! -d "./raw" ]; then
    echo "Usage: sh_alos_prep_preproc"
    echo "Please make sure the the raw directory exist!!"
    exit
fi



if [ "$1" == "" ]; then
    echo "Usage: sh_alos_prep_preproc_batch alos_scenes "
    exit 1
fi
file_alos_list=$1

grep '^ ' $file_alos_list | awk '{print $1}' > .tmp1
ls -l raw/IMG-HH-*__[AD] > .tmp


tfile=data.in
echo "cd raw" > $tfile

line=`head -1 .tmp1 | awk '{print $1}'`
line1=`cat .tmp | grep $line | awk '{print $9}'`
if [ "$line1" = "" ]; then
    echo "[]ERROR: not found $line!!"
    exit 1
fi
file1=`basename $line1`
#echo $file1
file2=./raw/${file1}.PRM
near_range=`grep near_range $file2 | awk '{print $3}'`
earth_radius=`grep earth_radius $file2 | awk '{print $3}'`
fd1=`grep fd1 $file2 | awk '{print $3}'`
echo "$file1 -near $near_range -radius $earth_radius -fd1 $fd1" > $tfile

files=`sed -n '2,$'p .tmp1`
for line in $files; do
    echo $line
    line1=`cat .tmp | grep $line | awk '{print $9}'`
    if [ "$line1" = "" ]; then
        echo "[]ERROR: not found $line!!"
        exit 1
    fi
    file1=`basename $line1`
    echo "$file1" >> $tfile
done 
cat $tfile


