#!/bin/csh

if ($#argv > 0) then
    cd $1
endif
set curdir=`pwd`
echo $curdir


set i = 1

while ($i < 367)
    #echo $i
    if ($i < 10) then
	set mydir = `echo 00${i}`
    else if ($i < 100) then
	set mydir = `echo 0${i}`
    else
        set mydir = `echo ${i}`
    endif
    set doy = $mydir
    set mydir = "${curdir}/${mydir}"
    #echo $mydir
    @ i++
    if (! -e $mydir) then
	echo "making dir: $mydir"
        mkdir $mydir
    endif
    #echo "$doy ????${doy}?.???"
    #echo "ls ${curdir}/????${doy}?.??? | wc -l"
    set nf =  `ls ${curdir}/????${doy}?.???* | wc -l`
    echo $nf
    if ( $nf < 1) then
	continue
    endif
    #continue
    foreach file (????${doy}?.???*)
	echo $file
	if ($file == "No match.") then
	    echo "no files, skipping..."
	endif
        echo "  moving $file to $mydir"
        mv $file $mydir
    end

end

    #compress files
    #echo find $curdir -name \"????????.???*\" "
    foreach file (`find $curdir -name "????????.???"`)
	echo "compress $file"
	gzip -S .Z $file
    end
