#!/bin/sh

# Name:
#   ../sh_S1_unzip_manifest
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

if [ "$ALOS_DATA" = "" ]; then
    echo "[ERROR]ALOS environment variable esa_data must be set first! Stopped."
    exit 1
fi

files=`ls ${ALOS_DATA}/*.zip`
for file in $files; do
    #echo $file
    ofile=`echo ${file} | sed -e 's/.zip//g'`.workreport
    #echo $ofile
    if [ -s $ofile ]; then
	#echo "Skip    ${ofile} !"
        continue
    fi
    #echo "Extract $ofile"
    unzip -p $file "*.workreport" > $ofile
    if [ ! -s $ofile ]; then
	echo "Zero output file! Deleted."
	rm -f $ofile
	#mv $file ${esa_data}/S1/tmp/
    fi
    
    #exit
done

