#!/bin/sh

# Name:
#   sh_asf_csv_all_to_ones
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_asf_csv_all_to_ones

path=`pwd`

opath=${esa_data}/metainfo/csv/

while [ "$1" != ""  ]; do
  case $1 in
    -path)
      path=$2
      ;;
    -opath)
      opath=$2
      ;;
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
done

#mkdir -p $opath

files=`ls $path/*.csv`
for file in $files; do
  echo $file
  nl=`cat $file | wc -l`
  li=2
  
  line1=`sed -n '1p' $file`
  while [ $li -le $nl ]; do
    line2=`sed -n "${li}p" $file`
    fname=`echo $line2 | awk -F\" '{print $2}'`
    ofile=${opath}/${fname}.csv
    if [ ! -s $ofile ]; then
      
      echo "$line1" > $ofile
      echo "$line2" >> $ofile
      echo $line2
      #exit
    fi
    li=`expr $li + 1`
  done
  #exit
done