#!/bin/sh

# Name:
#   sh_esa_s1_prep_proc
#   

# Purpose:
#   Prepare xml files for processing.

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

#if [ "$esa_unzip" = "" ]; then
#    echo "ESA environment esa_unzip variable not set! Stopped!!"
#    exit 1
#fi
#

if [ "$1" == "" ]; then
    echo "Usage: sh_esa_s1_prep_proc data.in "
    exit
fi
file=$1

typs=`cat $file | awk '{print $1}'`
nday=`cat $file | wc -l`

rm -f ./intf.in
r=1
i=1
while [ $i -le $nday ]; do
    j=`expr $i + 1`
    while [ $j -le $nday ]; do
	echo $typs | awk '{print $i":"$j }' i=$i j=$j r=1 >> intf.in
	j=`expr $j + 1`
    done
    i=`expr $i + 1`
done

cat intf.in

ref_img=`echo $typs | awk '{print $i}' i=$r`
sed -e "s/master_image.*/master_image = $ref_img/" config.alos.txt.template > config.alos.txt
