#!/bin/sh
#sh_acsp3
#To archive met/nav/rinex data files from one directory to data server 
#directories according the type/date.
#

if [ $# -lt 2 ]; then
    echo "Usage: sh_arsp3 src_dir target_dir [type]"
    echo "   type can be: gfile, sp3(default)"
    exit 0
fi

#set command-line parameters
src_dir=$1
cd ${src_dir}
src_dir=`pwd`

tgt_dir=$2
cd ${tgt_dir}
tgt_dir=`pwd`

type=sp3
if [ $# -ge 3 ]; then
    type=$3
fi

case ${type} in
    gfile)
	ptn="gfile*"
	;;
    sp3)
	ptn="*.sp3*"
	;;
esac


	
#find file in source directory

#create temporary directory
src_dir_tmp=${src_dir}/../.tmp
mkdir ${src_dir_tmp}
echo ${src_dir_tmp}

echo "find ${src_dir} -name ${ptn}"
find ${src_dir} -name "${ptn}" -exec mv {} ${src_dir_tmp} \;

cd ${src_dir_tmp}
pwd

i=0

while [ $i -le 6 ]; do
    gpsd=$i
    i=`expr $i + 1`
    nf=`ls ${src_dir_tmp}/???????${gpsd}.sp3* | wc -l`
    echo "#weekday(${gpsd}):${nf}"
    if [ $nf -lt 1 ]; then
	continue
    fi

    for file in `ls ???????${gpsd}.sp3*` ; do
	#echo $file
	gpsw=`echo $file | awk '{print substr($0,4,4)}'`
	mydir=${tgt_dir}/${gpsw}
	mkdir -p ${mydir}
	#echo "mv $file ${mydir}/"
	mv $file ${mydir}/
	echo ".\c"
    done   
    echo 
done