#!/bin/sh

# Name:
#   sh_esa_s1_prep_proc
#   

# Purpose:
#   Prepare xml files for processing.

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

#if [ "$esa_unzip" = "" ]; then
#    echo "ESA environment esa_unzip variable not set! Stopped!!"
#    exit 1
#fi
#

if [ "$1" == "" ]; then
    echo "Usage: sh_esa_s1_prep_proc data.in "
    exit
fi
file=$1

typs=`cat $file|awk '{print $1}'`
nday=`cat $file | wc -l`

rm -f ./align.in
r=1
#while [ $i -le $nday ]; do
#    j=`expr $i + 1`
#    while [ $j -le $nday ]; do
#	echo $typs | awk '{print $i":"$j":"$r }' i=$i j=$j r=i >> align.in
#	j=`expr $j + 1`
#    done
#    i=`expr $i + 1`
#done
j=1
while [ $j -le $nday ]; do
    if [ $j -ne $r ]; then
	echo $typs | awk '{print $r":"$j":"$r }'  j=$j r=$r >> align.in
    fi
    j=`expr $j + 1`
done

cat align.in

#ref_img=`echo $ids | awk '{print "S1A"$1"_ALL_"IW_TYP}' IW_TYP=$IW_TYP`
#sed -e "s/master_image.*/master_image = $ref_img/" batch_tops.config.2 > batch_tops.config
