#!/bin/tcsh
#sh_acmnr
#To archive met/nav/rinex data files from one directory to data server directories according the type/date.
#

if ($#argv < 2) then
    echo "Usage: sh_armnr src_dir target_dir [type]"
    echo "   type can be: met, nav, rinex(default)"
    echo "Example:"
    echo "    sh_armnr /tmpdata /gps_archive/pub/rinex"
    echo "    sh_armnr /tmpdata /gps_archive/pub/nav nav"
    echo "    sh_armnr /tmpdata /gps_archive/pub/met met"
    exit 0
endif

#set command-line parameters
set old_dir = `pwd`
set src_dir = $1
cd ${src_dir}
set src_dir = `pwd`
set tgt_dir = $2
cd $old_dir
cd ${tgt_dir}
set tgt_dir = `pwd`
set type = rinexd
if ($#argv >= 3) then
    set type = $3
endif

switch(${type})
    case met:
	set ptn = "*.??m*"
	breaksw
    case nav:
	set ptn = "*.??n*"
	breaksw
    case rinexd:
	set ptn = "*.??d*"
	breaksw
    case rinexo:
	set ptn = "*.??o*"
	breaksw
endsw 

echo $#argv 
if ( $#argv >= 4) then # move all to temporary directory ../.tmp
                       # you should delete it manually later.
#find file in source directory
#create temporary directory
    set src_dir_tmp = ${src_dir}/../.tmp
    mkdir ${src_dir_tmp}
    echo ${src_dir_tmp}

    find ${src_dir} -name "${ptn}" -exec mv {} ${src_dir_tmp} \;
else
    set src_dir_tmp = $src_dir
endif
cd ${src_dir_tmp}
echo ${src_dir_tmp}
pwd

#exit

set i = 1
while ($i < 367)
#    if ($i < 50) then
#	set mydir = `echo 00${i}`
#    else if ($i < 100) then
#	set mydir = `echo 0${i}`
#    else
#        set mydir = `echo ${i}`
#    endif
    set mydir = `echo ${i} |awk '{printf("%03d",$1)}'`
    set doy = $mydir
    @ i++

    set nf =  `ls ${src_dir_tmp}/????${doy}?.???* | wc -l`
    echo "ls ${src_dir_tmp}/????${doy}?.???*"
    echo "#doy(${doy}):${nf}"
    if ( $nf < 1) then
	continue
    endif

    foreach file (????${doy}?.???*)
	echo $file
	if ($file == "No match.") then
	    echo "no files, skipping..."
	endif
        
	set yr = `echo $file | awk '{print substr($0,10,2)}'`
	#echo "yr: $yr"
	set yr = `expr $yr + 0`
	if ($yr < 80) then
	    set year = `expr $yr + 2000`
	else if ($yr < 100) then
	    set year = `expr $yr + 1900`
	endif
	#set year = 
	set mydir = "${tgt_dir}/${year}/${doy}"
	mkdir -p ${mydir}
	echo "  moving $file to $mydir"
        mv $file $mydir
	#pwd
	#exit
    end

    
    
end

	exit 0
		#####skip following#####


	#compress files
    #echo find $curdir -name \"????????.???*\" "
    foreach file (`find $curdir -name "????????.???"`)
	echo "compress $file"
	gzip -S .Z $file
    end
