#!/bin/sh

# Name:
#   sh_asf_s1_get_slc_list
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

PROG=sh_asf_s1_get_slc_list

if [ "$1" = "" ]; then
  echo "Usage: sh_esa_s1_wget_data_meta4_asf meta4_file [opath]"
  exit 1
fi

#initial values for parametrs
is_check_cache=y
opath=${esa_data}/S1/
user=tianyunfeng

tmp=`echo $1 | awk '{print substr($1,1,1)}'`
if [ "$tmp" != "-" ]; then  #mode 1, sh_esa_s1_wget_data_meta4_asf meta4_file [opath]

  file=$1
  
  if [ "$2" != "" ]; then
    opath=$2
  fi

else  #mode 2, sh_esa_s1_wget_data_meta4_asf -file meta4_file -opath opath -user user -check_cache y_or_n

  while [ "$1" != "" ]; do
    case $1 in
      -check_cache)
        is_check_cache=$2
        ;;
      -file)
        file=$2
        ;;
      -opath)
        opath=$2
        ;;
      -user)
        user=$2
        ;;
      *)
        echo "[]ERROR: invalid option ($1)!!"
        exit 1
        ;;
    esac
    shift 2
  done
fi


#files=`grep '^ ' $file | grep S1 | grep _IW_SLC_`
files=`grep '^ ' $file | grep S1 | grep _IW_`
echo $files

cd $opath
pwd

#file_aria2=${file}.aria2

file_user=${HOME}/iGPS.addon/sh/aria2.conf.${user}


for file in $files; do

  #if [ -s $file  ]; then
  if [ -s $file -a ! -s ${file}.aria2 ]; then
    echo "$file already exist! skipped"
    #echo ls -l $file
    #echo ls -l $file | sh
    file `pwd`/$file
    continue
  fi

#  if [ -s ${esa_data}/S1/$file -a ! -s ${esa_data}/S1/${file}.aria2 ]; then
#    echo "$file already exist! skipped"
#    #echo ls -l $file
#    #echo ls -l $file | sh
#    file ${esa_data}/S1/$file
#    continue
#  fi
#  
  
  if [ "$is_check_cache" == "y" ]; then
  
    #check if is already downloaded (but not in this server)
    tmp=`cat ${esa_data}/s1.list |grep $file`
  	if [ "$tmp" != "" ]; then
  	  echo "[]INFO: already downloaded (maybe not in this sever)! skipped $file"
  	  continue
  	fi
  
    tmp=`cat ${esa_data}/s1.2.list |grep $file`
  	if [ "$tmp" != "" ]; then
  	  echo "[]INFO: already downloaded (maybe not in this server 2)! skipped $file"
  	  echo "[]INFO: available at $tmp "
  	  continue
  	fi
	
	fi
			
	
  pwd
  #echo aria2c --conf-path=$file_user --http-auth-challenge=true  "https://datapool.asf.alaska.edu/SLC/SA/${file}"
  #exit
  echo aria2c -c --conf-path=$file_user --check-certificate=false  --http-auth-challenge=true  "https://datapool.asf.alaska.edu/SLC/SA/${file}"
  aria2c -c --file-allocation=none --conf-path=$file_user --check-certificate=false  --http-auth-challenge=true  "https://datapool.asf.alaska.edu/SLC/SA/${file}"
  #exit
done


