#!/bin/sh

# Name:
#   sh_create_input_lst
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

dirs=`find . -maxdepth 1 -type d -name "*_*" | sort`
for dir in $dirs; do
  echo $dir
  
  if [ -s ${dir}/input.lst ]; then 
    continue
  fi
  
  nf=`find $dir -maxdepth 1 -type f -name "overlapping.S1*.txt" | wc -l`
  #echo nf is $nf
  if [ $nf -lt 2 ]; then 
    continue
  fi
    
  files=`find $dir -maxdepth 1 -type f -name "overlapping.S1*.txt"`
  
  echo "grep -h '^ ' $files |sort|uniq> ${dir}/input.lst"
  grep -h '^ ' $files |sort|uniq > ${dir}/input.lst
  #exit
done

