#!/bin/sh

# Name:
#   sh_check_los_ll_png
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

dirs=`ls intf_all/`
for dir in $dirs; do
    #echo $dir
    file=./intf_all_los_ll_png/${dir}-los_ll.png
    if [ -s $file ]; then
	#echo "los ll png file exist! continue"
	continue
    fi
    echo rm -rf ./intf_all/$dir
    echo rm -rf ./intf_all/$dir | sh
done

