#!/bin/sh

# Name:
#   sh_count_num
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_count_num_lys

lock_file=/sar/s1_track_frame_slc/_tmp_${PROG}.lock
if [ -s $lock_file ]; then
  echo "[$PROG]ERROR: already running!!"
  exit 1
fi

hostname > $lock_file


cd /sar/s1_track_frame_slc

tracks=`ls |grep '^[AD]'`

\rm -rf _tmp.files.count.txt
#\rm -rf files.sentinel-1.txt

for track in $tracks; do
  echo track
  frames=`find $track -maxdepth 1 -type d -name "[0-9]???"`
  for frame in $frames; do
    nf=`ls $frame/S*.zip | wc -l  `
    echo $track `basename $frame` $nf >> _tmp.files.count.txt
    echo $track $frame $nf

  #ls $track/S*.zip >> files.sentinel-1.txt
  #exit
  done
done
\mv _tmp.files.count.txt files.count.txt

\rm -f $lock_file