#!/bin/sh

# Name:
#   sh_clean_expt
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

path=`pwd`

echo "cleaning tables ..."
cd ${path}/tables
sh_clean_tables

echo "deleting temporary directories ..."
cd ${path}
\rm -rf archive brdc control gfiles gifs glbf gsoln igs ionex met mkrinex raw rinex

files="autcln.out.gz.Z antmod.dat.Z dcb.dat.Z svs_exclude.dat.Z gdetic.dat.Z  otlcmc.dat.Z  svnav.dat.Z   tform.dat.Z leap.sec.Z ut1..Z soltab..Z pole..Z nutabl..Z luntab..Z core gig???.???.Z brdc????.??n.Z "
for file in $files; do
    echo "deleting $file files ..."
    find $path -name "$file" -exec rm {} \;
done
