#!/bin/sh

# Name:
#   sh_del_zip_vh
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

. ${HOME}/.bashrc

PROG=sh_del_zip_vh

path=/sar/esa.sentinel-1

while [ "$1" != "" ]; do
  case $1 in
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      echo "[$PROG]Usage: ${PROG} "
      echo "[$PROG]Usage: e.g.,"
      echo "[$PROG]Usage: ${PROG} "
      exit 1
      ;;
  esac
  shift 2  
done

tracks=`grep '^ ' $path/in-progress/to_reduce_size.list | awk '{print $1}' | sort`
#echo A055 > _tmp_zip_del_vh

for track in $tracks; do
  echo $track
  echo sh_esa_s1_zip_del_vh -path $path/$track
  echo sh_esa_s1_zip_del_vh -path $path/$track | sh

done
