#!/bin/sh

# Name:
#   sh_del_unwrap_not_detrend
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_del_unwrap_not_detrend

while [ "$1" != "" ]; do
  case $1 in
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      echo "[$PROG]Usage: ${PROG} "
      echo "[$PROG]Usage: e.g.,"
      echo "[$PROG]Usage: ${PROG} "
      exit 1
      ;;
  esac
  shift 2  
done

#files=`ls slurm_intf_tops_*.log`
files=`ls slurm_intf_tops_*.sh`
for file in $files; do
  #echo $file
  id=`echo $file | sed -e 's/slurm_intf_tops_//g' | sed -e 's/.sh//g'`
  #echo $id
  echo "rm -rf intf_all/${id} intf_all_x2/${id} intf_all_los_ll_png/${id}*"
  #exit
done
