#!/bin/sh

# Name:
#   sh_esa_s1_track_ad
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

while read line ; do
  track=`echo $line | awk '{print $1}'`
  orb_type=`echo $line | awk '{print tolower(substr($2,1,1))}'`
  echo "mv t${track} ${orb_type}${track}"

done < /g4d/esa.data/meta4/ad.txt
