#!/bin/sh

# Name:
#   sh_envisat_preprocess
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   



if [ "$1" = "" ]; then
    echo "Usage: sh_envisat_preprocess file"
    exit 1
fi
file=$1


grep '^ ' $file | awk '{print $1}' > .tmp
while read line; do
    echo ENVI_SLC_pre_process $line 0 
    echo ENVI_SLC_pre_process $line 0 | sh   
done < .tmp


