#!/bin/sh

# Name:
#   sh_mv_manifest_outside
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

opath=/mnt/a/S1

files=`find /g6e/gsar/safe.outside/in -maxdepth 1 -name "S1*.safe"`
files_tobe=
nf=0
for file in $files; do
  #echo $file
  bname=`basename $file | awk -F. '{print $1".zip"}'`
  #echo bname is $bname
  #exit

  ofile="${opath}/`basename $bname`"
  echo ofile is $ofile
  if [ -s $ofile ]; then
    echo "[]INFO: already exist ($ofile)."
    continue
  fi

  file1=/sar/esa.sentinel-1/alll/${bname}
  if [ -L $file1 ]; then
      file2=`ls -l $file1 | awk '{print $11}'`
      #exit
  else
      file2=$file1
  fi

  files_tobe="$files_tobe $file2"
  nf=`expr $nf + 1`

done

cd /sar/esa.sentinel-1/alll/
pwd

i=1
for file_tobe in $files_tobe; do
  ofile="${opath}/`basename $file_tobe`"
  if [ -s "$ofile" ]; then 
    echo "[]INFO: already copied ($ofile})"
    continue
  fi
  echo "[]INFO: ${i}/${nf} rsync -th --progress $file_tobe ${opath}/"
  echo rsync -th --progress $file_tobe ${opath}/ | sh
  
  ##file3=`basename $file1 | awk -F. '{print $1".manifest.safe"}'`
  ##echo rm -f $file3
  ##echo cp -f  ${esa_data}/safe/S1/$file3 ./S1.2/
  ##echo cp -f  ${esa_data}/safe/S1/$file3 ./S1.2/ | sh
  ##echo mv  $file1 ./S1.2/
  
  #opath="`dirname $file2`.2b"
  #echo mkdir -p $opath
  #echo mkdir -p $opath | sh
  #echo "mv $file2 $opath"
  #echo "mv $file2 $opath" | sh
  
  
  #echo rm -rf $file2
  #exit
  
  i=`expr $i + 1`
done 

