#!/bin/sh

# Name:
#   sh_esa_s1_cp_zip_expt
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

if [ "$esa_data" = "" ]; then
    echo "ESA environment esa_data variable not set! Stopped!!"
    exit 1
fi

if [ "$1" == "" -o "$2" == "" ]; then
    echo "Usage: sh_esa_s1_cp_zip_expt file opath"
    exit
fi
file=$1
oldpath=`pwd`
cd $2
if [ $? -ne 0 ]; then
    echo "ERROR: output directory not accessiable! Stopped!"
    exit 1
fi
opath=`pwd`
cd $oldpath

grep '^ ' $file | awk '{print $1}' > .tmp
while read line; do
    #echo $line
    dfile="`echo $line | awk -F. '{print $1}'`.zip"
    #echo ${path_esa}/${dfile}
    if [ ! -s ${esa_data}/S1/${dfile} ]; then
	echo "ERROR:data not found [${esa_data}/S1/${dfile}]! Skipped!"
        continue
	#exit 1
    fi
    if [ -s ${opath}/${dfile} ]; then
	echo "WARNING:data already copied [${opath}/${dfile}]! Skipped!"
        continue
	#exit 1
    fi

    echo \cp -f ${esa_data}/S1/${dfile} ${opath}/
    echo \cp -f ${esa_data}/S1/${dfile} ${opath}/ | sh
    #exit
done < .tmp

