#!/bin/sh

# Name:
#   sh_esa_s1_link_g8c
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

dirs="h1 d1 g5b b1 g5d g5c"
dirs="/g8b/gsar/aletsch/d066 /g8b/gsar/aletsch/a088 /g8f/gsar/us /g8a/gsar/tmp/tanlu/t76/ok /g8e/gsar/eq20200119.m5.9.jiashi /g8f/gsar/karakoram/t136 /g8d/gsar/guizhou/t128/ /g8d/gsar/guizhou/t164/ /g8d/gsar/jixi/t134 /g5d/gsar/chuanzang /g8b/gsar/ordos /g8b/gsar/kunlun/t26-seasonal /g8c/gsar/weiyuan /g8b/gsar/jixi/des-t61/ /d1/gsar/shenzhen /dc1/esa.data/S1.2 /d1/gsar/chuanzang/t106 /d1/gsar/chuanzang/t33 /g5a/gsar/ranwu /g5a/gsar/jinsha.river.landslide /g5a/gsar/jieze /b1/gsar/weiyuan /b1/gsar/mht /b1/gsar/taiwan /b1/gsar/sandaoling /b1/gsar/songyuan /b1/gsar/tianshan /b1/gsar/longriba /b1/gsar/haiyuan /b1/gsar/kangding /b1/gsar/changning /b1/gsar/changbaishan /b1/gsar/jiali /b1/gsar/bj /run/media/tianyf/esa/tianyf/taiwan"
for dir in $dirs; do
  echo $dir
  #files=`ls /${dir}/esa.data/S1/*.zip`
  files=`ls ${dir}/S1*.zip`

  for file in $files; do
      sfile="${esa_data}/s1.2/`basename $file`"


      #remove broken symbolic link 
      if [[ -L "${sfile}" ]] && [[ ! -a "${sfile}" ]];then
        echo "[]INFO: broken link"
        file $sfile
        echo "remove $sfile"
        \rm -rf $sfile
      fi


      if [ -s $sfile ]; then
      	echo "[]INFO: already done ($sfile)."
        continue
      fi
      ##echo mv $sfile /g8c/esa.data/S1/tmp/ |sh
      echo ln -s $file $sfile
      echo ln -s $file $sfile | sh
      #exit
  done
  
done

