#!/bin/sh

# Name:
#   sh_esa_s1_xml_to_md5
#   

# Purpose:
#  Convert ESA chcksum information in XML files to md5sum file (${esa_data}/meta4/md5.txt).

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

if [ "$esa_data" == "" ]; then
    echo "[]ERROR: environtment variable esa_data NOT set!!"
    exit 1
fi

if [ ! -d $esa_data ]; then
    echo "[]ERROR: directory $esa_data NOT exist!!"
    exit 1
fi


md5file=${esa_data}/metainfo/md5.txt


#find files
files=`find ${esa_data}/metainfo/xml -maxdepth 1 -name "S1*.xml"`

for file in $files; do
    #echo $file

    bname=`basename $file | awk -F. '{print $1}'`
    
    tmp=`grep $bname $md5file`
    if [ "$tmp" != "" ]; then
	#echo "[]INFO: already in it."
	continue
    fi

    hashval=`cat $file | grep "${bname}" | awk -FChecksum '{print $3}' | awk -F'<' '{print $4}' | awk -F'>' '{print $2}'`
    #echo $hashval
    if [ "$hashval" == "" ]; then
	echo "{}WARNING: no checksum informaiton found for $bname !!"
	continue
    fi
    echo $hashval ${bname}.zip
    echo $hashval ${bname}.zip >> $md5file
    #exit
   
   
done 
