#!/bin/sh

# Name:
#   sh_alos_intf_in_sort_by_coherence
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

days=`ls -lS intf_all_los_ll_png/*_ll.png | awk '{print $9}'|awk -F/ '{print $2}' | awk -F- '{print $1}'`

rm -rf intf.in.s
dos2unix scene.tab >& /dev/null

for day in $days; do
    echo " "$day
    ##
    day1=`echo $day | awk -F_ '{print $1}'`
    year1=`echo $day1 | awk '{print substr($1,1,4)}'`
    doyr1=`echo $day1 | awk '{print substr($1,5,3)+1}'`
    ymd1=`doy $year1 $doyr1 | head -1 | awk '{print $2}' | sed -e 's/\///g'`
    #n1=`grep -n $day1 scene.tab | awk -F: '{print $1}'`
    #ymd1=`sed -n "${n1}p" data.in | awk '{print $1}'`
    ##
    day2=`echo $day | awk -F_ '{print $2}'`
    year2=`echo $day2 | awk '{print substr($1,1,4)}'`
    doyr2=`echo $day2 | awk '{print substr($1,5,3)+1}'`
    ymd2=`doy $year2 $doyr2 | head -1 | awk '{print $2}' | sed -e 's/\///g'`
    #n2=`grep -n $day2 scene.tab | awk -F: '{print $1}'`
    #ymd2=`sed -n "${n2}p" data.in | awk '{print $1}'`
    ##
    echo " "$ymd1:$ymd2 $n1 $n2
    cat intf.in | grep $ymd1 | grep $ymd2 
    #exit
    cat intf.in | grep $ymd1 | grep $ymd2 >> intf.in.s
done
