#!/bin/sh

# Name:
#   sh_esa_s1_asf_list_by_track
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_esa_s1_asf_list_by_track

roi_file=${GMT_pub}/vector/profile/roi_china.kml
file=tracks.txt

while [ "$1" != ""  ]; do
  case $1 in
    -roi)
      roi_file=$2
      ;;
    -file)
      file=$2
      ;;
    *)
      echo "[]ERROR: invalid option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
done


while read line ; do
  ad=`echo $line | awk -F- '{print $1}'`
  track=`echo $line | awk -F- '{print $2}'`
  echo ad $ad
  case $ad in 
    A)
      orb_type=ASCENDING
      ;;
    D)
      orb_type=DESCENDING
      ;;
    *)
      echo continue
      continue
      ;;
  esac
  
  ofile=${ad}${track}.csv
  if [ -s $ofile ]; then
    continue
  fi

  echo sh_esa_s1_query_asf -roi_file $roi_file -orb_type $orb_type -out_type CSV -track $track -roi_type polygon -out_file $ofile -weeks 329
  echo sh_esa_s1_query_asf -roi_file $roi_file -orb_type $orb_type -out_type CSV -track $track -roi_type polygon -out_file $ofile -weeks 329 | sh
  #exit
  
done < $file
