#!/bin/sh

# Name:
#   
#   

# Purpose:
#   Unzip S1 data files.

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
# 


if [ "$esa_data" = "" ]; then
    echo "[]WARNING:ESA environment esa_data variable not set! Default current!"
    path=`pwd`
else
    path=$esa_data/S1
    #exit 1
fi

if [ "$1" == "" ]; then
    echo "Usage: sh_esa_s1_unzip_test_doit file [input_path]"
    echo "  Default input path: current."
    exit
fi

#input file
file=$1

#input path, if given
if [ "$2" != ""  ]; then
    cd $2
    path=`pwd`
fi

grep '^ ' $file | awk '{print $1}' > .tmp
while read line; do
    #echo $line
    dfile="`echo $line | awk -F. '{print $1}'`.zip"

    if [ ! -s ${path}/${dfile} ]; then
        echo "ERROR:data not found [${path}/${dfile}]!!"
        continue
        exit 1
    fi

    
    #continue


    echo "unzip -t ${path}/${dfile}"
    echo "unzip -t ${path}/${dfile}" | sh 

    #exit
done < .tmp

