#!/bin/sh

# Name:
#   sh_esa_s1_mv_aria2_tmp
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
opath=/sar/esa.sentinel-1/tmp/

files=`ls *aria2`
for file in $files; do
  #echo $file
  bname=`echo $file | awk -F. '{print $1}'`
  ofile_zip="${opath}/${bname}.zip"
  if [ -s $ofile_zip ]; then
    echo "#[]INFO: already exist ($ofile_zip)!"
    continue
  fi
  echo "mv -f ${bname}.zip* $opath"
done
