#!/bin/sh

# Name:
#   sh_esa_s1_intf_all_mv_bad
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

grep '^ ' ../BAD.txt > .tmp

while read line ; do
    echo $line
    year=`echo $line |awk '{print substr($1,1,4)}'`
    mon=`echo $line | awk '{print substr($1,5,2)}'`
    day=`echo $line | awk '{print substr($1,7,2)}'`

    doyr=`doy $year $mon $day |head -1 | awk '{print $6-1}'`

    echo $line $year $mon $day $doyr

    echo "mv intf_all/*${year}${doyr}* ../BAD/"
    echo "mv intf_all/*${year}${doyr}* ../BAD/" | sh
    echo "mv intf_all_los_ll_png/*${year}${doyr}* ../BAD/"
    echo "mv intf_all_los_ll_png/*${year}${doyr}* ../BAD/" | sh

done < .tmp
