#!/bin/sh

# Name:
#   sh_esa_s1_link_h2
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


#dirs="g4b g4c g4d g4e g4f g5a g5c g5d g6b g6c g6f g6g g7b g7i g9b g9c g10a g10b g12a g12b g12c g12d g12e g12f g13a g13b g13c g13d g13e g14a g14b g14c g14d g15b g15e g16a g16c g16d g16e g16f g16g g16h g16i"
#paths=
#for dir in $dirs; do
#  paths="$paths /${dir}/esa.data/S1.2/"
#done

shares=`df -h|grep '^gpsac' | awk '{print $1}'`
mounts=`df -h|grep '^gpsac' | awk '{print $6}'`

paths=
n=0
for share in $shares; do
  n=`expr $n + 1`
  #echo "[${prog}]INFO: working in shared place $share"
  cur_host=`echo $share | awk '{print $1}' | awk -F: '{print $1}'`
  cur_path=`echo $mounts | awk '{print $i}' i=$n`
  #echo cur_path $cur_path
  #if [ "$cur_path" == "/g4d" ]; then
  #  continue
  #fi

  cur_path_s1=${cur_path}/esa.data/S1/
  cur_path_s2=${cur_path}/esa.data/S1.2/
  cur_path_s3=${cur_path}/esa.data/S1.3/
  paths="$paths $cur_path_s2"
done

paths="$paths /g4b/esa.data/S1.2"
paths="$paths /g4c/esa.data/S1.2"
paths="$paths /g4d/esa.data/S1.2"
#paths="$path /g4e/esa.data/S1.2"
#paths="$path /g4f/esa.data/S1.2"






for path in $paths ; do
  if [ ! -d $path ]; then
    continue
  fi
  
  echo "working $path ..."
  files=`ls ${path}/S1*.zip`
  for file in $files; do
    #chmod o-w $file
    sfile="${esa_data}/s1.2/`basename $file`"

    #remove broken symbolic link 
    if [[ -L "${sfile}" ]] && [[ ! -a "${sfile}" ]];then
      echo "[]INFO: broken link"
      file $sfile
      echo "remove $sfile"
      \rm -rf $sfile
    fi

    if [ -s $sfile ]; then
        continue
    fi
    ##echo mv $sfile /h2/esa.data/S1/tmp/ |sh
    echo ln -s $file $sfile | sh
    #exit
  done
done
