#!/bin/sh

# Name:
#   
#   

# Purpose:
#   Unzip S1 data files.

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
# 
#. ${HOME}/.bashrc


#esa_data_node=/sar/esa.sentinel-1/alll
#esa_data_node=/sar/esa.sentinel-1/links
esa_data_node=/sar/s1/links

if [ "$esa_unzip" = "" ]; then
    echo "ESA environment esa_unzip variable not set! Stopped!!"
    exit 1
fi


#if [ "$esa_data" = "" ]; then
#    echo "ESA environment esa_data variable not set! Stopped!!"
#    exit 1
#fi

if [ "$1" == "" ]; then
    echo "Usage: sh_esa_s1_unzip file [iw0|iw1|iw2|iw3]"
    exit
fi

#iw_typs=`echo "iw1,iw2,iw3" | sed -e 's/,/ /g'`
iw_typs='iw1,iw2,iw3'

is_local=n
is_check_done=n

#two modes of input parameters
if [ "`echo $1 | awk '{print substr($1,1,1)}'`" == "-" ]; then

  while [ "$1" != "" ]; do
    case $1 in
      -file)
        file=$2
        ;;
      -iw)
        iw_typs=`echo $2 | sed -e 's/,/ /g'`
        ;;
      -local)
        is_local=$2
        ;;
      -update)
        is_check_done=$2
        ;;
      *)
        echo "[]ERROR: invalid option ($1)!!"
        exit 1
        ;;
    esac
    shift 2
  done

else  #mode 2
file=$1

if [ "$2" = "" ]; then
    echo "[INFO]iw_type not specified! Default iw1/iw2/iw3 will be extracted."
    iw_typs='iw1,iw2,iw3'
else 
    iw_typs=$2 #`echo $2 | sed -e 's/,/ /g'`
fi

fi  #end-of-mode-2


if [ "$is_check_done" == "y" ]; then
  file_tmp=_tmp_input_lst
  grep '^ ' $file  > _tmp_file_in
  for iw in `echo $iw_typs | sed -e 's/,/ /g'`; do
    ii=`echo $iw | awk '{print substr($1,3,1)}'`
    file_blt="F${ii}/baseline_table.dat"
    if [ -s $file_blt ]; then
      file_data="F${ii}/data.in"
      break
    fi
  done
  echo baseline file $file_blt

  #\rm -rf $file_tmp
  sid=`head -1 $file_data | awk -F- '{print substr($5,1,8)}'`
  cat _tmp_file_in | grep $sid > $file_tmp
  while read line; do
    sid=`echo $line | awk -F_ '{print substr($6,1,8)}'`
    #echo sid $sid
    tmp=`cat $file_blt | grep $sid`
    if [ "$tmp" == "" ]; then
      echo " $line" >> $file_tmp
    fi
  done < _tmp_file_in
  wc -l $file_tmp
  file=$file_tmp
fi

echo file $file
#exit

echo sh_esa_s1_unzip_node -file $file -iw $iw_typs -local y 
echo sh_esa_s1_unzip_node -file $file -iw $iw_typs -local y |sh
echo sh_esa_s1_unzip_node -file $file -iw $iw_typs -local n 
echo sh_esa_s1_unzip_node -file $file -iw $iw_typs -local n |sh

#echo sh_esa_s1_unzip_node -file $file -iw $iw_typs -path /sar/s1b/links
#echo sh_esa_s1_unzip_node -file $file -iw $iw_typs -path /sar/s1b/links | sh
echo sh_esa_s1_unzip $file $iw_typs
echo sh_esa_s1_unzip $file $iw_typs | sh
