#!/bin/sh


if [ "$esa_data" = "" ]; then
    echo "[ERROR]ESA environment variable esa_data must be set first! Stopped."
    exit 1
fi

orbit=aux_poeorb

while [ "$1" != "" ]; do
    case $1 in
        -orbit)
            orbit=$2
            ;;
        *)
            echo "Invalid option $1 !"
            exit 1
            ;;
    esac
    shift 2
done

path_orb=/g4d/esa.data/aux_poeorb
path_orb=${esa_data}/aux_poeorb
path_orb=${esa_data}/aux_resorb
path_orb=${esa_data}/${orbit}

files_orb=`ls ${path_orb}/*.EOF`

files_tiff=`ls *.tiff`
for file_tiff in $files_tiff; do
    tmp=`esa_s1_tiff_EOFs $file_tiff $files_orb | head -1`
    file_orb=`echo $tmp | awk '{print $2}'`
    if [ "$file_orb" = "" ]; then
	echo "[]ERROR:orbit file not found for ${file_tiff}!!"
	exit 1
    fi
    ln -s $file_orb
    echo " $file_tiff `basename $file_orb`"
    #exit
done
