#!/bin/sh

# Name:
#   sh_esa_s1_intf_grd_2_classic
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

path=intf_all
opath=intf_all_classic

#dirs=`ls $path/ | grep _  |grep "201[56]"`
dirs=`cat intf.tab | awk -F\/ '{print $3}'`
for dir in $dirs; do
    echo $dir
    odir="${opath}/${dir}"


    if  [ ! -d $odir ]; then
	echo "mkdir -p $odir	"
	echo "mkdir -p $odir" | sh
    fi

    if [ ! -s ${odir}/unwrap_ll.png ]; then
	echo "\cp -f ${path}/${dir}/unwrap_ll.png ${odir}/"
	echo "\cp -f ${path}/${dir}/unwrap_ll.png ${odir}/" | sh
    fi
    
    if [ ! -s ${odir}/corr_cut.grd ]; then
	echo "gmt grdconvert ${path}/${dir}/corr_cut.grd ${odir}/corr_cut.grd=cf"
	echo "gmt grdconvert ${path}/${dir}/corr_cut.grd ${odir}/corr_cut.grd=cf" | sh
    fi

    if [ ! -s ${odir}/unwrap.grd ]; then
	echo "gmt grdconvert ${path}/${dir}/unwrap.grd ${odir}/unwrap.grd=cf"
	echo "gmt grdconvert ${path}/${dir}/unwrap.grd ${odir}/unwrap.grd=cf" | sh
    fi
    
 #exit
done
