#!/bin/sh

# Name:
#   
#   

# Purpose:
#   Unzip S1 data files.

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
# 


if [ "$esa_unzip" = "" ]; then
    echo "ESA environment esa_unzip variable not set! Stopped!!"
    exit 1
fi


if [ "$esa_data" = "" ]; then
    echo "ESA environment esa_data variable not set! Stopped!!"
    exit 1
fi

if [ "$1" == "" ]; then
    echo "Usage: sh_esa_s1_unzip file"
    exit
fi

file=$1

grep '^ ' $file | awk '{print $1}' > .tmp
while read line; do
    #echo $line
    dfile="`echo $line | awk -F- '{print $2}'`.zip"
    #echo ${path_esa}/${dfile}
    if [ ! -s ${esa_data}/S1/${dfile} ]; then
	echo "ERROR:data not found [${esa_data}/S1/${dfile}]!!"
        continue
	exit 1
    fi

    ofile="`echo $line | awk -F. '{print $1}'`.SAFE"
    #echo ${opath_esa}/${ofile}
    if [ -d ${esa_unzip}/${ofile} ]; then
	echo "INFO:already done [${esa_unzip}/${ofile}]. Skipped."
	continue
    fi
    echo "unzip ${esa_data}/S1/${dfile} -x *-vh-* -d ${esa_unzip}"
    #unzip ${esa_data}/S1/${dfile} -x *-vh-* -d ${esa_unzip}
    #exit
done < .tmp

