#!/bin/sh

. ${HONE}/.bashrc


if [ "$esa_data" = "" ]; then
    echo "[ERROR]ESA environment variable esa_data must be set first! Stopped."
    exit 1
fi

path_orb=/g4d/esa.data/aux_poeorb
path_orb=${esa_data}/aux_poeorb

files_orb=`ls ${path_orb}/*.EOF`

files=`ls *.tiff`
for file1 in $files; do
    file_tiff=$file1

    #check starting time
    timstr=`echo $file1 | awk -F- '{print $5}'`
    year1=`echo $timstr | awk '{print substr($1,1,4)}'`
    mon1=`echo $timstr | awk '{print substr($1,5,2)}'`
    day1=`echo $timstr | awk '{print substr($1,7,2)}'`
    hh1=`echo $timstr | awk '{print substr($1,10,2)}'`
    mm1=`echo $timstr | awk '{print substr($1,12,2)}'`
    ss1=`echo $timstr | awk '{print substr($1,14,2)}'`
    echo $year1 $mon1 $day1 $hh1 $mm1 $ss1 $file_tiff
    jd1=`doy $year1 $mon1 $day1 $hh1 $mm1 | head -1 | awk '{print $8}'`
    #echo $jd1

    satyp1=`basename $file1 | awk '{print toupper(substr($1,1,3))}'`
    #echo $satyp1

    #continue
    for file2 in $files_orb; do	
	#echo $file2
	file_orb=$file2
	file2=`basename $file2`
	
	satyp2=`echo $file2 | awk -F_ '{print $1}'`
	#echo $satyp1 $satyp2
	if [ "$satyp1" != "$satyp2" ]; then
	    continue
	fi
	timstr=`echo $file2 | awk -F_ '{print substr($7,2)}'`
	year2=`echo $timstr | awk '{print substr($1,1,4)}'`
	mon2=`echo $timstr | awk '{print substr($1,5,2)}'`
	if [ $mon2 -gt $mon1 -o $mon2 -lt `expr $mon1 - 1` ]; then 
	    continue
	fi
	day2=`echo $timstr | awk '{print substr($1,7,2)}'`
	hh2=`echo $timstr | awk '{print substr($1,10,2)}'`
	mm2=`echo $timstr | awk '{print substr($1,12,2)}'`
	ss2=`echo $timstr | awk '{print substr($1,14,2)}'`
	#echo 2 $year2 $mon2 $day2 $hh2 $mm2 $ss2
	#exit
	jd2=`doy $year2 $mon2 $day2 $hh2 $mm2 | head -1 | awk '{print $8}'`
	#echo $jd1 $jd2 `echo $jd1 $jd2 | awk '{if($1<$2){print 0} else {print 1}}'`
	if [ `echo $jd1 $jd2 | awk '{if($1<$2){print 0} else {print 1}}'` -eq 0 ]; then
	    #echo $file2
	    continue
	fi
	#echo $file2
	#exit
	#
	#check ending time
	timstr=`echo $file2 | awk -F_ '{print substr($8,1)}'`
	year3=`echo $timstr | awk '{print substr($1,1,4)}'`
	mon3=`echo $timstr | awk '{print substr($1,5,2)}'`
	if [ $mon3 -gt `expr $mon1 + 1` ]; then 
	    #echo $file2
	    continue
	fi
	if [ $mon1 -eq 12 ]; then
	    if [ $mon3 -gt 1 -a $mon3 -lt 12 ]; then 
		#echo $file2
		continue
	    fi
	else 
	    if [ $mon3 -lt $mon1 ]; then
		continue

	    fi
	fi
	day3=`echo $timstr | awk '{print substr($1,7,2)}'`
	hh3=`echo $timstr | awk '{print substr($1,10,2)}'`
	mm3=`echo $timstr | awk '{print substr($1,12,2)}'`
	ss3=`echo $timstr | awk '{print substr($1,14,2)}'`
	#echo 3 $year3 $mon3 $day3 $hh3 $mm3 $ss3
	jd3=`doy $year3 $mon3 $day3 $hh3 $mm3 | head -1 | awk '{print $8}'`
	#echo $jd1 $jd3 `echo $jd1 $jd3 | awk '{if($1>$2){print 0} else {print 1}}'`
	if [ `echo $jd1 $jd3 | awk '{if($1>$2){print 0} else {print 1}}'` -eq 0 ]; then
	    continue
	fi
	ln -s $file_orb
	echo " $file_tiff $file2"
	break
    done
    #exit
done
