#!/bin/sh

# Name:
#   sh_esa_s1_unzip_manifest2
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

if [ "$esa_data" = "" ]; then
    echo "[ERROR]ESA environment variable esa_data must be set first! Stopped."
    exit 1
fi


out_path="${esa_data}/safe/S1.2/"
input_path="${esa_data}/s1.2/"
sh_esa_s1_unzip_manifest $out_path  $input_path
