#!/bin/sh

# Name:
#   sh_mv_manifest_outside
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
grep '^ ' safe_inside.txt | awk -F\/ '{print $2}' > .tmp
#dos2unix .tmp
while read line ; do
  file1=${esa_data}/S1.2/`echo ${line} | awk -F. '{print $1".zip"}'`
  if [ ! -s $file1 ]; then
      continue
  fi
  if [ -L $file1 ]; then
      file2=`ls -l $file1 | awk '{print $11}'`
      #exit
  else
      file2=$file1
  fi

  echo file2 is $file2
  tmp="`dirname $file2`.2"
  opath="`dirname $tmp`/S1"
  echo $opath
  #exit

  ofile="${opath}/`basename ${file2} `"
  echo $ofile
  if [ -s $ofile ]; then
      echo "$ofile already copied! skip"
  echo rm -f $file1
  echo rm -rf $file2
      continue
  fi
  if [ ! -d $opath ]; then
    echo mkdir -p $opath
    echo mkdir -p $opath | sh
  fi
  echo "mv $file2 $opath"
  echo "mv $file2 $opath" | sh

  #echo scp $file1 /cloud1/ESA/S1.2/
  #echo scp $file1 /cloud1/ESA/S1.2/ | sh
  #echo rsync -th --progress $file2 /cloud1/ESA/S1.2/
  #echo rsync -th --progress $file2 /cloud1/ESA/S1.2/ | sh
  
  ##file3=`basename $file1 | awk -F. '{print $1".manifest.safe"}'`
  ##echo rm -f $file3
  ##echo cp -f  ${esa_data}/safe/S1/$file3 ./S1.2/
  ##echo cp -f  ${esa_data}/safe/S1/$file3 ./S1.2/ | sh
  ##echo mv  $file1 ./S1.2/
  
  #opath="`dirname $file2`.2b"
  #echo mkdir -p $opath
  #echo mkdir -p $opath | sh
  #echo "mv $file2 $opath"
  #echo "mv $file2 $opath" | sh
  
  
  #echo rm -rf $file2
  #exit
done < .tmp

