#!/bin/sh

# Name:
#   sh_dl_resorb
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

if [ "$esa_data" = "" ]; then
    echo "ESA environment esa_data variable not set! Stopped!!"
    exit 1
fi

#file=to_down_bengco_ascending
#file=EOF.list
# grep https 201612a.htm |grep 'qc.sentinel1' |grep EOF | awk -F\" '{print $2}' > eof.list
if [ "$1" == "" ]; then
    echo "Usage: sh_esa_s1_get_resorb EOF_list_file "
    exit
fi
file=$1

orb_type=`head -1 $file | awk -F\/ '{print tolower(substr($4,1,3))}'`
echo "orb_type $orb_type"
mkdir -p ${esa_data}/aux_${orb_type}orb/
grep -v '^#' $file > ${esa_data}/aux_${orb_type}orb/.tmp
cd ${esa_data}/aux_${orb_type}orb/
while read line ; do
    year=`basename $line | awk -F_ '{print substr($7,2,4)}'`
    echo $year
    opath_t=${esa_data}/aux_${orb_type}orb/${year}
    if [ ! -d $opath_t ] ; then
	echo mkdir $opath_t
	echo mkdir $opath_t | sh
    fi
    cd $opath_t
    pwd

    echo wget -c --no-check-certificate $line
    echo wget -c --no-check-certificate $line | sh
    #exit
done < ${esa_data}/aux_${orb_type}orb/.tmp

