#!/bin/sh

# Name:
#   sh_esa_s1_zip_del_vh
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_esa_s1_zip_del_vh

path=`pwd`

file_list=

while [ "$1" != "" ]; do
  case $1 in
    -p|-path)
      path=$2
      ;;
    -f|-file)
      file_list=$2
      ;;
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      echo "[$PROG]Usage: ${PROG} "
      echo "[$PROG]Usage: e.g.,"
      echo "[$PROG]Usage: ${PROG} "
      exit 1
      ;;
  esac
  shift 2  
done

echo file_list $file_list
if [ "$file_list" == "" -o ! -s $file_list ]; then
  if [ ! -d $path ]; then
    echo "[$PROG]ERROR: input path not exist ($path)!!"
    exit 1
  fi

  files=`find $path -maxdepth 1 -type f -size +3G -name "S1*_IW_SLC__1SDV_*.zip" | sort`

else
  files=`grep -h '^ ' $file_list`

fi

for file in $files; do
  du -hs $file
  #echo "zip -d $file \\*vh\*.tiff"
  #echo "zip -d $file \\*vh\*.tiff" | sh

  echo "zip -d  $file   \"*/measurement/s1*-slc-vh-*-00*.tiff\""
  echo "zip -d  $file   \"*/measurement/s1*-slc-vh-*-00*.tiff\"" | sh

  #echo "zip -d  $file   \"*/annotation/s1*-slc-vh-*-00*.xml\""
  #echo "zip -d  $file   \"*/annotation/s1*-slc-vh-*-00*.xml\"" | sh
  #exit
done
