#!/bin/sh

# Name:
#   sh_esa_s1_orb_res_archive
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
path=`pwd`
opath=`pwd`
oldpath=`pwd`

while [ "$1" != "" ]; do
    case $1 in
	-path)
	    cd $2
	    path=`pwd`
	    cd $oldpath
	    ;;
	-opath)
	    cd $2
	    opath=`pwd`
	    cd $oldpath
	    ;;
	-h|-help)
	    echo "sh_esa_s1_orb_res_archive [-path PATH] [-opath OPATH]"
	    exit
	    ;;
	*)
	    echo "[]ERROR: invalid option ($1)!!"
	    exit 1
	    ;;
    esac
    shift 2
done

echo "input path: $path"
echo "output path: $opath"

#exit
files=`ls ${path}/*.EOF`
for file in $files; do
    #echo $file
    year=`basename $file |awk -F_ '{print substr($7,2,4)}'`
    #echo $year
    opath_t=${opath}/${year}
    if [ ! -d $opath_t ]; then
	echo "mkdir $opath_t" 
	echo "mkdir $opath_t" | sh
    fi
    echo "mv $file ${opath_t}/"
    echo "mv $file ${opath_t}/" | sh
    #exit
done


