#!/bin/sh

# Name:
#   sh_dl_orb
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

if [ "$esa_data" = "" ]; then
    echo "ESA environment esa_data variable not set! Stopped!!"
    exit 1
fi

#file=to_down_bengco_ascending
#file=EOF.list
# grep https 201612a.htm |grep 'qc.sentinel1' |grep EOF | awk -F\" '{print $2}' > eof.list
if [ "$1" == "" ]; then
    echo "Usage: sh_esa_s1_get_orb EOF_list_file "
    exit
fi
file=$1

mkdir -p ${esa_data}/aux_poeorb/
grep -v '^#' $file > ${esa_data}/aux_poeorb/.tmp
cd ${esa_data}/aux_poeorb/
while read line ; do
    year=`basename $line | awk -F_ '{print substr($7,2,4)}'`
    echo $year
    opath_t=${esa_data}/aux_poeorb/${year}
    if [ ! -d $opath_t ] ; then
	echo mkdir $opath_t
	echo mkdir $opath_t | sh
    fi
    cd $opath_t
    pwd

    echo wget -c --no-check-certificate $line
    echo wget -c --no-check-certificate $line | sh
done < ${esa_data}/aux_poeorb/.tmp

