#!/bin/sh

# Name:
#   sh_mv_manifest_outside
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

if [ "$1" == "" ]; then
    echo "Usage: sh_esa_s1_del_zip zip_file"
    exit 1
fi

file=`pwd`/$1

grep '^ ' $file | awk '{print $1}' > .tmp
dos2unix .tmp >& /dev/null

while read line ; do
  #echo $line

  file1=${esa_data}/s1/`echo ${line} | awk -F. '{print $1".zip"}'`
  file2=${esa_data}/s1.2/`echo ${line} | awk -F. '{print $1".zip"}'`
  file3=${esa_data}/s1.3/`echo ${line} | awk -F. '{print $1".zip"}'`
  #echo file3 $file3

  if [ ! -s $file1 -a ! -s $file2 -a ! -s $file3 ]; then
      #echo " #[]WARNING: not exist ($file1/$file2/$file3)!"
      continue
  fi
  
  if [ -s $file1 ]; then
    if [ -L $file1 ]; then
      file1l=`ls -l $file1 | awk '{print $11}'`
      echo rm $file1l
    fi
    echo rm $file1
  fi
  
  if [ -s $file2 ]; then
    if [ -L $file2 ]; then
      file2l=`ls -l $file2 | awk '{print $11}'`
      echo rm $file2l
    fi
    echo rm $file2
  fi
  
  if [ -s $file3 ]; then
    if [ -L $file3 ]; then
      file3l=`ls -l $file3 | awk '{print $11}'`
      echo rm $file3l
    fi
    echo rm $file3
  fi
done < .tmp

