#!/bin/sh

# Name:
#   sh_esa_s1_rsync_zip
#   

# Purpose:
#  Copy S1 SLC zip files to SAR cluster Storage Array (/sar)

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#  
prog=sh_esa_s1_rsync_zip

if [ "$esa_data" = "" ]; then
    echo "[${prog}]ERROR: ESA environment esa_data variable not set! Stopped!!"
    exit 1
fi
 
path=`pwd`
opath=/sar/esa.sentinel-1/

while [ "$1" != "" ]; do
  case $1 in
    -path)
      path=$2
      ;;
    *)
      echo "[${prog}]ERROR: invalid option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
  
done

echo "[${prog}]INFO: working in $path "

files=`find $path -maxdepth 1 -type f -name "S1*.zip"`
files_tobe=
nf=0
nall=0
for file in $files; do
  #echo "[${prog}]INFO: $file"
  nall=`expr $nall + 1`

  bname=`basename $file | awk -F. '{print $1}'`
  file_safe="${esa_data}/metainfo/manifest.safe/all/${bname}.manifest.safe"
  if [ ! -s $file_safe ]; then
    file_safe="${path}/${bname}.manifest.safe"
    #echo file_safe $file_safe
    if [ ! -s $file_safe ]; then
      echo "[${prog}]ERROR: no meta file for $bname !! Skipped."
      continue
    fi
  fi

  ad=`grep pass $file_safe | awk -F\> '{print (substr($2,1,1))}'`

  relativeorbit=`grep relativeOrbitNumber $file_safe |grep start| awk -F\> '{print $2}' | awk -F\< '{
print $1}'`
  #echo $ad $relativeorbit $file
  odir="${opath}/${ad}${relativeorbit}"
  #echo "[${prog}]INFO:odir is $odir"
  #exit

  if [ ! -d $odir ]; then
    mkdir -p $odir
  fi

  file_t=${opath}/S1/${bname}.zip
  if [ -s ${file_t} ]; then
    #echo "[${prog}]INFO: already exist in $file_t ! Skipped."  
    continue
  fi


  file_t=${odir}/${bname}.zip
  if [ -s ${file_t} ]; then
    #echo "[${prog}]INFO: already exist in $file_t ! Skipped."  
    continue
  fi

  files_tobe="$files_tobe $file"
  nf=`expr $nf + 1`

done


echo "[${prog}]INFO: transfering ${nf}/${nall} files ..."

ni=1
for file in $files_tobe ; do
  bname=`basename $file | awk -F. '{print $1}'`
  file_safe="${esa_data}/metainfo/manifest.safe/all/${bname}.manifest.safe"
  if [ ! -s $file_safe ]; then
    file_safe="${path}/${bname}.manifest.safe"
    #echo file_safe $file_safe
    if [ ! -s $file_safe ]; then
      echo "[${prog}]ERROR: no meta file for $bname !! Skipped."
      continue
    fi
  fi

  ad=`grep pass $file_safe | awk -F\> '{print (substr($2,1,1))}'`

  relativeorbit=`grep relativeOrbitNumber $file_safe |grep start| awk -F\> '{print $2}' | awk -F\< '{
print $1}'`
  #echo $ad $relativeorbit $file
  odir="${opath}/${ad}${relativeorbit}"
  #echo "[]INFO:odir is $odir"
  #exit

  echo "[${prog}]INFO: $ni/$nf rsync -avP $file $odir/"
  echo "rsync -avP $file $odir/" | sh

  ni=`expr $ni + 1`
  #exit 

done
