#!/bin/sh

# Name:
#   sh_get_in_triangle
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_get_in_triangle

path=`pwd`

roi_file=/g4d/esa.data/vector/L0.roi_tibetan_plateau.psxy
ofile=S1.2.txt

type=center

while [ "$1" != "" ]; do
  case $1 in
    -path)
      path=$2
      ;;
    -roi)
      roi_file=$2
      ;;
    -ofile)
      ofile=$2
      ;;
    -type)
      type=$2
      ;;
    *)
      echo "[]ERROR: invalid option ($1)!!"
      exit 1
      ;;
  esac
  shift 2

done

echo path $path
echo roi $roi_file
echo ofile $ofile
echo type $type
#exit

\rm -f $ofile


files=`find $path -maxdepth 1 -name "S1*.manifest.safe"` 
if [ "$files" == "" ];then
    continue
fi
#echo files $files
#exit

for file in $files; do
  echo file $file
  #<gml:coordinates>38.438999,98.572174 38.830635,95.721046 40.505825,96.068153 40.115303,98.991364</gml:coordinates>
  tmp=`grep -h 'coordinates' $file | awk -F\> '{print $2}' | awk -F\< '{print $1}'`
  #echo tmp $tmp
  echo $tmp | awk '{for(i=1;i<=NF;i++){print $i}}' | sed -e 's/,/ /g' | awk '{print $2,$1}' > _tmp_safe
  #cat _tmp_safe
  
  if [ "$type" == "center"  ]; then
    lon=`cat _tmp_safe|awk '{print $1}' | mean`
    lat=`cat _tmp_safe|awk '{print $2}' | mean`
    echo lon $lon lat $lat
    #exit
    is_in=`is_point_in_polygon $lon $lat $roi_file | grep is_in | awk '{print $2}'`
  fi
  
  if [ "$type" == "edge"  ]; then    
    while read line; do
      lon=`echo $line | awk '{print $1}'`
      lat=`echo $line | awk '{print $2}'`
      echo lon $lon lat $lat
      is_in=`is_point_in_polygon $lon $lat $roi_file | grep is_in | awk '{print $2}'`
      if [ $is_in -eq 1 ]; then
        break
      fi
    done < _tmp_safe
  fi
  
  
  echo $lon $lat $is_in
  if [ $is_in -eq 1 ]; then
    echo " `basename $file`" >> $ofile
    wc -l $ofile
    #exit
  fi
  #exit
done
  
