#!/bin/sh

# Name:
#   sh_esa_link_orig
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

file_user=${HOME}/iGPS.addon/sh/aria2.conf

if [ "$1" == "" ]; then
    echo "Usage: sh_esa_run_aria2_batch file.products.meta4"
    exit
fi

file=$1

#aria2c --http-user='<your username>' --http-passwd='<your password>' --check-certificate=false --max-concurrent-downloads=2 -M products.meta4

#aria2c --continue --http-user=$user --http-passwd=$passwd --check-certificate=false --max-concurrent-download=2 -M $file
aria2c --continue --conf-path=$file_user --check-certificate=false --max-concurrent-download=2 -M $file
