#!/bin/sh

# Name:
#   sh_gps_sinfo_not_in
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_gps_sinfo_not_in

sfile=trna.sit
ifile=station.info

#use system default time
yearStart=`date -u +%Y`
doys=`date -u +%j | awk '{printf("%03d",$0)}'`
doys=`expr $doys - 1`
if [ $doys -le 0 ]; then
    yearStart=`expr $yearStart - 1`
    doys=`ymd2ydoy ${yearStart} 12 31 | awk '{print $2}'`
    doys=`echo $doys | awk '{printf("%03d",$0)}'`
fi
doye=$doys
yearEnd=$yearStart
sites=`rdsit $sfile`

while [ "$1" != "" ]; do
  case $1 in
    -sfile)
      sfile=$2
      sites=`rdsit $sfile`
      ;;
    -ifile)
      ifile=$2
      ;;
    -yrs)
      yearStart=$2
      yr=`echo $yearStart | awk '{print substr($0,3,2)}'`
      y=`echo $yearStart | awk '{print substr($0,4,1)}'`
      ndays=`ymd2ydoy ${yearStart} 12 31 | awk '{print $2}'`
      ;;
    -yre)
      yearEnd=$2
      ;;
    -doys)
      doys=$2
      ;;
    -doye)
      doye=$2
      ;;
    -sites)
      sites=$2
      sites=`echo $sites | awk -F, '{for (i=1;i<=NF;i++) print $i}'`
      ;;
    *)
      echo "[]ERROR: invalid option ($1)!!"
      exit 1
      ;;
  esac

  shift 2
done

echo $yearStart $doys $yearEnd $doye

for site in $sites; do
  echo "[]INFO: search $site items in $ifile"
  lsite=`echo $site | awk '{print tolower($1)}'`
  tmp=`grep '^ ' $ifile | awk '{print tolower($1)}' | grep $lsite`
  if [ "$tmp" == "" ]; then
    echo "[]WARNING: no information for site $site !"
    continue
  fi
  grep '^ ' $ifile | awk '{if(tolower($1)==lsite){print $0}}' lsite=$lsite > .tmp.info
  echo "found `wc -l .tmp.info | awk '{print $1}'` records"
  
  #loop for each day  
  year=${yearStart}
  while [ ${year} -le ${yearEnd} ]; do

    if [ ${year} -eq ${yearStart} ]; then
      doy=${doys}
    else
      doy=001
    fi

    if [ ${year} -eq ${yearEnd} ]; then
      ndays=${doye}
    else
      ndays=`ymd2ydoy ${year} 12 31 | awk '{print $2}'`
    fi

    yy=`echo $year | awk '{print substr($0,3,2)}'`
    while [ ${doy} -le ${ndays} ]; do
      doy=`echo $doy | awk '{printf("%03d",$0)'}`
      
      echo "checking $site $year $doy ..."
      mjd=`doy $year 1 $doy 12 0 | head -1 | awk '{print $NF}'`
      
      is_found=0
        
      while read line; do
        #echo "$line"
        year1=`echo "$line" | awk '{print substr($0,25,4)}'`
        doyr1=`echo "$line" | awk '{print substr($0,30,3)}'`
        year2=`echo "$line" | awk '{print substr($0,44,4)}'`
        doyr2=`echo "$line" | awk '{print substr($0,49,3)}'`
        #echo $year1 $doyr1 $year2 $doyr2
        
        
        mjd1=`doy $year1 1 $doy1 12 0 | head -1 | awk '{print $NF}'`
        mjd2=`doy $year2 1 $doy2 12 0 | head -1 | awk '{print $NF}'`
        
        is_in=`echo $mjd $mjd1 $mjd2 | awk '{if($1>$2&&$1<$3){print 1}else{print 0}}'`
        if [ $is_in -eq 1 ]; then
          echo "[]INFO: found for $site on $year $doy !"
          is_found=1
          break
        fi
        #exit
      done < .tmp.info
      if [ $is_found -eq 0 ]; then
          echo "[]WARNING: no information found for $site on $year $doy !"
      fi
  
  
      doy=`expr $doy + 1`
    done
    year=`expr $year + 1`
  done
  #exit
done
