#!/bin/sh

# Name:
#   sh_grd_resample
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

files=`ls disp_???????_ll.grd`

file=`ls disp_???????_ll.grd | head -1`

sf=10
sf=4

#output directory
mkdir -p r${sf}

#current pixel size
psz_xx=`grdinfo -C $file | awk '{print $8}'`
psz_yy=`grdinfo -C $file | awk '{print $9}'`

#echo $psz_xx $psz_yy

out_psz_xx=`echo $psz_xx $sf | awk '{print $1*$2}'`
out_psz_yy=`echo $psz_yy $sf | awk '{print $1*$2}'`

#echo $out_psz_xx $out_psz_yy

echo "convert ra to ll ..."
cd r${sf}
rm ./trans.dat 
ln -s ../trans.dat
ln -s ../gauss*
files=`ls ../disp_???????.grd`

if [ ! -s vel_mask_ll.grd ]; then
    ln -s ../vel_mask.grd
    echo proj_ra2ll.csh trans.dat vel_mask.grd vel_mask_ll.grd
    echo proj_ra2ll.csh trans.dat vel_mask.grd vel_mask_ll.grd | sh
fi
grdinfo -C vel_mask.grd
grdinfo -C vel_mask_ll.grd

for file in $files; do
    bname=`basename $file`
    fname="${bname%.*}"

    out_name="${fname}_ll.grd"
    #echo $out_name
    #if [ ! -s $out_name ] ; then
	grdinfo -C $file

	echo proj_ra2ll.csh trans.dat $file $out_name
	echo proj_ra2ll.csh trans.dat $file $out_name | sh >& /dev/null

	grdinfo -C $out_name
	exit
    #fi
    
    out_name2="${fname}_mask_ll.grd"
    out_name2a="${fname}_mask_ll"

    if [ ! -s $out_name2 ]; then

	grdinfo -C $out_name
	grdinfo -C vel_mask_ll.grd

	echo "grdmath $out_name vel_mask_ll.grd MUL = ${out_name2}"
	echo "grdmath $out_name vel_mask_ll.grd MUL = ${out_name2}" | sh

	grd2kml.csh $out_name2a ../vel_ll.cpt4 
    fi
    
    
    exit
done


exit
#masking
for file in $files; do
    bname=`basename $file`
    fname="${bname%.*}"

    out_name="${fname}_mask.grd"
    #echo $out_name

    if [ -s $out_name ] ; then
	echo "[]Exists! Skip ($out_name) .."
	continue
    fi

    grdinfo -C $file
    grdinfo -C vel_mask_ll.grd

    echo "grdmath $file vel_mask_ll.grd MUL = ${out_name}"
    echo "grdmath $file vel_mask_ll.grd MUL = ${out_name}" | sh

    exit
done

exit

#resample
files=`ls r${sf}/disp_???????_mask.grd`
for file in $files; do
    bname=`basename $file`
    fname="${bname%.*}"

    out_name="r${sf}/${fname}_r${sf}.grd"
    #echo $out_name

    if [ -s $out_name ] ; then
	echo "[]Exists! Skip ($out_name) .."
	continue
    fi


    echo grdsample $file -I${out_psz_xx}/${out_psz_yy} -G${out_name}
    echo grdsample $file -I${out_psz_xx}/${out_psz_yy} -G${out_name}  | sh
    #exit
done

#exit
#convert to ra to ll
#ln -s trans.dat r${sf}/
#touch r${sf}/gauss_400
