#!/bin/sh

# Name:
#   sh_grd_cut_one_roi
#   

# Purpose:
#   Cut ONLY ONE roi from the grd file. 

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_grd_cut_one_roi


file_grd=
file_roi=

#test case 
file_grd=/sar/irm/by.frame/A142_0096/F3/sbas/vel_mask_ll.grd
file_roi=../vector/b18.psxy


ofile=


while [ "$1" != "" ]; do
  case $1 in
    -f|-file)
      file_grd=$2
      ;;
    -r|-roi)
      file_roi=$2
      ;;
    -o|-ofile)
      ofile=$2
      ;;
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      echo "[$PROG]Usage: ${PROG} "
      echo "[$PROG]Usage: e.g.,"
      echo "[$PROG]Usage: ${PROG} "
      exit 1
      ;;
  esac
  shift 2  
done

if [ "$file_grd" == "" ]; then
  echo "[$PROG]ERROR: no grd file!! "
  exit 1
fi
if [ ! -s $file_grd ]; then
  echo "[$PROG]ERROR: grd file not exist ($file_grd)!! "
  exit 1
fi


if [ "$file_roi" == "" ]; then
  echo "[$PROG]ERROR: no roi file!! "
  exit 1
fi
if [ ! -s $file_roi ]; then
  echo "[$PROG]ERROR: roi file not exist ($file_roi)!! "
  exit 1
fi


if [ "$ofile" == "" ]; then
  ofile="`basename $file_roi | sed -e 's/.psxy/.grd/g'`"
fi


  if [ ! -s $ofile ]; then
    echo "gmt grdcut $file_grd -G$ofile -F${file_roi}+c " 
    echo "gmt grdcut $file_grd -G$ofile -F${file_roi}+c " | sh
  fi
 
  if [ -s $ofile ]; then
    tmp=`gmt grdinfo -C $ofile -L2 | grep NaN`
    if [ "$tmp" != "" ]; then
      echo "[$PROG]INFO: try rect cut ..."
      Ii=`gmt grdinfo -I $ofile`
      Ri=`gmt gmtinfo $file_roi $Ii`
      echo "Ri $Ri"
      
      echo "gmt grdcut $Ri $file_grd -G$ofile"
      echo "gmt grdcut $Ri $file_grd -G$ofile" | sh

      #exit
    fi
  fi

  #check again for valid output, remove output if empty
  if [ -s $ofile ]; then
    tmp=`gmt grdinfo -C $ofile -L2 | grep NaN`
    if [ "$tmp" != "" ]; then
      echo "[$PROG]INFO: no data in output file ($file_grd)!"
      echo "\rm -f $ofile"
      #exit
      echo "\rm -f $ofile" | sh
    fi
  fi
