#!/bin/bash

# Name:
#   sh_grd2kml
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorithm:
#   

# Dependency:
#   


PROG=sh_grd2kml


file_grd=
file_cpt=
scale_title='mm/yr'

while [ "$1" != "" ]; do
  #echo p1 $1
  case $1 in
    -f)
      file_grd=$2
      ;;
    -c)
      file_cpt=$2
      ;;
    -s)
      scale_title=$2
      ;;
    *)
      if [ "`echo $1 | awk '{print substr($1,1,1)}'`" == "-" ]; then
        echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
        echo "[$PROG]Usage: ${PROG} "
        echo "[$PROG]Usage: e.g.,"
        echo "[$PROG]Usage: ${PROG} "
        exit 1
      else
        #echo "not while param"
        break
        #shift 1
      fi
      ;;
  esac
  #echo shift it
  shift 2  
done

if [ "$file_grd" == "" ]; then
  if [ $# -ge 1 ]; then
    file_grd=$1
  else
    file_grd=vel_ll.grd
  fi
fi


if [ "$file_cpt" == "" ]; then
  if [ $# -ge 2 ]; then
    file_cpt=$2
  else
    file_cpt=vel.cpt
  fi
fi

echo file_grd $file_grd
echo file_cpt $file_cpt

fname=`basename $file_grd`
bname=`echo $fname | sed -e 's/.grd$//g'`
dname=`dirname $file_grd`

path_old=`pwd`

if [ "$dname" != "" ]; then
  cd $dname
  echo "[]INFO: working in `pwd` ..."
fi

file_grd2="$bname"
file_grd3="`basename $file_grd`"
pwd
echo file_grd2 $file_grd2 

\rm ${file_grd2}.kml -f

if [ ! -s $file_cpt ]; then
  zmin=`gmt grdinfo -C $file_grd3 | awk '{print $6}'`
  zmax=`gmt grdinfo -C $file_grd3 | awk '{print $7}'`
  gmt makecpt -Cjet -T${zmin}/${zmax}/.1 -Z -I > $file_cpt
fi

echo grd2kml.csh $file_grd2 $file_cpt
echo grd2kml.csh $file_grd2 $file_cpt | sh

if [ ! -s ${file_grd2}.kml ]; then
  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: cannot produce output KML file!!"
  exit 1
fi

#if [ ! -s scalebar.png ]; then
  #make the scale bar for velocity
  gmt psscale -Dx.15i/.17i/1.2c/.2c  -C$file_cpt -Bxaf+l"${scale_title}" -P  > ${file_grd2}_scalebar.ps
  gmt psconvert -A -Tj ${file_grd2}_scalebar.ps
#fi

#insert the scalebar into KML file

cat <<eob > _tmp_scalebar_kml
	<ScreenOverlay>
		<name>Legend of ${file_grd2}</name>
		<Icon>
			<href>${file_grd2}_scalebar.jpg</href>
		</Icon>
		<overlayXY x="0" y="0" xunits="fraction" yunits="fraction"/>
		<screenXY x="0" y="0" xunits="fraction" yunits="fraction"/>
		<rotationXY x="0.5" y="0.5" xunits="fraction" yunits="fraction"/>
		<size x="0" y="0" xunits="pixels" yunits="pixels"/>
	</ScreenOverlay>
eob
#exit
\cp -f ${file_grd2}.kml _tmp_kml
sed '/\/GroundOverlay>/r _tmp_scalebar_kml' _tmp_kml > ${file_grd2}.kml

#clean temporary files
\rm _tmp_kml _tmp_scalebar_kml

if [ "$dname" != "" ]; then
  cd $path_old
  echo "[]INFO: returned to `pwd`"
fi
