#!/bin/tcsh -f

# Name:
#   sh_grd2jpg
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
  set scale = "-JX5i"
  gmt gmtset COLOR_MODEL = hsv
  gmt gmtset MEASURE_UNIT = inch
  set limitU = "500"
  set limitL = "-500"

  gmt  makecpt -Cseis -Z -T"$limitL"/"$limitU"/1 -D > los.cpt
  gmt makecpt -Cseis -Z -T-1/1/0.1 -D > los2.cpt
  gmt makecpt -Cseis -Z -T-10/10/1 -D > dem.cpt
#  makecpt -Cseis -Z -T-180/180/10 -D > shift.cpt
  gmt makecpt -Cseis -Z -T-500/500/1 -D > mean.cpt

set X_MAX = 92.9
set Y_MAX = 30.3
set X_MIN = 91.8
set Y_MIN = 29.4

set Y_MIN = 34.85
set Y_MAX = 34.9
set X_MIN = 112.22
set X_MAX = 112.26

#set yeardoyrs = `cat scene.tab | awk '{print $1}'`
set R = -R${X_MIN}/${X_MAX}/${Y_MIN}/${Y_MAX}
	#set B = -B.4f.2/.4f.2
	set B = -B.05f.025/.05f.025


ls disp_????????.grd | awk -F. '{print $1}' > disp.list
#ls disp_???_ll.grd | awk -F. '{print $1}' | tail -100> disp.list
ls disp_???????_mask_ll.grd | awk -F. '{print $1}' | tail -1000> disp.list
set file_ref = "`head -1 disp.list`.grd"
#set R = `grdinfo -I.001 $file_ref`

foreach a (`cat disp.list`)
  if (-f $a".grd") then
   echo $a
   set n = `echo $a | awk -F_ '{print $2}'`
   #set year = `echo $yeardoyrs | awk '{print $j}' j=$n | awk '{print substr($1,1,4)}'`
   #set doyr = `echo $yeardoyrs | awk '{print $j}' j=$n | awk '{print substr($1,5)}'`
   set year = `echo $a | awk '{print substr($1,6,4)}'`
   set doyr = `echo $a | awk '{print substr($1,10,3)}'`
   set ymd = `echo $a | awk '{print substr($1,6,8)}'`
   echo year_doyr: $year $doyr $n
   set ymd = `doy $year $doyr | head -1 | awk '{print $2}'`
   set boundR = `gmt grdinfo $file_ref -C | awk '{printf("%6.2f",($3-$2)/8)}'`
   set boundA = `gmt grdinfo $file_ref -C | awk '{printf("%6.2f",($5-$4)/8)}'`
   echo boundR: $boundR
   echo boundA: $boundA
   gmt grdimage $R $a".grd"  $scale -Clos.cpt -B"$boundA":lon:/"$boundA":lat::."$ymd":WSen -X1.3 -Y3 -P -K > $a".ps" 
#   psvelo -R -J -W0.15p,black -Gwhite   -Se.3/0.95/0  -L -A9p+e  -V -O -K  <<eof >> $a".ps"
#     92.27  29.81 1 0 0 0 0
#eof
  psxy -R -J -O -K -W.5p,black <<eof >> $a".ps"
  > -L"米拉山隧道_Mila_tunnel"
92.3371824212   29.7913162455
92.3311097605   29.8420254371

eof
   gmt psscale -D2.5/-1.2/5/0.2h -Clos.cpt -B100:"LOS Displacement (mm)":/:"-> uplift": -O -E >> $a".ps"
   gmt psconvert -A $a".ps" -Tj -E100
   rm $a".ps"
  endif
  #exit
end 
