#!/bin/sh

# Name:
#   sh_grd2xyz
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
files=`ls *.grd`
for file in $files; do
    #ofile="`basename $file | awk -F. '{print $1}'`_ll.grd"
    #echo "proj_ra2ll.csh trans.dat $file $ofile"
    #echo "proj_ra2ll.csh trans.dat $file $ofile" | sh
    
    #ofile2="`basename ${ofile} | awk -F. '{print $1}'`.nc"
    ofile2=`echo $file | sed -e 's/.grd/.nc/g' `
    echo "gmt grdconvert $file  ${ofile2}=cf"
    echo "gmt grdconvert $file  ${ofile2}=cf" | sh
done


