#!/bin/sh

# Name:
#   sh_intf_remove_trend
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

##use full path & file names
#path=`pwd`/intf_all
#opath=`pwd`/intf_all_detrend

##use relative path
path=./intf_all
opath=./intf_all_detrend

bname_corr=corr
bname_corr=corr_cut

while [ "$1" != "" ]; do
  case $1 in
    -corr)
      bname_corr=$2
      ;;
    *)
      echo "[]ERROR: wrong option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
done

mkdir -p $opath

dirs=`ls $path | grep "_"`
echo "dirs: $dirs"
for dir in $dirs; do
    echo $dir
    file_corr=`ls ${path}/${dir}/${bname_corr}.grd`
    if [ "$file_corr" = "" -o ! -s $file_corr ]; then
	echo "[]WARNING: coherence $file_corr not exist! skipped!"
	continue
    fi
    file_unwrap="${path}/${dir}/unwrap.grd"
    file_unwrap_mask="${path}/${dir}/unwrap_mask.grd"
    #echo $file_unwrap
    #echo $file_unwrap_mask

    if [ ! -s $file_unwrap -a  ! -s $file_unwrap_mask ]; then
	echo "[]WARNING: $file_unwrap and $file_unwrap_mask not exist! skipped!"
	continue
    fi

    ofile_corr="${opath}/${dir}/`basename $file_corr`"
    ofile_unwrap="${opath}/${dir}/`basename $file_unwrap`"
    ofile_unwrap_mask="${opath}/${dir}/`basename $file_unwrap_mask`"

      
    mkdir -p ${opath}/${dir}/

    if [ ! -s $ofile_corr ]; then
	echo ln -s $file_corr ${opath}/${dir}/
	echo ln -s ../../intf_all/${dir}/${bname_corr}.grd ${opath}/${dir}/ | sh
    fi

    if [ -s $file_unwrap -a ! -s $ofile_unwrap ]; then
	echo grdtrend $file_unwrap -N3r -D${ofile_unwrap}
	#echo gmt grdtrend $file_unwrap -N3r -D${ofile_unwrap} | sh
    fi

    if [ -s $file_unwrap_mask -a ! -s $ofile_unwrap_mask ]; then
	echo grdtrend $file_unwrap_mask -N3r -D${ofile_unwrap_mask}
	echo gmt grdtrend $file_unwrap_mask -N3r -D${ofile_unwrap_mask} | sh
    fi


 
    #exit
done


