#!/bin/sh 

#Note:
#  The program was developed in VMWare Sol10X86. We must
#  manually update system time each time the system was
#  been resumed.
#    ntpdate time.windows.com
#  But now, after installed the vmware tools, the time is
#  synchronized automatically. Thus, no need to update 
#  time anymore.

sh_igpsftk_clean_make

is_remake=y

host=192.168.91.2
host=10.23.19.195
host=192.168.11.195
host=192.168.11.23
#host=210.31.68.199

#user=anonymous
#password=tianyf@gmail.com
#user=tianyf
#password=
#user=jlm
#password=

while [ "$1" != "" ]; do
    case $1 in
	-remake)
	    is_remake=$2
	    ;;
	-host)
	    host=$2
	    ;;
	-u)
	    user=$2
	    ;;
	-p)
	    password=$2	    
	    ;;
	-h)
	    echo "Backup iGPS programes to remote backup server."
	    echo "Usage: sh_bak_igps [-remake y/n] [-host ip]  [-u user] [-p password]"
	    echo "(c)Tian 2007   GPSF V1.0"
	    exit
	    ;;
	*)
	    echo "Error: not valid option $1."
	    exit
	    ;;
    esac
    shift 2
done

echo "Backup program for iGPS started."
echo "  +clean existing builds ..."
cd ${HOME}/iGPS/ftk
make clean > /dev/null 2>&1

echo "  +tar and compress the directory ..."
cd ${HOME}
echo "  +working in `pwd`"

host=`uname -n | awk -F. '{print $1}'`

if [ "$host" = "gpsac" -o "$host" = "gpsac4" ]; then
tfile_dc=iGPS-`date "+%Y%m%d-%H%M%S"`-all.tar
echo "  +creating ${tfile_dc}.bz2 ..."
tar -cf $tfile_dc gpsf
bzip2 $tfile_dc
scp ${tfile_dc}.bz2 tianyf@gpsdc:/dcd0/BACKUP/tianyf/
if [ $? -eq 0 ]; then
    #\rm ${tfile} > /dev/null 2>&1
    \rm ${tfile_dc}.bz2 > /dev/null 2>&1
fi
fi

tfile=iGPS-`date "+%Y%m%d-%H%M%S"`.tar
echo "  +creating ${tfile}.bz2 ..."
tar -cf $tfile iGPS --exclude="*China.apr" --exclude="*cmon.apr" --exclude="*ltnn.apr"
bzip2 $tfile

echo "  +uploading ${tfile}.bz2 to ${host} as ${user}..."
# At first, we send this file as a attachment to some email accounts.
#uuencode $tfile.bz2 $tfile.bz2 | mailx -s $tfile.bz2 y.f.tian@163.com
# Now, the file is uploaded to one FTP server in the local network.
#echo "    +ncftpput -u ${user} -p ${password}  ${host} /cygdrive/d/phd/expt/backups/ ${tfile}.bz2"
#ncftpput -u ${user} -p ${password}  ${host} /cygdrive/d/phd/expt/backups/ ${tfile}.bz2 #> /dev/null 2>&1
scp ${tfile}.bz2 tianyf@tyf:/cygdrive/d/phd/expt/backups/
if [ $? -eq 0 ]; then
    \rm ${tfile}.bz2 > /dev/null 2>&1
fi
echo "  +temporary files cleared."



if [ "$is_remake" = "y" ]; then
    cd ${HOME}/iGPS/ftk
    echo "  +rebuilding..."
    ./install_igpsftk
fi

echo "Done."
