#!/bin/sh


if [ $# -lt 1 ]; then
    echo "Usage: sh_mv_rnx -dir inpath -odir outpath -yrs YRS -yre YRE"
    echo "                 -doys DOYS -doye DOYE"
    echo "                 -sites SITES_LIST | -sitefile SITE_LIST_FILE (*.sit)"
    exit 1
fi

path=/dcd0/ftp/pub/rinex
opath=`pwd`
yearStart=`date -u +%Y`
yearEnd=`date -u +%Y`


doy=`date -u +%j | awk '{printf("%03d",$0)}'`
doys=`expr $doy - 1`
if [ $doys -lt 0 ]; then
    yearStart=`$yearStart - 1`
    doys=`ymd2ydoy ${yearStart} 12 31 | awk '{print $2}'`
    doys=`echo $doys | awk '{printf("%03d",$0)}'`
fi
#doye=`ymd2ydoy ${yearStart} 12 31 | awk '{print $2}'`
doye=$doys


sites=`rdsit /export/home/tianyf/gpsf/cgps/conf/dc-090927.sit|awk '{print tolower($0)}' |sort | uniq`
sites=`rdsit /export/home/tianyf/tmp/shortrnx/short.rem.sit | awk '{print tolower($0)}' |sort | uniq`


# process command-line parameters
#####################################################
#COMMAND LINE PARAMETERS
#####################################################
while [ "$1" != "" ]
do
  #echo $1
  case $1 in
      -dir)
	  pathcur=`pwd`
	  cd $2
	  path=`pwd`
	  cd $pathcur
	  ;;
      -odir)
	  pathcur=`pwd`
	  cd $2
	  opath=`pwd`
	  cd $pathcur
	  ;;
      -yrs)
	  yearStart=$2
	  yr=`echo $yearStart | awk '{print substr($0,3,2)}'`
	  y=`echo $yearStart | awk '{print substr($0,4,1)}'`
	  ndays=`ymd2ydoy ${yearStart} 12 31 | awk '{print $2}'`
	  ;;
      -yre)
	  yearEnd=$2
	  ;;
      -doys)
	  doys=$2
	  ;;
      -doye)
	  doye=$2
	  ;;
      -sites)
	  sites=$2
	  sites=`echo $sites | awk -F, '{for (i=1;i<=NF;i++) print $i}'`
	  ;;
      -sitefile)
	  sfile=$2
	  
	  #sites=`sh_site_read $sfile`
	  sites=`rdsit $sfile|awk '{print tolower($0)}' |sort | uniq`
	  #echo $sites
	  ;;
      *)
	  echo "invalid options: $1"
	  exit 1
	  ;;
  esac
  shift 2
done
echo $sites
echo $yearStart $doys $yearEnd $doye

#exit
year=${yearStart}
while [ ${year} -le ${yearEnd} ]; do

    if [ ${year} -eq ${yearStart} ]; then
	doy=${doys}
    else
       doy=001
    fi

    if [ ${year} -eq ${yearEnd} ]; then
	ndays=${doye}
    else
	ndays=`ymd2ydoy ${year} 12 31 | awk '{print $2}'`
    fi

    yy=`echo $year | awk '{print substr($0,3,2)}'`
    while [ ${doy} -le ${ndays} ]; do
        doy=`echo $doy | awk '{printf("%03d",$0)'}`
        day_dir=${opath}/${year}/${doy}
        mkdir -p ${day_dir}
	chmod g+w ${day_dir}
        cd ${day_dir}
	pwd

	
	rdir=${path}/${year}/${doy}
	echo "rdir: $rdir"
        pwd
	#continue
	if [ "$sites" = "all" ]; then
            filez=${doy}0.${yy}d.Z
	    echo "\mv -f ${rdir}/* ${day_dir}"
	else
	    echo "loop sites..."
	    for site in $sites; do
		sess=0
		fileud=${site}${doy}${sess}.${yy}d
		fileuo=${site}${doy}${sess}.${yy}o
		filez=${site}${doy}${sess}.${yy}d.Z
		rfile=${rdir}/${filez}
		if [ -f $rfile ]; then
		    echo "\mv -f ${rfile} ${day_dir}"
		    #\cp -f ${rfile} ${day_dir}
		    \mv -f ${rfile} ${day_dir}
		fi
	    done
	fi
	doy=`expr $doy + 1`
        #doy=`expr $doy + 50`
    done
    year=`expr $year + 1`
done
