#!/bin/sh

# Name:
#   sh_max_interval
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_max_interval

path_old=`pwd`

usage(){
  echo "[$PROG]Usage: ${PROG} "
  echo "[$PROG]Usage: e.g.,"
  echo "[$PROG]Usage:  "
}

file=

while [ "$1" != "" ]; do
  case $1 in
    -f|-file)
      file=$2
      ;;
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      usage
      exit 1
      ;;
  esac
  shift 2  
done

cat $file | awk 'NR==1{old=$1;next}{print $1-old; old=$1}' | max | awk '{print int($1)}'

