#!/bin/bash

# Name:
#   sh_new

# Purpose:
#   Create a new shell script with a template.


if [ $# -lt 1 ]; then
    echo "Usage: sh_new ofile"
    exit
fi

# output file name
ofile=$1
if [ -f $ofile ]; then
    echo "Target file [${ofile}] exist! Overwrite it? [y/n]:"
    read yn
    #echo $yn
    if [ "${yn}" != "y" ]; then
  exit
    fi
    echo "WARNING: file [${ofile}] overwritten."
fi

# module file name
mfile=${HOME}/iGPS/ftk/inc/mod_sh
if [ ! -f ${mfile} ]; then
    echo -e "[$PROG]\033[1;33;41mERROR\033[0m: Module file NOT exist!"
    exit
fi

#
date_today=`date +%Y%m%d`

# get the line number of "# Name:"
linu=`grep -n "# Name:" $mfile | awk -F":" '{print $1}'`
# copy the first part to output file
sed -n "1,${linu}p" $mfile > $ofile
# insert function/subroutine name information to output file
echo "#   $ofile" >> $ofile

linu=`expr $linu + 1`

#change modification time
linm=`grep -n "# Modifications:" $mfile | awk -F":" '{print $1}'`
# copy the first part to output file
sed -n "${linu},${linm}p" $mfile >> $ofile
# insert creation information to output file
echo "#   + Created on `date` by `whoami`" >> $ofile

linu=`expr $linm + 1`
# append the second part to output file

sed -n "${linu},$ p" $mfile >> $ofile

echo "PROG=$ofile" >> $ofile

echo "">> $ofile
echo 'timestamp=`date | sed -e "s/ /_/g" | sed -e "s/:/-/g"`' >> $ofile


# add executable property
chmod +x $ofile


cat <<EOF >> $ofile

path_old=\`pwd\`

usage_of_it(){
cat <<eob
\${PROG}
  version $date_today
|_ Description_of_this_program
|+
  -Dependencies_of_this_program
|<
  Inputs
  [-h|-help|--help]
|>
  Outputs
|e.g.,
  \${PROG}
(c)iGPS (https://github.com/igps-ftk/)
eob
}

if [ \$# -lt 2 ]; then
  usage_of_it
  exit 1
fi

while [ "\$1" != "" ]; do
  case \$1 in
    -h|-help|--help)
      usage_of_it
      exit 1
      ;;
    *)
      echo -e "[\$PROG]\033[1;33;41mERROR\033[0m: invalid option (\$1)!!"
      usage_of_it
      exit 1
      ;;
  esac
  shift 2
done


echo "[\$PROG]INFO: done."
EOF
# the END
