#!/bin/sh

# Name:
#   sh_org_sig
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

files=`ls *.org`
for file in $files; do
    #echo $file
    sigline=`grep -H "min/max NE" $file | tail -1`
    echo $sigline
done