#!/bin/sh

# Name:
#   sh_sar_gsar_list
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_sar_gsar_list

bname=gsar
bname=

while [ "$1" != "" ]; do
  case $1 in
    -b|-bname)
      bname=$2
      ;;
    *)
      echo "[]ERROR: invalid option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
done


#paths=`df -h | awk '{print $6}' | grep 'g[0-9]'`
paths=`df -h | awk '{print $6}' | grep '^/g'`

for path in $paths; do
  echo $path
  if [ "$bname" == "" ]; then
    find $path -maxdepth 4 
  else
    path_gsar="${path}/${bname}"
    if [ ! -d $path_gsar ]; then
      continue
    fi

    dirs=`find $path_gsar -maxdepth 2 -type d`
    for dir in $dirs; do
      echo $dir
    done
  fi
  #exit
done
