#!/bin/sh

# Name:
#   sh_sar_sort_baseline_table_by_data_in
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_sar_sort_baseline_table_by_data_in

path_old=`pwd`

usage(){
  echo "[$PROG]Usage: ${PROG} "
  echo "[$PROG]Usage: e.g.,"
  echo "[$PROG]Usage:  "
}

while [ "$1" != "" ]; do
  case $1 in
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      usage
      exit 1
      ;;
  esac
  shift 2  
done



\rm -f _tmp_blt
while read line; do
  # s1b-iw1-slc-vv-20200108t214728-20200108t214753-019731-0254e1-004:S1B_OPER_AUX_POEORB_OPOD_2020012
  tid=`echo $line | awk -F- '{print substr($5,1,8)}'`
  echo tid $tid
  cat baseline_table.dat | grep $tid >> _tmp_blt
done < data.in

\mv -f _tmp_blt baseline_table.dat

