#!/bin/sh

# Name:
#   sh_sar_sbas_2_gic3dv
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_sar_sbas_2_gic3dv

while [ "$1" != "" ]; do
  case $1 in
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      echo "[$PROG]Usage: ${PROG} "
      echo "[$PROG]Usage: e.g.,"
      echo "[$PROG]Usage: ${PROG} "
      exit 1
      ;;
  esac
  shift 2  
done

paste vel_mask_ll3.xyz rms_mask_ll3.xyz look_mask_ll3.xyz > _vel_rms_look_mask_ll3.xyz

#101.679298246	20.9477080836	0.182784050703	101.679298246	20.9477080836	0.524286746979	101.679298 20.947708 984.795852 0.622280 -0.117923 0.773862  	39.298	-79.269602982221045
cat _vel_rms_look_mask_ll3.xyz | awk '{print $1,$2,$14,$13,$3*.1,$6*.1}' 
