#!/bin/sh

# Name:
#   sh_sar_del_merged_tiff
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

oldpath=`pwd`

#grep '^ ' wc-l-20200515.txt > .tmp

path_root=/sar/proc_gmtsar/interseismic/

cd $path_root

dirs=`ls -l | grep '^d' | awk '{print $9}'`



for line in $dirs; do
  echo $line
  path=`echo $line | awk '{print $1}'`
  echo "# $path"

  #echo "rm -rf ${path}/f123.1/intf_all_detrend"
  #echo "rm -rf ${path}/f123.1/intf_all_detrend" | sh

  #echo "rm -rf ${path}/f123.1/intf_all_los_ll.png"
  #echo "rm -rf ${path}/f123.1/intf_all_los_ll.png" | sh

  #continue
  Fpath="${path}/f123.1/intf_all"
  if [ ! -d $Fpath ]; then
    Fpath="${path}/f123/intf_all"
    if [ ! -d $Fpath ]; then
      continue
    fi
  fi

  echo "# `pwd`"

  echo "#deleting unwrap.grd files in $Fpath ..."
  find $Fpath -name "unwrap.grd" -exec rm {} \;
  echo "#deleting unwrap_ll* files in $Fpath ..."
  find $Fpath -name "unwrap_ll*" -exec rm {} \;
  echo "#deleting corr_ll* files in $Fpath ..."
  find $Fpath -name "corr_ll*" -exec rm {} \;

  cd $Fpath
  echo "# `pwd`"

  echo "#sh_sar_clean_intf_all_all"
  echo sh_sar_clean_intf_all_all | sh


  cd $path_root
  echo "# `pwd`"

  #exit
done 
