#!/bin/sh

# Name:
#   sh_sar_raw_remove_unused_slc
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_sar_raw_remove_unused_slc

path_old=`pwd`

usage(){
  echo "[$PROG]Usage: ${PROG} "
  echo "[$PROG]Usage: e.g.,"
  echo "[$PROG]Usage:  "
}

while [ "$1" != "" ]; do
  case $1 in
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      usage
      exit 1
      ;;
  esac
  shift 2  
done


file_bl=../baseline_table.dat
file_dt=../data.in

nl_bl=`cat $file_bl | wc -l`
nl_dt=`cat $file_dt | wc -l`

if [ $nl_bl -ne 2 ]; then
  echo "[]ERROR: #lines of $file_bl is not 2!!"
  exit 1
fi

if [ $nl_dt -ne 2 ]; then
  echo "[]ERROR: $lines of $file_dt is not 2!!"
  exit 1
fi

files_slc=`find . -maxdepth 1 -type f -name "S1*ALL*.SLC"|sort`
for file_slc in $files_slc; do
  #echo $file_slc
  tid=`basename $file_slc | awk -F_ '{print $2}'`
  #echo $tid
  tmp=`grep -h $tid $file_bl`
  if [ "$tmp" == "" ]; then
    echo "[]INFO: deleting $tid files ..."
    echo "\rm -rf S1_${tid}*"
    \rm -rf S1_${tid}*
  else
    echo "[]INFO: keep $tid files."
  fi
done 
