#!/bin/sh

# Name:
#   sh_sar_intf_all_resample
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

PROG=sh_sar_intf_all_resample

path_old=`pwd`

usage_of_it(){
  echo "[$PROG]HELP: ${PROG} "
  echo "[$PROG]HELP:   [-s|-sf|-scale_factor SCALE_FACTOR]"
  echo "[$PROG]HELP:   [-p|-path INPUT_PATH]"
  echo "[$PROG]HELP:   [-o|-opath OUTPUT_PATH]"

  echo "[$PROG]HELP:   [-h|-help]"
  echo "[$PROG]HELP: e.g., in F1 (F2/F3) run"
  echo "[$PROG]HELP:   ${PROG} -file roi.kml -opath intf_all_roi"
}


path=intf_all
opath=

sf=2

while [ "$1" != "" ]; do
  case $1 in
    -s|-sf)
      sf=$2
      ;;
    -h|--help)
      echo "Usage: $PROG [-sf sacle_factor] [-path INTF_ALL]"
      exit
      ;;
    -p|-path)
      path=$2
      ;;
    -o|-opath)
      opath=$2
      ;;
    *)
      echo "[$PROG]ERROR: invlaid option ($1)!!"
      exit 1
      ;;
  esac

  shift 2
done

tmp=`dirname ${path}/test.txt`
path=`basename $tmp`

if [ "$opath" == "" ]; then
  opath=${path}_x${sf}
fi


echo "[$PROG]INFO: input path = $path"
echo "[$PROG]INFO: output path = $opath"
#exit


dirs=`ls $path/ | grep _  |grep "20[12][0-9]"`
dir=`echo $dirs | awk '{print $1}'`
#echo $dir
file_corr=${path}/${dir}/corr_cut.grd
#file_corr=${path}/${dir}/corr.grd

xs=`gmt grdinfo -C $file_corr | awk '{print int($8*2+.5)}'`
ys=`gmt grdinfo -C $file_corr | awk '{print int($9*2+.5)}'`
echo xs $xs ys $ys
I="-I${xs}/${ys}"
echo "[$PROG]INFO: output pixel size = $I"

#exit

npc=0
npu=0

for dir in $dirs; do
    echo "[$PROG]INFO: processing $dir ..."
    odir="${opath}/${dir}"
    if [ ! -d $odir ]; then
      echo "mkdir -p $odir"
      echo "mkdir -p $odir" | sh
    fi

    #echo "\cp -f ${path}/${dir}/unwrap_mask_ll.png ${odir}/"
    #echo "\cp -f ${path}/${dir}/unwrap_mask_ll.png ${odir}/" | sh
    
    file_corr=${path}/${dir}/corr_cut.grd
    #file_corr=${path}/${dir}/corr.grd
    ofile_corr=${odir}/`basename $file_corr`
    if [ ! -s $ofile_corr ]; then
    	echo "gmt grdsample $file_corr -G${ofile_corr} $I"
    	echo "gmt grdsample $file_corr -G${ofile_corr} $I" | sh
      npc=`expr $npc + 1`
    fi

    file_unwrap=${path}/${dir}/unwrap_mask.grd
    #file_unwrap=${path}/${dir}/unwrap.grd
    ofile_unwrap="${odir}/`basename $file_unwrap`"
    if [ ! -s $ofile_unwrap ]; then
    	echo "gmt grdsample $file_unwrap -G${ofile_unwrap} $I"
    	echo "gmt grdsample $file_unwrap -G${ofile_unwrap} $I" | sh
      npu=`expr $npu + 1`
    fi

    #exit
done

echo "[$PROG]INFO: #${npc} corr files and #${npu} unwrapped phase files processed."
echo "[$PROG]INFO: done."
