#!/bin/bash

# Name:
#   sh_esa_link_raworig
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorithm:
#   

# Dependency:
#   

if [ "$esa_unzip" = "" ]; then
    echo "[ERROR]ESA environment variable esa_unzip must be set first! Stopped."
    exit 1
fi

echo esa_unzip $esa_unzip


if [ "$1" = "" ]; then
    echo "Usage: sh_esa_link_raworig file [iw_type]"
    exit
fi
file=$1

if [ "$2" = "" ]; then
    echo "[INFO]iw_type not specified! Default iw1 used."
    iw_typ=iw1
else
    iw_typ=$2
fi



grep '^ ' $file | awk '{print $1}' > .tmp
while read line; do
    echo $line
    dfile="`echo $line | awk -F. '{print $1}'`.SAFE"
    if [ ! -d ${esa_unzip}/${dfile} ]; then
	echo -e "[$PROG]\033[1;33;41mERROR\033[0m:data not found [${path_esa}/${dfile}]!!"
	exit 1
    fi
    file_tiff=`find ${esa_unzip}/${dfile} -name "s1*-${iw_typ}-*-vv-*.tiff"`
    if [ "$file_tiff" == "" ]; then
    	echo -e "[$PROG]\033[1;33;41mERROR\033[0m: unzipped tiff file not found ($dfile)!!"
    	exit 1
    fi
    
    bname=`basename $file_tiff`
    if [ -s $bname ]; then
	#echo "[$PROG]INFO: already linked."
	continue
    fi

    echo "[$PROG]INFO: linking $bname ..."
    ln -s $file_tiff
    #find ${esa_unzip}/${dfile}/ -name "s1*-${iw_typ}-*-vv-*.tiff" -exec ln -s {} \;
    #echo " ${dfile} linked."
    
done < .tmp
