#!/bin/sh

# Name:
#   sh_sar_prep_sbases
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_sar_prep_sbases

function usage_of_it(){

    echo "Usage: $PROG -t TEMPORAL_BASELINE_THRESHOLD"
    echo "  input:"
    echo "    1) baseline_table.dat"
    echo "    2) intf.in"
    echo "  output:"
    echo "    1) intf.tab"
    echo "    2) scene.tab"
    
    echo "Example:"
    echo "  $PROG -t 0"
    echo "  $PROG -t 73,"
    echo "  $PROG -t 1,36"
    echo "  $PROG -t ,36"
    
    echo "Usage: $PROG -t 1,36 1,72 121,"
    echo "(c)Copyright 2017 Yunfeng Tian (tianyf@gmail.com)"
}


if [ ! -s baseline_table.dat ]; then
  echo "[$PROG]ERROR: no baseline_table.dat file!!"
  exit 1
fi

if [ ! -s intf.in ]; then
  echo "[$PROG]ERROR: no intf.in file!!"
  exit 1
fi

path_old=`pwd`

t1t2s='0, 1,12, 1,24 1,36 1,48 1,60 1,72 1,120 1,180 ,366  37, 73, 73,120 121, 181, 367, 121,500 367,900 700, 900,'
is_overwrite=n

while [ "$1" != "" ]; do
  case $1 in
    -t)
      t1t2s=$2
      ;;
    -o|-overwrite)
      is_overwrite=$2
      ;;
    -h)
      usage_of_it
      exit 1
      ;;
    *)
      echo "[$PROG]ERROR:invalid option ($1)!!"
      usage_of_it
      exit 1
      ;;
  esac
  shift 2
done

for t1t2 in $t1t2s; do
  t1=`echo $t1t2 | awk -F, '{print $1}'`
  t2=`echo $t1t2 | awk -F, '{print $2}'`
  
  cmdstr="sh_sar_prep_sbas"
  oname="b"
  if [ "$t1" == "" ]; then
    t1=1
  fi
  cmdstr="$cmdstr -t1 $t1"
  oname="${oname}${t1}-"
    
  if [ "$t2" != "" ]; then
    cmdstr="$cmdstr -t2 $t2"
    oname="${oname}${t2}"
  fi
  echo oname $oname
  echo $cmdstr
  
  cd $path_old
  pwd
  
  if [ ! -d $oname ]; then
    mkdir -p $oname
  fi
  if [ -s $oname/intf.tab1 -a -s $oname/scene.tab1 -a "$is_overwrite" != "y" ]; then
    echo "[$PROG]WARNING: data already exist in $oname! Skipped."
    continue
  fi
  
  cd $oname
  ln -s ../intf.in
  ln -s ../baseline_table.dat
  echo $cmdstr | sh
  cd ..
  
done
