#!/bin/sh

# Name:
#   sh_esa_s1_sbas_tar
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorithm:
#   

# Dependency:
#   

if [ "$1" = "" ]; then
  path=`pwd`
  out_path=`basename $path`
  echo out_path $out_path
else
  out_path=$1
fi
#exit


cmdstr="tar zcf ${out_path}.tar.gz vel_ll.kml vel_ll.png vel_ll_scalebar.jpg *.tab vel_mask_ll* rms_mask_ll3* look_mask_ll3* baseline* data.in f-baseline* incidence master.PRM S1_20*.LED"

if [ -s orb.psxy ];then
  cmdstr="$cmdstr orb.psxy orb.psxy.kml"
fi

echo $cmdstr
echo $cmdstr | sh

