#!/bin/sh

# Name:
#   sh_sar_gacos_time
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_sar_gacos_time

while [ "$1" != "" ]; do
  case $1 in
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      echo "[$PROG]Usage: ${PROG} "
      echo "[$PROG]Usage: e.g.,"
      echo "[$PROG]Usage: ${PROG} "
      exit 1
      ;;
  esac
  shift 2  
done

if [ ! -s input.lst.ok ]; then
  ehco "[]ERROR: input.lst.ok file not exist!!"
  exit 1
fi

mkdir -p gacos

fi=`find ./gacos -maxdepth 1 -type f -name "gacos.times*" | wc -l | awk '{print $1+1}'`
ofile="./gacos/gacos.times${fi}"
echo ofile $ofile
ofile="./gacos/gacos.times.`date  +%Y%m%dT%H%M%S`"
echo ofile $ofile
#  S1A_IW_SLC__1SSV_20141103T234438_20141103T234505_003124_003966_1553.manifest.safe           0.79818594
#  S1A_IW_SLC__1SSV_20141103T234503_20141103T234531_003124_003966_5F6E.manifest.safe           0.83602771
grep '^ ' input.lst.ok | awk -F_ '{print substr($6,1,8)}' | sort | uniq > $ofile
echo "[]INFO: done (output to $ofile)."