#!/bin/sh

# Name:
#   sh_sar_gacos_merge_ll
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorithm:
#   

# Dependency:
#   


PROG=sh_sar_gacos_merge_ll

path_old=`pwd`

path1=/g7b/gsar/gacos/099-a-m3-0081CA06_0087F6ED_0092696A-lijiang_deqin/ztd.ll
path2=/g7b/gsar/gacos/t99-f1255-f1265-a-m_honghe5_lijiang/ztd.ll
opath=./ztd.ll.merged

while [ "$1" != "" ]; do
  case $1 in
    -path1)
      path1=$2
      ;;
    -path2)
      path2=$2
      ;;
    -opath)
      opath=$2
      ;;
    *)
      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalide option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
done


mkdir -p $opath


files1=`find $path1 -maxdepth 1 -name "*_ll.grd" | sort`
for file1 in $files1; do
  cd $path_old

  bname=`basename $file1 | sed -e s'/.grd//g'`
  file2=${path2}/${bname}.grd
  if [ ! -s $file2 ]; then
    #echo "[]WARNING: no second file for $file1 !"
    continue
  fi
  echo "merging $file1 and $file2"

  ofile=${opath}/${bname}.grd
  if [ -s $ofile ]; then
    #echo "[]INFO: output file exist."
    continue
  fi


tmp1=`gmt grdinfo -C $file1`
echo tmp1 $tmp1
xmin1=`echo $tmp1 | awk '{print $2}'`
xmax1=`echo $tmp1 | awk '{print $3}'`
ymin1=`echo $tmp1 | awk '{print $4}'`
ymax1=`echo $tmp1 | awk '{print $5}'`

tmp2=`gmt grdinfo -C $file2`
echo tmp2 $tmp2
xmin2=`echo $tmp2 | awk '{print $2}'`
xmax2=`echo $tmp2 | awk '{print $3}'`
ymin2=`echo $tmp2 | awk '{print $4}'`
ymax2=`echo $tmp2 | awk '{print $5}'`

xmin=`echo $xmin1 $xmin2 | awk '{if($1>$2){print $2}else{print $1}}'`
xmax=`echo $xmax1 $xmax2 | awk '{if($1<$2){print $2}else{print $1}}'`
ymin=`echo $ymin1 $ymin2 | awk '{if($1>$2){print $2}else{print $1}}'`
ymax=`echo $ymax1 $ymax2 | awk '{if($1<$2){print $2}else{print $1}}'`

Ro= #"-R${xmin}/${xmax}/${ymin}/${ymax}"
echo "R $Ro"

Io= #`grdinfo -I $file1`
echo "I $Io"

  echo "$file1 - 1" > filelist
  echo "$file2 - 1" >> filelist
  echo "gmt grdblend filelist $Ro $Io -G${ofile}"
  echo "gmt grdblend filelist $Ro $Io -G${ofile}" | sh
 
  cd $opath
  pwd

    zmin=`gmt grdinfo -C ${bname}.grd | awk '{print $6}'`
    zmax=`gmt grdinfo -C ${bname}.grd | awk '{print $7}'`
    echo $zmin $zmax
    gmt makecpt -Cjet -T${zmin}/${zmax}/.001 -Z -I > phase.cpt
    gmt grdimage ${bname}.grd -JX5i -I${bname}.grd  -Cphase.cpt -Bxaf -Byaf -BWSne -P -V -X1.3i -Y3i -K > ${bname}.ps
    gmt psscale -R${bname}.grd  -J -DJTC+w5i/0.2i+h+e -Cphase.cpt -Baf+l"Zenith total delay (m)" -O >> ${bname}.ps
    gmt psconvert -Tj -P -Z ${bname}.ps
  
  #exit

done
