#!/bin/bash

# Name:
#   sh_slc_cut
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorithm:
#   

# Dependency:
#   

PROG=sh_slc_cut


usage_of_it(){
cat <<eob
$PROG
|_Clip area of interest from aligned SLC files.
|+
  -aligned SLC files (F?/raw/S1_*.*)
  -trans.dat (for converstion between WGS-84 and radar coordiante)
|<
  -r|-roi|-f|-file POLYGON_KML
  [-R RADAR_RANGES_IN_GMT_-R_FORM]
  [-o|-opath OUTPUT_PATH]
  [-ow|-overwrite WHETHER_OR_NOT_OVERWRITE_EXISTING]
  [-ds|-date_start|-start|-d1 STARTING_YYYYMMDD]
  [-de|-date_end|-end|-d2 ENDING_YYYYMMDD]
|>
  OUTPUT_PATH/S1_*.SLC
  OUTPUT_PATH/S1_*.LED
|e.g.,
  ${PROG} -r mine.kml
(c)iGPS (https://github.com/igps-ftk/)
eob
}


path_old=`pwd`

path=`pwd`/raw
opath=`pwd`/raw.cut
file_roi=
region_cut= #e.g., 15000/21000/000/2000
is_overwrite=n

date_start=20140101
date_end=20990101

while [ "$1" != "" ]; do
  case $1 in
    -r|-f|-roi|-file)
      cd `dirname $2`
      file_roi="`pwd`/`basename $2`"
      cd $path_old
      ;;
    -R)
      region_cut=$2
      ;;
    -o|-opath)
      opath=$2
      ;;
    -ow|-overwrite)
      is_overwrite=$2
      ;;
    -ds|-date_start|-start|-d1)
      date_start=$2
      ;;
    -de|-date_end|-end|-d2)
      date_end=$2
      ;;
    -h|-help|--help)
      usage_of_it
      exit 1
      ;;
    *)
      usage_of_it
      echo ""
      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
done

if [ "$file_roi" == "" -a "$region_cut" == "" ]; then
  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: at least one type of range MUST be given!!"
  echo "[$PROG]        1).ROI file (-file roi.kml)"
  echo "[$PROG]        2).rectangular ranges (XMIN/XMAX/YMIN/YMAX)"
  exit 1
fi


echo path $path 
echo opath $opath
echo file_roi $file_roi
echo region_cut $region_cut

if [ ! -d $opath ]; then
  mkdir -p $opath
fi
cd $opath
opath=`pwd`
cd $path_old

#get scene list from baseline_table.dat
cd $path_old

if [ ! -s baseline_table.dat ]; then
  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: no baseline_table.dat file in `pwd`!!"
  exit 1
fi
S1_list=
count=0
while read line; do
  S1_name=`echo $line | awk '{print $1}'`
  if [ $count -eq 0 ]; then
    S1_list=$S1_name
    count=1
    continue
  fi
  S1_date=`echo $S1_name | awk -F_ '{print $2}'`
  if [ $S1_date -lt $date_start -o $S1_date -gt $date_end ]; then
    continue
  fi
  S1_list="$S1_list $S1_name"
  count=`expr $count + 1`
  
done < baseline_table.dat

echo S1_list $S1_list
echo count $count


if [ "$region_cut" == "" ]; then

  gmt kml2gmt $file_roi > ${opath}/.tmp1
  cat ${opath}/.tmp1 |grep -v '>' | awk '{print $1,$2,0}'>  ${opath}/.roi.llh
  cat ${opath}/.roi.llh
  
  cd $opath
  #ln -s ../topo/trans.dat .
  
  proj_ll2ra_ascii.csh ${path}/../topo/trans.dat .roi.llh .roi.xyz
  cat .roi.xyz
  #cat .roi.xy | awk '{print $2,$1}' > .roi.xy2
  
  #exit
  
#  files=`find ../${path} -name "corr_cut.grd"`
#  file=`echo $files | awk '{print $1}'`
#  echo file $file
#  if [ "$file" == "" ]; then
    pI=-I4/1
#  else 
#    pI=`grdinfo -I $file`
#  fi
  echo pI $pI
  region_cut=`gmt gmtinfo $pI .roi.xyz | awk '{print substr($0,3)}'`
  cd ..
else
  region_cut="${region_cut}"
fi
echo "region_cut $region_cut"


cd $path
for S1_name in $S1_list ; do
  file=${S1_name}.PRM
  echo $file
  bname=`basename $file | sed -e 's/.PRM//g'`
  ofile="${opath}/${bname}"

  if [ -s ${ofile}.SLC -a "$is_overwrite" == "n" ]; then
    echo "[$PROG]INFO:already exist (${ofile}.SLC). Skipped."
    continue
  fi
  echo cut_slc $file _tmp1 $region_cut
  #continue
  echo cut_slc $file _tmp1 $region_cut | sh

  \mv -f _tmp1.PRM ${ofile}.PRM
  \mv -f _tmp1.SLC ${ofile}.SLC
  \cp -fp ${bname}.LED ${opath}/
  #exit
done

echo "[$PROG]INFO: done."