#!/bin/sh

# Name:
#   sh_sar_auto_grid_running_info
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
. ~/.bashrc

PROG=sh_sar_auto_grid_running_info

path_old=`pwd`

usage(){
  echo "[$PROG]Usage: ${PROG} "
  echo "[$PROG]Usage: e.g.,"
  echo "[$PROG]Usage:  "
}

timestamp=`date | sed -e 's/ /_/g' | sed -e 's/:/-/g'`
file_tmp=/sar/proc_gmtsar/auto_grid/script/event/running/log.running.${timestamp}

while [ "$1" != "" ]; do
  case $1 in
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      usage
      exit 1
      ;;
  esac
  shift 2  
done

date > $file_tmp
squeue -o "%R %.58j %T" | awk '{print $2}' | awk -F- '{print $NF, $2}' | sort | uniq | grep -v NAME >> $file_tmp
