#!/bin/sh

# Name:
#   sh_sar_cp_intf_png
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

PROG=sh_sar_cp_intf_png


if [ "$1" = "-h" -o "$1" = "-help" ]; then
    echo Usage: sh_sar_cp_los_ll_png [types]
    echo   "Types: los,phasefilt,unwrap_mask,..., default is los."
    exit 0
fi

types="los_ll phase unwrap"
types=los_ll.png
types=phasefilt_mask_ll.png



if [ "$1" != "" ]; then
  if [ `echo $1 | awk '{print index($0,",")}'` -gt 0 ]; then
    types=`echo $1 | sed -e 's/,/ /g'`
  elif [ "$1" == "l" ]; then
    types='los_ll.png'
  elif [ "$1" == "p" ]; then
    types='phasefilt_ll.png'
  elif [ "$1" == "u" ]; then
    types='unwrap_mask_ll.png'
  else
    types=`echo $1 | sed -e 's/,/ /g'`
  fi
  
fi

echo copy file types: $types
#exit

#if [ ! -d intf ]; then
#    echo "[$PROG]ERROR:directory intf not exist!!"
#    echo exit 1
#fi

if [ ! -d intf_all ]; then
    echo "[$PROG]WARNING:directory intf_all not exist! Create the link to intf."
    #ln -s intf intf_all
    exit 1
fi

#exit
path=./intf_all/
#path=./ia/

echo input path is $path

#path=./intf/
opath=./intf_all_png

mkdir -p $opath

for type in $types; do
    #echo $type
    pairs=`find $path -maxdepth 1 -type d -name "[12]*_[12]*"`
    for pair in $pairs; do
      #echo $pair

    files=`find $pair -maxdepth 1 -type f -name "${type}"`
    for file in $files; do
	tpath=`dirname $file`
	ofile=${opath}/`basename ${tpath}`-`basename $file`
        #echo ofile $ofile
	if [ -s $ofile ]; then
	    continue
	fi
	echo cp -fp $file $ofile
	echo cp -fp $file $ofile |sh
    done
    done
done

pwd
