#!/bin/sh

# Name:
#   sh_sar_sbas_reproj
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_sar_sbas_reproj

r=4
corr_min=.05
corr_direction=tail

while [ "$1" != "" ]; do

  case $1 in
    -r)
      r=$2
      ;;
    -corr_min)
      corr_min=$2
      ;;
    -corr_direction)
      corr_direction=$2
      ;;
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      exit 1
      ;;
  esac
  
  shift 2
      
done

case $r in
  1)
    filter=100;
    ;;
  2)
    filter=200;
    ;;
  3)
    filter=400;
    ;;
  4)
    filter=800;
    ;;
  1)
      echo "[$PROG]ERROR: invalid pixel size code ($r)!!"
      exit 1
    ;;
esac
    
\rm -f gauss_*
touch gauss_${filter}
ls -l gauss_*

proj_ra2ll.csh trans.dat vel.grd vel_ll.grd
grd2kml.csh vel_ll vel.cpt
sh_esa_s1_corr_mask -corr_min $corr_min -direction $corr_direction
sh_esa_s1_sbas_tar