#!/bin/sh

# Name:
#   sh_slurm_kill_job
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_slurm_kill_job

path_old=`pwd`

usage(){
  echo "[$PROG]Usage: ${PROG} -ptn PATTERN -kill y/n"
  echo "[$PROG]Usage: e.g.,"
  echo "[$PROG]Usage:  "
}

ptn=
is_kill=n

while [ "$1" != "" ]; do
  case $1 in
  	-p|-ptn)
  		ptn=$2
  		;;
  	-k|-kill)
  		is_kill=$2
  		;;
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      usage
      exit 1
      ;;
  esac
  shift 2  
done

if [ "$ptn" == "" ]; then
	echo "[$PROG]ERROR: no job identity given($ptn)!!"
	usage
	exit 1
fi
#
squeue -p intf -o "%A %R %.58j %T" | grep "$ptn"

if [ "$is_kill" == "y" ]; then
	pids=`squeue -p intf -o "%A %R %.58j %T" | grep $ptn | awk '{print $1}'`
	echo "[$PROG]INFO: to kill $pids"
	for pid in $pids; do
		echo "[$PROG]INFO:cancelling job $pid ..."
		scancel $pid
	done
fi 


