#!/bin/sh

# Name:
#   sh_sar_cal_sat_incidence
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

PROG=sh_sar_cal_sat_incidence



SAT=SAT
file=vel_ll

while [ "$1" != "" ]; do
    case $1 in
	-sat)
	    SAT=$2
	    ;;
	-file)
	    file=$2
	    ;;
	*)
	    echo "[$PROG]ERROR: invalid options $1 !!"
	    exit
	    ;;
    esac
    shift 2
done
echo Satellite sensor: ${SAT}


if [ ! -s ../topo/dem.grd ]; then
	echo "[$PROG]ERROR: dem.grd is missing (`pwd`/../topo/dem.grd)!!"
	exit 1
fi 


if [ ! -s ${file}.xyz ]; then
    echo "0. first convert ${file}.grd to XYZ format"
    if [ ! -s ${file}.grd ]; then
	echo "[$PROG]ERROR: ${file}.grd is missing!!"
	exit 1
    fi
    gmt grd2xyz ${file}.grd | grep -v NaN | awk '{print "",$0}' > ${file}.xyz
fi

cat ${file}.xyz | awk '{print $1,$2}' > _tmp_cal_sat_indicence.llde

files_prm=`ls ../topo/*.PRM | sort`
if [ $? -ne 0 ]; then
    echo "[]ERROR: error when searching PRM file!!"
    exit 1
fi
file_prm=`echo $files_prm | head -1 | awk '{print $1}'`
sid=`basename $file_prm | awk -F- '{print $3}'`


led_name=`grep led_file $file_prm | awk '{print $3}'`
if [ ! -s $led_name ]; then
  #for single subswath processing (F1/F2/F3)
  if [ -s ../raw/$led_name ]; then
    \cp -f ../raw/$led_name .
  elif [ -s ../topo/$led_name ]; then
    \cp -f ../topo/$led_name .
  elif [ -s ../../F1/raw/$led_name ]; then
    \cp -f ../../F1/raw/$led_name .
  else
    echo "[]ERROR:no LED file found($lef_name)!!"
    exit 1
  fi

fi

echo ln -s $file_prm 
echo ln -s $file_prm | sh 
file_prm=`basename $file_prm`

echo add_look.csh _tmp_cal_sat_indicence.llde $file_prm $SAT ../topo/dem.grd
echo add_look.csh _tmp_cal_sat_indicence.llde $file_prm $SAT ../topo/dem.grd | sh
#exit

cat _tmp_cal_sat_indicence.lltnde | awk '{print $4,$5,$6}' | sar_cal_sat_incidence | awk '{print 90-$1}' > _tmp_incidences
cat _tmp_incidences | mean | awk '{print $1}'


