#!/bin/sh

# Name:
#   sh_sitminus
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorithm:
#   

# Dependency:
#   

file1=$1
file2=$2

echo "#$file1"
echo "#$file2"

sites1=`rdsit $file1 | sort | uniq`
#sites2=`rdsit $file2 | sort | uniq`

for site in $sites1; do
    tmp=`grep -i $site $file2`
    if [ "$tmp" = "" ]; then
        echo " "$site
    fi
done
