#!/bin/sh

# Name:
#   sh_sar_node_clean_f123_SLC
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
oldpath=`pwd`

swaths='1 2 3'

grep '^ ' wc-l-20200408.txt > .tmp

while read line; do
  echo $line
  path=`echo $line | awk '{print $5}'`
  orbtype=`echo $path | awk '{if(index($1,"-a-")>0){print "asc"}else{print "des"}}'`

  echo $path $orbtype
  if [ "$orbtype" == "" ]; then
    continue
  fi
  #exit
  for i in $swaths; do
    if [ ! -d ${path}/${orbtype}_F${i} ]; then
      continue
    fi
    #files=`find ${path}/${orbtype}_F${i}/raw -name "S1*.SLC"`
    #files=`find ${path}/${orbtype}_F${i}/raw -name "s1*.tiff"`
    #echo "rm -rf ${path}/${orbtype}_F${i}/intf_all"
    echo "mv ${path}/${orbtype}_F${i} ${path}/F${i}"

    for file in $files; do
      echo rm $file

    done
    #exit
  done
done < .tmp
