#!/bin/sh

# Name:
#   sh_sar_copy_F
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_sar_copy_F

path=
opath=

while [ "$1" != "" ]; do
  case $1 in
    -path)
      path=$2
      ;;
    -opath)
      opath=$2
      ;;
    *)
      echo "[]ERROR: invalid option ($1)!!"
      exit 1
      ;;
  esac
  shift 2
done

if [ "$path" == "" ]; then
  echo "[]ERROR: no input path given!!"
  exit
fi

if [ "$opath" == "" ]; then
  echo "[]ERROR: no output path given!!"
  exit
fi

echo path $path
echo opath $opath

if [ ! -d $opath ]; then
  mkdir -p $opath
fi

rsync -avP $path/ba* $opath/
rsync -avP $path/da* $opath/
rsync -avP $path/intf.in* $opath/
rsync -avP $path/*.tab1 $opath/
rsync -avP $path/topo $opath/
ln -s $path/raw.cut $opath/raw
