#!/bin/sh

# Name:
#   sh_sar_clear_tmp_unzip
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   


PROG=sh_sar_clear_tmp_unzip

path_old=`pwd`

usage(){
  echo "[$PROG]Usage: ${PROG} -del y/n -path TEMPORARY_DIRECTORY"
  echo "[$PROG]Usage: e.g.,"
  echo "[$PROG]Usage:  "
}

is_del=

if [ "$esa_unzip" != "" ];then
	path_unzip=$esa_unzip
fi

while [ "$1" != "" ]; do
  case $1 in
  	-d|-del)
  		is_del=$2
  		;;
  	-p|-path)
  		path_unzip=$2
  		;;
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      usage
      exit 1
      ;;
  esac
  shift 2  
done


if [ "$path_unzip" == "" ]; then
	echo "[$PROG]ERROR: no unzipped S1 directory given ($path_unzip)!!"
	usage
	exit 1
fi

path_unzip=`dirname $path_unzip/test.txt` 

tmp=`echo $path_unzip | grep '_unzip$'`
if [ "$tmp" == "" ]; then
	echo "[$PROG]ERROR: not unzipped S1 directory ($path_unzip)!!"
	exit 1
fi

if [ ! -d $path_unzip ]; then
	echo "[$PROG]ERROR: directory not exist ($path_unzip)!!"
	exit 1
fi

echo "[$PROG]INFO: delete unzipped S1 files in $path_unzip"

nd=`find $path_unzip -maxdepth 1 -type d -name "S1*.SAFE" | wc -l`
dires=`find $path_unzip -maxdepth 1 -type d -name "S1*.SAFE" | sort`
di=0
for dire in $dires; do
	di=`expr $di + 1`
	echo "[]INFO: $di/$nd deleting $dire ..."
	echo "\rm -rf $dire"
	echo "\rm -rf $dire" | sh
done