#!/bin/sh

# Name:
#   sh_sar_xcorr_stat
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
gmtset FONT_TITLE			= 16p,Helvetica,black
gmtset FONT_ANNOT_PRIMARY		= 8p,Helvetica,black
gmtset FONT_LABEL			= 8p,Helvetica,black



files=`ls xcorr_*.dat0`
for file in $files; do
    avg=`cat $file | awk '{print $5}' | mean`
    echo $avg $file
    ofile=${file}.ps
    cat $file | awk '{print $5}' | pshistogram -JX5i -Bx10+l"Correlation $file" -By10+lCounts -BWSen+t"mean xcorr = ${avg}" -W2 -F -Gred -L.5p,gray -P  -V > $ofile
    psconvert -A -Tj $ofile
    #exit
done

