#!/bin/sh

# Name:
#   sh_sar_unwrap_mask_ll_png
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

path=`pwd`

if [ "`basename $path`" != "intf_all_detrend" ]; then
    echo "[]WARNING: this script is supposed to run in intf_all_detrend directory!"
    exit 1
fi

files=`find $path -name "unwrap_mask.grd"`
for file in $files; do
    echo $file
    path_cur=`dirname $file`
    #bname=`basename $file`
    #
    cd $path_cur
    pwd
    ln -s ../../topo/trans.dat
    touch gauss_400
    proj_ra2ll.csh trans.dat unwrap_mask.grd unwrap_mask_ll.grd
    makecpt -Cjet -T-10/10/.1 -Z > unwrap.cpt
    grd2kml.csh unwrap_mask_ll unwrap.cpt

    #exit
done
