#!/bin/sh
#sh_tsplot_sio
# Copyright: 
#   Yunfeng Tian on AUG-31-2007
# Purpose:
#   To plot SIO's coordinate time series products
#

#//////////SUBROUTINES///////////

#//////////MAIN PROGRAM//////////
#
if [ $# -lt 1 ]; then
    echo "Usage: sh_tsplot_sio file|pattern"
    exit
fi

echo "#sites: $#"

#temporary file names
tsn=.n
tse=.e
tsu=.u

gmtset HEADER_FONT_SIZE = 12p
gmtset LABEL_FONT_SIZE = 10p
gmtset ANNOT_FONT_SIZE_PRIMARY = 8p

tstype=RAW
tstype="Cleaned NEU Position"
while [ "$1" !=  "" ];do
    file=`pwd`/$1
    ofile=${file}.ps
    site=`echo $1 | awk '{print toupper(substr($0,1,4))}'`
    echo "Creating plot for ${file} .."

    #Up
    `grep -v "^#" $file | awk '{print $1,$6*1000,$9*1000}' > ${tsu}`
    R=`minmax -I.1/.5 ${tsu}`
    R1=`minmax -C ${tsu}`
    stepx=`echo $R1 | awk '{if ($2-$1 >=4 ) print 2;else print 1;}'`
    stepx=`echo $R1 | awk '{print int(($2-$1)/5)+1}'`
    stepy=`echo $R1 | awk '{print int(($4-$3)/25+1)*5}'`
    stepy2=`echo $stepy | awk '{print $1/2}'`
    #echo $stepx $stepy $R1
    psxy ${tsu} $R -JX6i/2.5i  -Ba${stepx}f0.5:"Year":/a${stepy}f${stepy2}:"Up (mm)":/SWne -Sc0.08c -Gblue -Ey0/2/250/200/20 -P -K -U"ICD GMF Produced by sh_tsplot_sio"> ${ofile}

    #East
    `grep -v "^#" $file | awk '{print $1,$5*1000,$8*1000}' > ${tse}`
    R=`minmax -I.1/.5 ${tse}`
    R1=`minmax -C ${tse}`
    stepy=`echo $R1 | awk '{print int(($4-$3)/25+1)*5}'`
    stepy2=`echo $stepy | awk '{print $1/2}'`
    psxy ${tse} $R -JX6i/2.5i  -Ba${stepx}f0.5:"":/a${stepy}f${stepy2}:"East (mm)":/SWne -Sc0.05c -Gblue -Y3i -Ey0/2/250/200/20 -O -K >> ${ofile}

    #North
    `grep -v "^#" $file | awk '{print $1,$4*1000,$7*1000}' > ${tsn}`
    R=`minmax -I.1/.5 ${tsn}`
    R1=`minmax -C ${tsn}`
    stepy=`echo $R1 | awk '{print int(($4-$3)/25+1)*5}'`
    stepy2=`echo $stepy | awk '{print $1/2}'`
    psxy ${tsn} $R -JX6i/2.5i  -Ba${stepx}f0.5/a${stepy}f${stepy2}:"North (mm)"::."${tstype} Time Series for ${site}":SWNe -Sc0.05c -Gblue -Y3i -Ey0/2/250/200/20 -O >> ${ofile}


    #convert postscript to jpeg file
    ps2raster ${ofile} 
    ps2raster -A -Tf ${ofile} 
    shift 1
done
\rm -f ${tsn} ${tse} ${tsu}
