#!/bin/sh

# Name:
#   sh_txtfile_minus
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   
if [ $# -ne 2 ]; then
    echo "Usage: sh_txtfile_minus file1 file2"
    exit 1
fi

file1=$1
file2=$2

while read line; do
    #echo input:  $line
    tmp=`grep "$line" $file2`
    if [ "$tmp" = "" ]; then
	echo $line
    fi
done < $file1

