#!/bin/sh

# Name:
#   sh_vel2sdm
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

usage_of_it(){
    echo "Usage: sh_vel2sdm [-xmin XMIN] [-xmax XMAX] [-ymin YMIN] [-ymax YMAX] [-ofile OUT_FILE]"
    echo "  Defaults:"
    echo "    xmin=$xmin"
    echo "    xmax=$xmax"
    echo "    ymin=$ymin"
    echo "    ymax=$ymax"
    echo "    ofile=$ofile"
    echo "  Inputs:"
    echo "    1) vel_ll.grd"
    echo "    2) rms_ll.grd"
    echo "(c)Copyright 2017   Yunfeng Tian (tianyf@gmail.com)"
}

xmin=92.3
xmax=92.4
ymin=29.775
ymax=29.875
ofile=vel_asc.xyze

while [ "$1" != "" ]; do
    case $1 in
	-xmin)
	    xmin=$2
	    ;;
	-xmax)
	    xmax=$2
	    ;;
	-ymin)
	    ymin=$2
	    ;;
	-ymax)
	    ymax=$2
	    ;;
	-ofile)
	    ofile=`pwd`/$2
	    ;;
	-h)
	    usage_of_it
	    exit 1
	    ;;
	*)
	    echo "[]ERROR: invalid input $1"
	    usage_of_it
	    exit 1
	    ;;
    esac
    shift 2
done

grdcut vel_ll.grd -Gvel_ll_cut.grd -R${xmin}/${xmax}/${ymin}/${ymax}
grdcut rms_ll.grd -Grms_ll_cut.grd -R${xmin}/${xmax}/${ymin}/${ymax}

grd2xyz vel_ll_cut.grd > vel_ll_cut.xyz
grd2xyz rms_ll_cut.grd > rms_ll_cut.xyz

paste vel_ll_cut.xyz rms_ll_cut.xyz > vel_rms_ll_cut.xyz

grep -iv 'nan'  vel_rms_ll_cut.xyz | awk '{print $2,$1,$3,$6}' > $ofile
