#!/bin/sh

# Purpose:
# [default]:
#   Get the sp3 orbit files for the latest week.
#   3 weeks latency in SOPAC database.
#   Run each week.

. ${HOME}/.bashrc

if [ "$IGS_ROOT" == "" ]; then
#local_root=/export/home/tianyf/tmp/products
#local_root=/cygdrive/e/igs/pub/products
#local_root=/data0/igs0/pub/products
local_root=/data0/igs0/pub/products
local_root=/d2/ftp/pub/products
local_root=/g3c/pub/products
local_root=/g10a/ftp/pub/products
else
  local_root=${IGS_ROOT}/products
fi


#yearStart=1994
#yearStart=2008
#yearEnd=2008

#doys=001
#doye=`ymd2ydoy ${yearStart} 12 31 | awk '{print $2}'`
#doye=89

#starting date: > 3 weeks
#  the first day of the 4th previous week.
#1.find the first day of current week.
year=`date -u +%Y`
#yy=`date -u +%y`
#mo=`date -u +%m`
#dd=`date -u +%d`
#doy=`ymd2ydoy ${year} ${mo} ${dd} | awk '{print $2}'`
doy=`date -u +%j`

#year=2015
#doy=21
echo Today in UTC is $year $doy

gpsw=`doy ${year} ${doy} |grep "GPS Week" | awk '{print $3}'`
#gpsd=`doy ${year} ${doy} | grep "GPS Week" | awk '{print $7}' | awk -F, '{print $1}'`
doy=`doy ${gpsw}W 0 | head -1 | awk '{print $6}'`
year=`doy ${gpsw}W 0 | head -1 | awk '{print substr($2,1,4)}'`

echo "The first day in current GPS week (${gpsw}) is $year $doy "

#2.find the first day of 4 week ago.
doy=`expr $doy - 21`
if [ $doy -le 0 ]; then
    year=`expr $year - 1`
    ndays=`ymd2ydoy $year 12 31 | awk '{print $2}'`
    doy=`expr $ndays + $doy`
fi
#echo $year $doy
yearStart=$year
yearEnd=$year
doys=$doy
doye=`expr $doys + 6`
ndoyr=`ymd2ydoy $year 12 31|awk '{print $2}'`
if [ $doye -gt $ndoyr ]; then
    doye=`expr $doye - $ndoyr`
    yearEnd=`expr $yearEnd + 1`
fi


echo Three weeks ago in UTC is $yearStart  $doys
echo "End of session: $yearEnd $doye"
#exit

orbit=IGSF

# process command-line parameters
#####################################################
#COMMAND LINE PARAMETERS
#####################################################
while [ "$1" != "" ]
do
  #echo $1
  case $1 in
      -dir)
	  cd $2
	  local_root=$2
	  ;;
      -orbit)
	  orbit=$2
	  ;;
      -yrs)
	  yearStart=$2
	  yr=`echo $yearStart | awk '{print substr($0,3,2)}'`
	  y=`echo $yearStart | awk '{print substr($0,4,1)}'`
	  ndays=`ymd2ydoy ${yearStart} 12 31 | awk '{print $2}'`
	  ;;
      -yre)
	  yearEnd=$2
	  ;;
      -doys)
	  doys=$2
	  ;;
      -doye)
	  doye=$2
	  ;;
      -sites)
	  sites=$2
	  sites=`echo $sites | awk -F, '{for (i=1;i<=NF;i++) print $i}'`
	  ;;
      -sitefile)
	  sfile=$2
	  
	  sites=`sh_site_read $sfile`
	  #echo $sites
	  ;;
      *)
	  echo "invalid options: $1"
	  exit 1
	  ;;
  esac
  shift 2
done
#echo $sites

if [ $yearStart -lt 50 ] ; then
  yearStart=`expr $yearStart + 2000`
fi
if [ $yearStart -ge 50 -a $yearStart -lt 100 ]; then
  yearStart=`expr $yearStart + 1900`
fi

if [ $yearEnd -lt 50 ] ; then
  yearEnd=`expr $yearEnd + 2000`
fi
if [ $yearEnd -ge 50 -a $yearEnd -lt 100 ]; then
  yearEnd=`expr $yearEnd + 1900`
fi



#echo $sites

#exit

hr=
case $orbit in
    IGSF)
	orbt=s
	;;
    IGSR)
	orbt=r
	;;
    IGSR)
	orbt=u
	hr="_18"
	;;
    *)
	echo "Invalid orbit type: $orbit."
	exit 1
	;;
esac

year=${yearStart}
echo year $year yearEnd $yearEnd
#exit
while [ ${year} -le ${yearEnd} ]; do

    if [ ${year} -eq ${yearStart} ]; then
	doy=${doys}
    else
       doy=001
    fi

    if [ ${year} -eq ${yearEnd} ]; then
	ndays=${doye}
    else
	ndays=`ymd2ydoy ${year} 12 31 | awk '{print $2}'`
    fi

    yy=`echo $year | awk '{print substr($0,3,2)}'`

    while [ ${doy} -le ${ndays} ]; do
        doy=`echo $doy | awk '{printf("%03d",$0)'}`
	gpsw=`doy ${year} ${doy} |grep "GPS Week" | awk '{printf("%04d", $3)}'`
	gpsd=`doy ${year} ${doy} |grep "GPS Week" | awk '{print $7}' | awk -F, '{print $1}'`
        week_dir=${local_root}/${gpsw}
        mkdir -p ${week_dir}
        cd ${week_dir}
        pwd

	echo "wget -nc --http-user=anonymous --http-password=tianyf@gmail.com http://garner.ucsd.edu/pub/products/${gpsw}/igs${gpsw}${gpsd}.sp3.Z"
	#if [ "${orbt}" = "u" ]; then
	#wget -c --http-user=anonymous --http-password=tianyf@gmail.com http://garner.ucsd.edu/pub/products/${gpsw}/ig${orbt}${gpsw}${gpsd}${hr}.sp3.Z
	wget -nc --http-user=anonymous --http-password=tianyf@gmail.com http://garner.ucsd.edu/pub/products/${gpsw}/ig${orbt}${gpsw}${gpsd}${hr}.sp3.Z
        #wget -nc --http-user=anonymous --http-password=tianyf@gmail.com ftp://igs.gnsswhu.cn/pub/gps/products/${gpsw}/ig${orbt}${gpsw}${gpsd}${hr}.sp3.Z

	###wget -nc --http-user=anonymous --http-password=tianyf@gmail.com http://garner.ucsd.edu/pub/products/${gpsw}/ig${orbt}${gpsw}${gpsd}${hr}.clk.Z
	#else
	#    wget -c --http-user=anonymous --http-password=tianyf@gmail.com http://garner.ucsd.edu/pub/products/${gpsw}/ig${orbt}${gpsw}${gpsd}.sp3.Z
	#fi
	if [ $gpsd -eq 6 ]; then
	    #wget -nc --http-user=anonymous --http-password=tianyf@gmail.com http://garner.ucsd.edu/pub/products/ig${orbt}${gpsw}7.erp.Z
echo	    wget -nc --http-user=anonymous --http-password=tianyf@gmail.com http://garner.ucsd.edu/pub/products/${gpsw}/ig${orbt}${gpsw}7.erp.Z
	fi
	doy=`expr $doy + 1`
    done
    year=`expr $year + 1`
done
