PRO IND_2IN1, ARR0, ARR1, INDEX=INDEX
  IF N_PARAMS() LT 2 THEN BEGIN
    ARR0 = INDGEN(10)
    ARR1 = [3,5,6]
  ENDIF

  INDEX=-1
  FOR I=0, N_ELEMENTS(ARR1)-1 DO BEGIN
    POS=WHERE(ARR0 EQ ARR1[I])
    IF POS[0] EQ -1 THEN CONTINUE
    INDEX=[INDEX,POS]
  ENDFOR
  IF N_ELEMENTS(INDEX) LE 1 THEN RETURN
  INDEX=INDEX[1:*]
  ;PRINT,INDEX
END