#!/bin/sh

ids=`grep '^ ' ../ids`
#ids=`cat ../ids_12`
#ids="2 3 4 5 6 7 8 9 10 11"
ids="19 20"

for id in $ids; do
  if [ $id -le 1 ]; then
    echo continue
    continue
  fi

  cmdstr1='yum -y install samba'
  cmdstr2='systemctl enable smb'
  cmdstr3='systemctl restart smb'
  cmdstr4='systemctl status smb'
  cmdstr5="rsync -avP /sar/admin/smb/smb.conf node${id}:/etc/samba/"

  echo  starting yum installer on node${id} with command $cmdstr1 and $cmdstr2
  #ssh node${id} $cmdstr5
  ssh node${id} $cmdstr3


  #exit
done


