#!/bin/sh

ids=`cat ../ids`
#ids=`cat ../ids_12`
ids="19 20"

file='vsftpd.conf'
for id in $ids; do
  echo scp ./$file node${id}:/etc/vsftpd/
  echo scp ./$file node${id}:/etc/vsftpd/ | sh

  #exit
done


for id in $ids; do
  if [ $id -eq 1 ]; then
    echo continue
  fi
  echo "restarting vsftpd service on node${id} ..."
  ssh node${id} "systemctl restart vsftpd"
done
