#!/bin/sh

# Name:
#   sh_mount_ac
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

PROG=sh_mount_ac


this_host=`hostname`
echo "[$PROG]INFO: this host is $this_host"
node_type=`echo $this_host | awk '{print substr($1,1,5)}'`
echo "[$PROG]INFO: node type is $node_type"
if [ "$node_type" != "gpsac" ]; then
  echo "[$PROG]ERROR: only run in gpsac servers!!"
  exit 1
fi

host_short=`echo $this_host | sed -e 's/gpsac/g/g'`
#echo "mount --bind /home/tianyf /${host_short}h"
#echo "mount --bind /home/tianyf /${host_short}h" | sh

#exit 0

targets="gpsac3 gpsac4 gpsac5 gpsac6 gpsac7 gpsac9 gpsac10 gpsac12 gpsac13 gpsac14 gpsac15 gpsac16 gpsac18 gpsac19"
#targets="gpsac3 gpsac4"


while [ "$1" != "" ]; do
  case $1 in
    -target)
      targets=`echo $2 | sed -e 's/,/ /g'`
      ;;
    *)
      echo "[$PROG]ERROR: invalid option ($1)!!"
      echo "[$PROG]Usage: ${PROG} "
      echo "[$PROG]Usage: e.g.,"
      echo "[$PROG]Usage: ${PROG} "
      exit 1
      ;;
  esac
  shift 2  
done

 

for target in $targets; do
  case $target in
    gpsac3)
#target=gpsac3
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
echo   mount ${target}:/g3a /g3a
echo   mount ${target}:/g3b /g3b
  #mount ${target}:/g5c /g5c
  #mount ${target}:/g5d /g5d
echo   mount ${target}:/home/tianyf /g3h
fi
			;;
    gpsac4)

#target=gpsac4
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  #mount ${target}:/usr/local/fftw-3.3.7 /usr/local/fftw-3.3.7
  #mount ${target}:/usr/local/GMT-5.4.2i /usr/local/GMT-5.4.2i
  #mount ${target}:/usr/local/szip-2.1i /usr/local/szip-2.1i
  #mount ${target}:/usr/local/zlib-1.2.11i /usr/local/zlib-1.2.11i
  #mount ${target}:/usr/local/hdf5-1.8.19i /usr/local/hdf5-1.8.19i
  #mount ${target}:/usr/local/gmt5sar20170823i /usr/local/gmt5sar20170823i
  #mount ${target}:/usr/local/gamit-v10.61 /usr/local/gamit-v10.61
  #mount ${target}:/usr/local/gamit-v10.7 /usr/local/gamit-v10.7
  #mount ${target}:/usr/local/bin /usr/local/bin
  #mount ${target}:/composer_xe_2015.3.187/ /composer_xe_2015.3.187/
    
echo   mount ${target}:/usr/local/orbits/ /usr/local/orbits/
  
  #mount ${target}:/home/tianyf/iGPS /home/tianyf/iGPS
  #mount ${target}:/home/tianyf/iGPS.addon/ /home/tianyf/iGPS.addon/
  
echo   mount ${target}:/g4b /g4b
echo   mount ${target}:/g4c /g4c
echo   mount ${target}:/g4d /g4d
  
echo   mount ${target}:/opt /opt
else
  echo 
  #mount -t cifs -o username=GMTSAR,password=123456,uid=501,dir_mode=0755 //10.4.28.111/tian /cloud1
echo   mount -t cifs -o username=ICDSAR,password=123abc,uid=501,dir_mode=0755,vers=3.0 //10.4.134.28/SARData2 /g4e
  #mount 10.4.134.54:/s1data /g4f

fi
#exit

			;;
    gpsac5)
#target=gpsac5
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
echo   mount ${target}:/home/g5a /g5a
echo   mount ${target}:/g5b /g5b
echo   mount ${target}:/g5c /g5c
echo   mount ${target}:/g5d /g5d
echo   mount ${target}:/home/tianyf /g5h
fi


			;;
    gpsac6)
#target=gpsac6
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  #mount ${target}:/usr/local/dcw-gmt-1.1.4 /usr/local/dcw-gmt-1.1.4
  #mount ${target}:/usr/local/gshhg-gmt-2.3.7 /usr/local/gshhg-gmt-2.3.7
  #mount ${target}:/usr/local/GMT-6.0.0 /usr/local/GMT-6.0.0
  #mount ${target}:/usr/local/gmt5sar20200529 /usr/local/gmt5sar20200529
echo   mount ${target}:/usr/local/MATLAB /usr/local/MATLAB
echo   mount ${target}:/g6b /g6b
echo   mount ${target}:/g6c /g6c
echo   mount ${target}:/g6d /g6d
echo   mount ${target}:/g6e /g6e
echo   mount ${target}:/g6f /g6f
echo   mount ${target}:/g6g /g6g
echo   mount ${target}:/home/tianyf/ /g6h
fi

			;;
    gpsac7)
#target=gpsac7
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
echo   mount ${target}:/g7b /g7b
echo   mount ${target}:/g7c /g7c
echo   mount ${target}:/g7d /g7d
#echo   mount ${target}:/g7e /g7e
echo   mount ${target}:/g7f /g7f
echo   mount ${target}:/g7g /g7g
echo   mount ${target}:/home/tianyf /g7h
#echo   mount ${target}:/g7i /g7i

fi

			;;
    gpsac9)
#target=gpsac9
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
echo   mount ${target}:/g9a /g9a
echo   mount ${target}:/g9b /g9b
  #mount ${target}:/g9c /g9c
echo   mount ${target}:/g9d /g9d
echo   mount ${target}:/home/tianyf /g9h
echo   mount ${target}:/g9n /g9n
fi

			;;
    gpsac10)
#target=gpsac10
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."

echo   mount ${target}:/g10a /g10a
echo   mount ${target}:/g10b /g10b
echo   mount ${target}:/g10c /g10c
echo   mount ${target}:/g10d /g10d
echo   mount ${target}:/home/tianyf /g10h
fi

			;;
    gpsac12)
#target=gpsac12
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
echo   mount ${target}:/g12a /g12a
echo   mount ${target}:/g12b /g12b
echo   mount ${target}:/g12c /g12c
echo   mount ${target}:/g12d /g12d
echo   mount ${target}:/g12e /g12e
echo   mount ${target}:/g12f /g12f
echo   mount ${target}:/home/tianyf /g12h
fi

			;;
    gpsac13)
#target=gpsac13
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
echo   mount ${target}:/g13a /g13a
echo   mount ${target}:/g13b /g13b
echo   mount ${target}:/home/g13c /g13c
echo   mount ${target}:/g13d /g13d
echo   mount ${target}:/g13e /g13e
echo   mount ${target}:/g13f /g13f
  #mount ${target}:/g13g /g13g
echo   mount ${target}:/home/tianyf /g13h
fi

			;;
    gpsac14)
#target=gpsac14
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  #mount ${target}:/g14a /g14a
echo   mount ${target}:/g14b /g14b
echo   mount ${target}:/g14c /g14c
echo   mount ${target}:/g14d /g14d
echo   mount ${target}:/g14e /g14e
echo   mount ${target}:/g14f /g14f
echo   mount ${target}:/g14g /g14g
echo   mount ${target}:/home/tianyf /g14h
echo   mount ${target}:/g14i /g14i
echo   mount ${target}:/g14n /g14n
echo   mount ${target}:/g14o /g14o


fi


			;;
    gpsac15)
#target=gpsac15
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
echo   mount ${target}:/g15a /g15a
echo   mount ${target}:/g15b /g15b
echo   mount ${target}:/g15c /g15c
echo   mount ${target}:/g15d /g15d
echo   mount ${target}:/g15e /g15e
echo   mount ${target}:/g15f /g15f
  #mount ${target}:/g15g /g15g
echo   mount ${target}:/home/tianyf /g15h
echo   mount ${target}:/g15n /g15n

fi

			;;
    gpsac16)
#target=gpsac16
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
echo   mount ${target}:/g16a /g16a
  #mount ${target}:/g16b /g16b
echo   mount ${target}:/g16c /g16c
echo   mount ${target}:/g16d /g16d
echo   mount ${target}:/g16e /g16e
echo   mount ${target}:/g16f /g16f
echo   mount ${target}:/g16g /g16g
echo   mount ${target}:/g16h /g16h
echo   mount ${target}:/g16i /g16i
echo   mount ${target}:/g16j /g16j
echo   mount ${target}:/g16n /g16n
echo   mount ${target}:/g16o /g16o

fi
			;;


#gpsac17)
##target=gpsac17
#if [ "$this_host" != "$target" ]; then
#  echo "[$PROG]INFO: mounting ${target}'s shares..."
#  #mount ${target}:/g17a /g17a
#  #mount ${target}:/g17b /g17b
#  ##mount ${target}:/g17c /g17c
#  ##mount ${target}:/g17d /g16d
#  ##mount ${target}:/g16e /g16e
#  ##mount ${target}:/g16f /g16f
#  ##mount ${target}:/g16g /g16g
#  #mount ${target}:/home/tianyf /g17h
#  ##mount ${target}:/g16i /g16i
#  ##mount ${target}:/g16j /g16j
#  #mount ${target}:/g17n /g17n
#  ##mount ${target}:/g16o /g16o
#
#fi

    gpsac18)
target=gpsac18
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  echo "mount ${target}:/home/tianyf /g18h"
  #echo "mount ${target}:/g18a /g18a"
fi
      ;;

    gpsac19)
target=gpsac19
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  echo "mount ${target}:/home/tianyf /g19h"
  #echo "mount ${target}:/g19a /g19a"
fi
      ;;



#target=vmicd
#if [ "$this_host" != "$target" ]; then
#  echo "[$PROG]INFO: mounting ${target}'s shares..."
#  #mount ${target}:/c2/lhasa_block/ /home/lhasa_block/
#  #mount ${target}:/c2/hfilesi.v18  /home/hfilesi.gmf.v3
#  echo ""
#fi

#
#target=vmshare
#if [ "$this_host" != "$target" ]; then
#  echo "[$PROG]INFO: mounting ${target}'s shares..."
#  echo ""
#fi

		*)
		  echo "[]WARNING: invalid server ($target)!"
			;;
  esac
  
done
