#!/bin/sh

# Name:
#   sh_mount_ac
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

PROG=sh_mount_ac


this_host=`hostname`
echo "[$PROG]INFO: this host is $this_host"
node_type=`echo $this_host | awk '{print substr($1,1,5)}'`
echo "[$PROG]INFO: node type is $node_type"
if [ "$node_type" != "gpsac" ]; then
  echo "[$PROG]ERROR: only run in gpsac servers!!"
  exit 1
fi

host_short=`echo $this_host | sed -e 's/gpsac/g/g'`
echo "mount --bind /home/tianyf /${host_short}h"
echo "mount --bind /home/tianyf /${host_short}h" | sh

#exit 0

target=gpsac3
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  mount ${target}:/g3a /g3a
  mount ${target}:/g3b /g3b
  #mount ${target}:/g5c /g5c
  #mount ${target}:/g5d /g5d
  mount ${target}:/home/tianyf /g3h
fi


target=gpsac4
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  #mount ${target}:/usr/local/fftw-3.3.7 /usr/local/fftw-3.3.7
  #mount ${target}:/usr/local/GMT-5.4.2i /usr/local/GMT-5.4.2i
  #mount ${target}:/usr/local/szip-2.1i /usr/local/szip-2.1i
  #mount ${target}:/usr/local/zlib-1.2.11i /usr/local/zlib-1.2.11i
  #mount ${target}:/usr/local/hdf5-1.8.19i /usr/local/hdf5-1.8.19i
  #mount ${target}:/usr/local/gmt5sar20170823i /usr/local/gmt5sar20170823i
  #mount ${target}:/usr/local/gamit-v10.61 /usr/local/gamit-v10.61
  #mount ${target}:/usr/local/gamit-v10.7 /usr/local/gamit-v10.7
  #mount ${target}:/usr/local/bin /usr/local/bin
  #mount ${target}:/composer_xe_2015.3.187/ /composer_xe_2015.3.187/
    
  mount ${target}:/usr/local/orbits/ /usr/local/orbits/
  
  #mount ${target}:/home/tianyf/iGPS /home/tianyf/iGPS
  #mount ${target}:/home/tianyf/iGPS.addon/ /home/tianyf/iGPS.addon/
  
  mount ${target}:/g4b /g4b
  mount ${target}:/g4c /g4c
  mount ${target}:/g4d /g4d
  
  mount ${target}:/opt /opt
else
  echo 
  #mount -t cifs -o username=GMTSAR,password=123456,uid=501,dir_mode=0755 //10.4.28.111/tian /cloud1
  mount -t cifs -o username=ICDSAR,password=123abc,uid=501,dir_mode=0755,vers=3.0 //10.4.134.28/SARData2 /g4e
  #mount 10.4.134.54:/s1data /g4f

fi
#exit

target=gpsac5
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  mount ${target}:/home/g5a /g5a
  mount ${target}:/g5b /g5b
  mount ${target}:/g5c /g5c
  mount ${target}:/g5d /g5d
  mount ${target}:/home/tianyf /g5h
fi


target=gpsac6
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  #mount ${target}:/usr/local/dcw-gmt-1.1.4 /usr/local/dcw-gmt-1.1.4
  #mount ${target}:/usr/local/gshhg-gmt-2.3.7 /usr/local/gshhg-gmt-2.3.7
  #mount ${target}:/usr/local/GMT-6.0.0 /usr/local/GMT-6.0.0
  #mount ${target}:/usr/local/gmt5sar20200529 /usr/local/gmt5sar20200529
  mount ${target}:/usr/local/MATLAB /usr/local/MATLAB
  mount ${target}:/g6b /g6b
  mount ${target}:/g6c /g6c
  mount ${target}:/g6d /g6d
  mount ${target}:/g6e /g6e
  mount ${target}:/g6f /g6f
  mount ${target}:/g6g /g6g
  mount ${target}:/home/tianyf/ /g6h
fi

target=gpsac7
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  mount ${target}:/g7b /g7b
  mount ${target}:/g7c /g7c
  mount ${target}:/g7d /g7d
  mount ${target}:/g7e /g7e
  mount ${target}:/g7f /g7f
  mount ${target}:/g7g /g7g
  mount ${target}:/home/tianyf /g7h
  mount ${target}:/g7i /g7i

fi

target=gpsac9
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  mount ${target}:/g9a /g9a
  mount ${target}:/g9b /g9b
  #mount ${target}:/g9c /g9c
  mount ${target}:/g9d /g9d
  mount ${target}:/home/tianyf /g9h
  mount ${target}:/g9n /g9n
fi

target=gpsac10
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."

  mount ${target}:/g10a /g10a
  mount ${target}:/g10b /g10b
  mount ${target}:/g10c /g10c
  mount ${target}:/g10d /g10d
  mount ${target}:/home/tianyf /g10h
fi

target=gpsac12
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  mount ${target}:/g12a /g12a
  mount ${target}:/g12b /g12b
  mount ${target}:/g12c /g12c
  mount ${target}:/g12d /g12d
  mount ${target}:/g12e /g12e
  mount ${target}:/g12f /g12f
  mount ${target}:/home/tianyf /g12h
fi

target=gpsac13
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  mount ${target}:/g13a /g13a
  mount ${target}:/g13b /g13b
  mount ${target}:/home/g13c /g13c
  mount ${target}:/g13d /g13d
  mount ${target}:/g13e /g13e
  mount ${target}:/g13f /g13f
  #mount ${target}:/g13g /g13g
  mount ${target}:/home/tianyf /g13h
fi

target=gpsac14
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  #mount ${target}:/g14a /g14a
  mount ${target}:/g14b /g14b
  mount ${target}:/g14c /g14c
  mount ${target}:/g14d /g14d
  mount ${target}:/g14e /g14e
  mount ${target}:/g14f /g14f
  mount ${target}:/g14g /g14g
  mount ${target}:/home/tianyf /g14h
  mount ${target}:/g14i /g14i
  mount ${target}:/g14n /g14n
  mount ${target}:/g14o /g14o


fi


target=gpsac15
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  mount ${target}:/g15a /g15a
  mount ${target}:/g15b /g15b
  #mount ${target}:/home/g15c /g15c
  mount ${target}:/g15d /g15d
  mount ${target}:/g15e /g15e
  mount ${target}:/g15f /g15f
  #mount ${target}:/g15g /g15g
  mount ${target}:/home/tianyf /g15h
  mount ${target}:/g15n /g15n

fi

target=gpsac16
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  mount ${target}:/g16a /g16a
  #mount ${target}:/g16b /g16b
  mount ${target}:/g16c /g16c
  mount ${target}:/g16d /g16d
  mount ${target}:/g16e /g16e
  mount ${target}:/g16f /g16f
  mount ${target}:/g16g /g16g
  mount ${target}:/g16h /g16h
  mount ${target}:/g16i /g16i
  mount ${target}:/g16j /g16j
  mount ${target}:/g16n /g16n
  mount ${target}:/g16o /g16o

fi



target=gpsac17
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  #mount ${target}:/g17a /g17a
  #mount ${target}:/g17b /g17b
  ##mount ${target}:/g17c /g17c
  ##mount ${target}:/g17d /g16d
  ##mount ${target}:/g16e /g16e
  ##mount ${target}:/g16f /g16f
  ##mount ${target}:/g16g /g16g
  #mount ${target}:/home/tianyf /g17h
  ##mount ${target}:/g16i /g16i
  ##mount ${target}:/g16j /g16j
  #mount ${target}:/g17n /g17n
  ##mount ${target}:/g16o /g16o

fi



target=vmicd
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  #mount ${target}:/c2/lhasa_block/ /home/lhasa_block/
  #mount ${target}:/c2/hfilesi.v18  /home/hfilesi.gmf.v3
  echo ""
fi


target=vmshare
if [ "$this_host" != "$target" ]; then
  echo "[$PROG]INFO: mounting ${target}'s shares..."
  echo ""
fi
