#!/bin/sh

ids=`grep '^ ' ../ids`
#ids=`cat ../ids_12`
#ids="4 5 8 9"
ids="19 20"

for id in $ids; do
  if [ $id -le 1 ]; then
    echo continue
    continue
  fi

  cmdstr1='systemctl enable vncserver@:1'
  cmdstr2="systemctl start vncserver@:1"
  echo  starting VNC on node${id} with command $cmdstr2 and $cmdstr1
  ssh node${id} $cmdstr1
  ssh node${id} $cmdstr2


  #exit
done


