#!/bin/sh


host_name=`hostname`
echo host name $host_name
id_cur=`echo $host_name | sed -e 's/[a-z]//g' | sed -e 's/[A-Z]//g'`
echo current host id $id_cur
host_type=`echo $host_name | sed -e 's/[0-9]//g'`
echo host type $host_type

file_ids=../ids.${host_name}
if [ ! -s $file_ids ]; then
  echo "[$PROG]ERROR:file $file_ids not exist!!"
  exit
fi

ids=`grep '^ ' $file_ids`
#ids=`cat ../ids_12`
echo ids $ids
#exit

for id in $ids; do

  files="./${host_name}/.bashrc"
  files="$files ./${host_name}/.cshrc"
  #files="$files ./${host_name}/.gmtversions"
  
  for file in $files; do
    echo scp $file ${host_type}${id}:/home/tianyf/
    echo scp $file ${host_type}${id}:/home/tianyf/ | sh
    #continue
  done
  
  #exit
done

