#!/bin/sh

ids=`grep '^ ' /sar/admin/ids`
#ids=`cat ../ids_12`

for id in $ids; do
  if [ $id -eq 1 ]; then
    echo continue
  fi

  cmdstr='rm -rf /home/tianyf/gsar/temp'
  cmdstr2='mkdir -p /home/tianyf/gsar/temp'

  cmdstr='rm /home/tianyf/gg'
  cmdstr2='ln -s /usr/local/gamit-v10.71 /home/tianyf/gg'

  echo  clear temp directory  on node${id} with command $cmdstr
  echo "ssh node${id} $cmdstr"
  echo "ssh node${id} $cmdstr" |sh
  echo "ssh node${id} $cmdstr2"
  echo "ssh node${id} $cmdstr2" | sh
  #exit
done


