c+
cName:
c     rnxdc
cPurpose:
c     Delete post-header-comments which are generated by teqc combination.
cInputs:
c     file - input RINEX filename
c     ofile - output filename
c     flag - (boolean) output to standard output? (1=yes)
c-
      program rnxdc


c     variables declaration:
      character*1023 file,ofile
      character*80 strbuf,flag,strtmp
      integer ioerr,ui,uo,tmp(2),nskip
      logical eof
      integer nblen,iargc,i

      
c     executable clauses:

c     get command-line parameters
      if (iargc().lt.2) then
         write(*,*) 'Usage: rnxdc filein fileout [1]'
         stop
      endif
c     input file name
      call getarg(1,file)
c     output file name
      call getarg(2,ofile)
c     output to terminal flag
      if (iargc().ge.3) then
         call getarg(3,flag)
      endif
c     vefify parameters:
      write(*,*) 'Input: ',file(1:nblen(file))
      write(*,*) 'Output: ', ofile(1:nblen(ofile))
      if (flag.eq.'1')  write(*,*) 'Options: also output to terminal.'


c     file handle
c     ui-unit in
      ui=61
c     uo-unit out
      uo=71
      open(unit=ui,file=file,status='old',err=82)
      open(unit=uo,file=ofile,err=81)
      eof=.false.
      do while(.NOT.eof)
c        rinex v2.1 line length is assumed to be 80!
         read(ui,'(A80)',end=81) strbuf
c         write(*,*) strbuf(1:nblen(strbuf))
         call strtrim(strbuf,strtmp)
c         write(*,*) strtmp(1:nblen(strtmp))
c         read(strbuf,'(I2)') tmp(1)
         if (strtmp(1:2).eq.'4 ') then
            write(*,*) strbuf(1:nblen(strbuf))
            read(strbuf,*) tmp
            write(*,91) tmp(2)
 91         format('skip the following ',I3,' lines...')
            do i=1, tmp(2)+1
                read(ui,'(A80)',end=81) strbuf
            enddo
         endif
c         write(*,*) strbuf(1:nblen(strbuf))
         write(uo,'(a)') strbuf(1:nblen(strbuf))
c         write(*,*) strtmp(1:nblen(strtmp))
      enddo
      close(uo)
 81   continue
      close(ui)     


 82   continue
      end


