 rerun of cmonoc gmf + sio igs[1-6] with 139 stablization sites

 +++++++++++++++++++++++++++++++++++++
 + GLORG                 Version 5.16X +
 +++++++++++++++++++++++++++++++++++++


 Stabilization with  20.0% constant,  80.0% site dependent weighting.
 Delete sites with   4.0-sigma condition.
 Height variance factor      10.00 Position,     10.00 Velocity
 For Position: Min dH sigma 0.0050 m;    Min RMS 0.0030 m,    Min dNE sigma 0.00050 m
 For Velocity: Min dH sigma 0.0050 m/yr; Min RMS 0.0030 m/yr, Min dNE sigma 0.00010 m/yr
 Sigma Ratio to allow use: Position   2.00 Velocity   2.00

====================================================================================================
 Starting Position stabilization iteration   1 L0812281200_vsbl.glx
 For    7 sites in origin, min/max height sigma      62.00     86.91 mm; Median       65.82 mm, Tol      10.00 mm L0812281200_vsbl.glx
 Removing IRKT_GPS from orgin condition, height sigma      80.62 mm, Ratio Tol  2.000 L0812281200_vsbl.glx
 Removing TROM_GPS from orgin condition, height sigma      86.91 mm, Ratio Tol  2.000 L0812281200_vsbl.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -1.24927 +-    0.22060 Iter  1 L0812281200_vsbl.glx
 Y Rotation  (mas)    -2.07040 +-    0.22133 Iter  1 L0812281200_vsbl.glx
 Z Rotation  (mas)    22.60469 +-    0.11832 Iter  1 L0812281200_vsbl.glx
 X Translation (m)     0.01089 +-    0.00663 Iter  1 L0812281200_vsbl.glx
 Y Translation (m)    -0.05505 +-    0.00661 Iter  1 L0812281200_vsbl.glx
 Z Translation (m)    -0.06969 +-    0.00368 Iter  1 L0812281200_vsbl.glx
 Scale       (ppb)    -1.74830 +-    1.17377 Iter  1 L0812281200_vsbl.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
MADR_8PS   1.00  NRC1_GPS   1.00  GOLD_1HT   1.00  DAEJ_GPS   1.00  MATE_1PS   1.00 
 For   15 Position Iter  1 Pre RMS    0.2585 m; Post RMS   0.00497 m L0812281200_vsbl.glx
 For    5 sites in origin, min/max NE sigma       4.09      7.00 mm; Median        6.06 mm, Tol       3.94 mm L0812281200_vsbl.glx

====================================================================================================
 Starting Position stabilization iteration   2 L0812281200_vsbl.glx
 For    5 sites in origin, min/max height sigma      62.00     68.97 mm; Median       65.58 mm, Tol      10.00 mm L0812281200_vsbl.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -1.28190 +-    0.20320 Iter  2 L0812281200_vsbl.glx
 Y Rotation  (mas)    -2.11306 +-    0.21883 Iter  2 L0812281200_vsbl.glx
 Z Rotation  (mas)    22.61605 +-    0.11360 Iter  2 L0812281200_vsbl.glx
 X Translation (m)     0.00998 +-    0.00636 Iter  2 L0812281200_vsbl.glx
 Y Translation (m)    -0.05281 +-    0.00628 Iter  2 L0812281200_vsbl.glx
 Z Translation (m)    -0.06960 +-    0.00354 Iter  2 L0812281200_vsbl.glx
 Scale       (ppb)    -2.12167 +-    1.09784 Iter  2 L0812281200_vsbl.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
MADR_8PS   0.81  NRC1_GPS   1.11  GOLD_1HT   1.12  DAEJ_GPS   1.01  MATE_1PS   0.91 
 For   15 Position Iter  2 Pre RMS    0.2586 m; Post RMS   0.00472 m L0812281200_vsbl.glx
 For    5 sites in origin, min/max NE sigma       3.38      7.77 mm; Median        6.05 mm, Tol       5.33 mm L0812281200_vsbl.glx

====================================================================================================
 Starting Position stabilization iteration   3 L0812281200_vsbl.glx
 For    5 sites in origin, min/max height sigma      62.00     68.97 mm; Median       65.58 mm, Tol      10.00 mm L0812281200_vsbl.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -1.29813 +-    0.19814 Iter  3 L0812281200_vsbl.glx
 Y Rotation  (mas)    -2.13490 +-    0.21872 Iter  3 L0812281200_vsbl.glx
 Z Rotation  (mas)    22.60764 +-    0.11247 Iter  3 L0812281200_vsbl.glx
 X Translation (m)     0.00930 +-    0.00628 Iter  3 L0812281200_vsbl.glx
 Y Translation (m)    -0.05170 +-    0.00619 Iter  3 L0812281200_vsbl.glx
 Z Translation (m)    -0.06956 +-    0.00351 Iter  3 L0812281200_vsbl.glx
 Scale       (ppb)    -2.24054 +-    1.06550 Iter  3 L0812281200_vsbl.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
MADR_8PS   0.75  NRC1_GPS   1.13  GOLD_1HT   1.19  DAEJ_GPS   1.00  MATE_1PS   0.85 
 For   15 Position Iter  3 Pre RMS    0.2625 m; Post RMS   0.00467 m L0812281200_vsbl.glx
 For    5 sites in origin, min/max NE sigma       3.19      8.48 mm; Median        5.88 mm, Tol       5.38 mm L0812281200_vsbl.glx

====================================================================================================
 Starting Position stabilization iteration   4 L0812281200_vsbl.glx
 For    5 sites in origin, min/max height sigma      62.00     68.97 mm; Median       65.58 mm, Tol      10.00 mm L0812281200_vsbl.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -1.30891 +-    0.19697 Iter  4 L0812281200_vsbl.glx
 Y Rotation  (mas)    -2.14939 +-    0.21874 Iter  4 L0812281200_vsbl.glx
 Z Rotation  (mas)    22.59056 +-    0.11206 Iter  4 L0812281200_vsbl.glx
 X Translation (m)     0.00873 +-    0.00626 Iter  4 L0812281200_vsbl.glx
 Y Translation (m)    -0.05095 +-    0.00616 Iter  4 L0812281200_vsbl.glx
 Z Translation (m)    -0.06957 +-    0.00350 Iter  4 L0812281200_vsbl.glx
 Scale       (ppb)    -2.24877 +-    1.05393 Iter  4 L0812281200_vsbl.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
MADR_8PS   0.73  NRC1_GPS   1.11  GOLD_1HT   1.26  DAEJ_GPS   0.98  MATE_1PS   0.83 
 For   15 Position Iter  4 Pre RMS    0.2651 m; Post RMS   0.00467 m L0812281200_vsbl.glx
 For    5 sites in origin, min/max NE sigma       3.17      9.18 mm; Median        5.56 mm, Tol       4.77 mm L0812281200_vsbl.glx

====================================================================================================
 Starting Position stabilization iteration   5 L0812281200_vsbl.glx
 For    5 sites in origin, min/max height sigma      62.00     68.97 mm; Median       65.58 mm, Tol      10.00 mm L0812281200_vsbl.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -1.31732 +-    0.19633 Iter  5 L0812281200_vsbl.glx
 Y Rotation  (mas)    -2.16192 +-    0.21817 Iter  5 L0812281200_vsbl.glx
 Z Rotation  (mas)    22.56963 +-    0.11128 Iter  5 L0812281200_vsbl.glx
 X Translation (m)     0.00825 +-    0.00624 Iter  5 L0812281200_vsbl.glx
 Y Translation (m)    -0.05027 +-    0.00614 Iter  5 L0812281200_vsbl.glx
 Z Translation (m)    -0.06958 +-    0.00347 Iter  5 L0812281200_vsbl.glx
 Scale       (ppb)    -2.22965 +-    1.04620 Iter  5 L0812281200_vsbl.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
MADR_8PS   0.73  NRC1_GPS   1.08  GOLD_1HT   1.33  DAEJ_GPS   0.94  MATE_1PS   0.81 
 For   15 Position Iter  5 Pre RMS    0.2678 m; Post RMS   0.00470 m L0812281200_vsbl.glx
 For    5 sites in origin, min/max NE sigma       3.22      9.93 mm; Median        5.13 mm, Tol       3.82 mm L0812281200_vsbl.glx
 Removing GOLD_1HT from orgin condition, NE sigma       9.93 mm, Ratio Tol  2.000 L0812281200_vsbl.glx

====================================================================================================
 Starting Position stabilization iteration   6 L0812281200_vsbl.glx
 For    4 sites in origin, min/max height sigma      62.00     68.97 mm; Median       65.70 mm, Tol      10.00 mm L0812281200_vsbl.glx

 Position system stabilization results 
 --------------------------------------- 
 X Rotation  (mas)    -1.45934 +-    0.19234 Iter  6 L0812281200_vsbl.glx
 Y Rotation  (mas)    -2.30512 +-    0.22700 Iter  6 L0812281200_vsbl.glx
 Z Rotation  (mas)    22.38115 +-    0.10670 Iter  6 L0812281200_vsbl.glx
 X Translation (m)     0.00070 +-    0.00610 Iter  6 L0812281200_vsbl.glx
 Y Translation (m)    -0.04272 +-    0.00604 Iter  6 L0812281200_vsbl.glx
 Z Translation (m)    -0.06996 +-    0.00350 Iter  6 L0812281200_vsbl.glx
 Scale       (ppb)    -2.07937 +-    0.90927 Iter  6 L0812281200_vsbl.glx
 Condition Sigmas used     0.0000    0.0000    0.0000    0.0000    0.0000    0.0000    0.0000
Sites and relative sigmas used in stabilization
MADR_8PS   0.79  NRC1_GPS   1.24  DAEJ_GPS   1.02  MATE_1PS   0.90 
 For   12 Position Iter  6 Pre RMS    0.2491 m; Post RMS   0.00340 m L0812281200_vsbl.glx
 For    4 sites in origin, min/max NE sigma       2.66      6.60 mm; Median        3.24 mm, Tol       1.16 mm L0812281200_vsbl.glx
 Removing NRC1_GPS from orgin condition, NE sigma       6.60 mm, Ratio Tol  2.000 L0812281200_vsbl.glx
Rotating into local coordinates for equates
 Checking covariance matrix after equate and force
 rerun of cmonoc gmf + sio igs[1-6] with 139 stablization sites


---------------------------------------------------------
 GLOBK Ver 5.16X, Global solution
---------------------------------------------------------

 Solution commenced with: 2008/12/28  0: 0    (2008.9891)
 Solution ended with    : 2008/12/28 23:59    (2008.9918)
 Solution refers to     : 2008/12/28 11:59    (2008.9904) [Seconds tag  45.000]
 Satellite IC epoch     : 2008/12/28 12: 0  0.00
 GPS System Information : Time GPST Frame J2000 Precession IAU76 Radiation model BERNE Nutation IAU80 Gravity EGM96
 MODELS Used in Analysis: SD-WOB  SD-UT1  RAY-MOD E-Tide  K1-Tide PoleTideOC-Load MeanPTD  
 Run time               :    9/ 8/25  0:37 47.00

 There were         1 exps from          1 global files in the solution
 There were       134194 data used,       0 data not used and       134194 data total
 There were          520 global parameters estimated
 There were   50 stations,    0 radio sources, and   32 satellites

 The  prefit chi**2 for     515 input parameters is     0.040

 LIST file      : L0812281200_vsbl.glx
 COMMON file    : comb.com
 GLOBK CMD file : globk_comb.cmd
 GLORG CMD file : glorg_comb.cmd
 APRIORI file   : ../tables/lfile.
 APRIORI file   : ../tables/itrf2005.apr.updated
 APRIORI file   : ../tables/lfile. (glorg)
 APRIORI file   : ../tables/itrf2005.apr.updated (glorg)
 NUTATION file  :  
 PLANETARY file :  
 SD ORIENT file :  
 PMU file       : ../tables/pmu.usno
 BACK SOLN file :  
 OUTGLOBAL file :  
 SVS EPHEM file : comb.svs_Z
 SVS MARKOV file:  
 EARTHQUAKE file: ../tables/eq_file.all

 There were  702 site renames listed.  Renames used are: 
   #   Orig     New          Specific  Period from   ----->      To              Position change (m)       Type
  38 GOLD_GPS->GOLD_1PS                 1996/ 1/ 1  0: 0  2100/ 1/ 1  0: 0      0.0000     0.0000     0.0000 XYZ
  40 GOL2_GPS->GOL2_1PS                 1995/10/31  0: 0  2100/ 1/ 1  0: 0      0.0000     0.0000     0.0000 XYZ
  73 MAD2_GPS->MAD2_2PS                 2000/11/ 6  0: 0  2100/ 1/ 1  1: 0      0.0000     0.0000     0.0000 XYZ
  77 MATE_GPS->MATE_1PS                 1999/ 6/18  0: 0  2100/ 1/ 1  1: 0      0.0000     0.0000     0.0000 XYZ
 364 CAGL_GPS->CAGL_2PS                 2001/ 7/11  0: 0  2100/ 1/ 1  0: 0      0.0000     0.0000     0.0000 XYZ
 418 FAIR_GPS->FAIR_6PS                 2004/12/22 21:10  2100/ 1/ 1  0: 0      0.0000     0.0000     0.0000 XYZ
 480 KUNM_GPS->KUNM_1PS                 2004/12/26  0:58  2100/ 1/ 1  0: 0      0.0000     0.0000     0.0000 XYZ
 507 MADR_GPS->MADR_8PS                 2000/ 6/30  0: 0  2100/ 1/ 1  0: 0      0.0000     0.0000     0.0000 XYZ
 586 REYK_GPS->REYK_2PS                 2000/ 6/21  0:52  2100/ 1/ 1  0: 0      0.0000     0.0000     0.0000 XYZ
 637 TRO1_GPS->TRO1_3PS                 2004/ 7/13  7:34  2100/ 1/ 1  0: 0      0.0000     0.0000     0.0000 XYZ
 678 WTZR_GPS->WTZR_2PS                 1996/ 9/ 1  0: 0  2100/ 1/ 1  0: 0      0.0000     0.0000     0.0000 XYZ
 690 ZIMM_GPS->ZIMM_1PS                 1998/11/ 6  0: 0  2100/ 1/ 1  0: 0      0.0000     0.0000     0.0000 XYZ
 701 BJFS_GPS->BJFS_6EQ                 2006/ 7/ 4  0: 0  2100/ 1/ 1  1: 0      0.0000     0.0000     0.0000 XYZ

 There were   15 earthquakes listed.  Earthquakes used are:
  #  CODE     Lat (deg)  Long (deg) Radius (km) Depth (km)    Date       Rename?
  4   NR      34.2800   241.4400     150.0000     9.7200 1994/ 1/17 12:30  YES
  8   HT      34.5900   243.7300     200.0000     5.0000 1999/10/16 11:46  YES
 13   DN      63.7400   212.3100     600.0000    10.0000 2002/11/ 5  0: 3  YES
 15   SU       4.5000    95.0000    2500.0000    20.0000 2004/12/26  0:57  YES

 COSEISMIC characteristics
 #  CODE              Static sigma               Spatial Sigma (Depth/Dist)^2
               North      East       Height (m)    North     East       Height (m)
  4   NR      1.0000     1.0000     1.0000       1.8000     1.8000     0.7000
  8   HT      0.0010     0.0010     0.0010       1.8000     1.8000     0.7000
 13   DN      1.0000     1.0000     1.0000       1.8000     1.8000     0.7000
 15   SU      1.0000     1.0000     1.0000       2.0000     2.0000     2.0000

 PRE-SEISMIC characteristics
 #  CODE    Dur              Static Process           Spatial Process (Depth/Dist)^2
          (days)    North      East       Height        North     East       Height
                             (mm^2/day)                       (mm^2/day)
  4   NR    0.0     0.0000     0.0000     0.0000       0.0000     0.0000     0.0000
  8   HT    0.0     0.0000     0.0000     0.0000       0.0000     0.0000     0.0000
 13   DN    0.0     0.0000     0.0000     0.0000       0.0000     0.0000     0.0000
 15   SU    0.0     0.0000     0.0000     0.0000       0.0000     0.0000     0.0000

 POST-SEISMIC characteristics
 #  CODE    Dur              Static Process           Spatial Process (Depth/Dist)^2
          (days)    North      East       Height        North     East       Height
                             (mm^2/day)                       (mm^2/day)
  4   NR   60.0     0.1000     0.1000     0.1000       1.8000     1.8000     0.7000
  8   HT   90.0     0.1000     0.1000     0.1000       1.8000     1.8000     0.7000
 13   DN  100.0     0.1000     0.1000     0.1000       1.8000     1.8000     0.7000
 15   SU    0.0     0.0000     0.0000     0.0000       0.0000     0.0000     0.0000

 POST-SEISMIC LOG Estimates
 #  CODE    Tau              Static Log           Spatial Process (Depth/Dist)^2
          (days)    North      East       Height        North     East       Height
                               (mm)                       (mm)
  4   NR    0.0     0.0000     0.0000     0.0000       0.0000     0.0000     0.0000
  8   HT    0.0     0.0000     0.0000     0.0000       0.0000     0.0000     0.0000
 13   DN    0.0     0.0000     0.0000     0.0000       0.0000     0.0000     0.0000
 15   SU    0.0     0.0000     0.0000     0.0000       0.0000     0.0000     0.0000

 Summary of GLOBK command file globk_comb.cmd
-------------------------------------------------------------------------------
* Globk command file to combine solutions
  make_svs comb.svs Z
  com_file comb.com
  srt_file comb.srt
* earthquake file
x eq_file ../tables/IGS_steps_070112.eq_file
x eq_file ../tables/eq_file.global
x eq_file ../tables/eq_file.china
 eq_file ../tables/eq_file.all
#  earth-rotation values
x   (not needed if pmu free in final combination; pmu.bull_b begins only at 1 Jan 1992)
 in_pmu  ../tables/pmu.usno
# apr site file(s)
  apr_file ../tables/lfile.
  apr_file ../tables/itrf2005.apr.updated
#     (1) Max chi**2, (2) Max prefit diff, (3) Max rotation; defaults are 100 10000 10000
  max_chi 30 50 2000.0
x  max_chii 13 3
* Apply the pole tide whenever not applied in GAMIT
  app_ptid ALL
# Allow the network to be loose since using glorg for stabilization
  apr_neu  all  10 10 10  0 0 0
# Satellites are loose if combining with global SOPAC H-files
#                X       Y      Z    XDOT  YDOT  ZDOT  DRAD YRAD ZRAD BRAD XRAD DCOS DSIN YCOS YSIN BCOS BSIN
  apr_svs all   100     100    100   10     10    10    1     1  .02  .02  .02 . 02  .02 . 02 . 02  .02 . 02
#  tight if not combining with global data
x  apr_svs all .05 .05 .05 .005 .005 .005 .01 .01 F F F F F F F F F F F F F F F
# Keep EOP loose
  apr_wob  100.  100.  10. 10.0  0.0  0.0  0.0  0.0
  apr_ut1  100.  10.  0.0  0.0  0.0  0.0
x  mar_wob  36500 36500 365 365 0 0 0 0
x  mar_ut1  36500 365 0 0 0 0
#  unless not using global data
x  apr_wob  .25 .25  .001 .001 0 0 0 0
x  apr_ut1  .25 .25 .001 .001 0 0
x  mar_wob    1 1  .001 .001
x  mar_ut1    1 .001
* Estimate translation   -   .0005 m**2/yr = 15 mm/half-yr
 apr_tran .005 .005 .005 0 0 0
 apr_scale 1. 1.
x mar_tran .0025 .0025 .0025 0 0 0
x mar_scale 365 0
# Set minimal globk print options since using glorg output
   prt_opt cdms gdlf
# Invoke glorg for stabilization
  org_cmd glorg_comb.cmd
  org_opt cmds psum gdlf
x  out_glb  H------_cmon.GLX
  descr rerun of cmonoc gmf + sio igs[1-6] with 139 stablization sites
  use_site clear
*vsbl
 use_site ARM1
 use_site ARM2
 use_site BAY1
 use_site BAY2
 use_site CAGL
 use_site CAGZ
 use_site DARR
 use_site DARW
 use_site DAV1
 use_site DAVR
 use_site GOL2
 use_site GOLD
 use_site IRKJ
 use_site IRKT
 use_site LHAS
 use_site LHAZ
 use_site MAD2
 use_site MADR
 use_site MAT1
 use_site MATE
 use_site NRC1
 use_site NRC2
 use_site OHI2
 use_site OHI3
 use_site REYK
 use_site REYZ
 use_site TCMS
 use_site THU2
 use_site THU3
 use_site TID1
 use_site TID2
 use_site TNML
 use_site TRO1
 use_site TROM
 use_site WTZA
 use_site WTZJ
 use_site WTZR
 use_site WTZT
 use_site WTZZ
 use_site YAR1
 use_site YAR2
 use_site YARR
 use_site ZIMJ
 use_site ZIMM
 use_site BJFS
 use_site BUCU
 use_site CHAT
 use_site DAEJ
 use_site FAIR
 use_site JPLM
 use_site KUNM
 use_site LPGS
*global stablization sites
 use_site ALAC
 use_site ALBH
 use_site ALGO
 use_site ALIC
 use_site AMC2
 use_site ARP3
 use_site ARTU
 use_site AUCK
 use_site AZRY
 use_site BAHR
 use_site BARH
 use_site BBRY
 use_site BILI
 use_site BOGO
 use_site BOR1
 use_site BRMU
 use_site BRUS
 use_site BUCU
 use_site CAGS
 use_site CAS1
 use_site CASC
 use_site CCJM
 use_site CEDU
 use_site CHAT
 use_site CHUM
 use_site CHUR
 use_site CIC1
 use_site COCO
 use_site CRAO
 use_site CRO1
 use_site DAEJ
 use_site DARW
 use_site DAV1
 use_site DRAO
 use_site DUBO
 use_site ELRO
 use_site EPRT
 use_site FLIN
 use_site FTS1
 use_site GENO
 use_site GLPT
 use_site GLSV
 use_site GODE
 use_site GOLD
 use_site GRAS
 use_site GRAZ
 use_site HELG
 use_site HERS
 use_site HNPT
 use_site HOB2
 use_site HOFN
 use_site HOLB
 use_site HRAO
 use_site IISC
 use_site IRKT
 use_site ISTA
 use_site JOZE
 use_site JPLM
 use_site KABR
 use_site KARR
 use_site KELS
 use_site KELY
 use_site KERG
 use_site KOSG
 use_site KOUR
 use_site KYW1
 use_site LAMP
 use_site MAC1
 use_site MADR
 use_site MAG0
 use_site MALI
 use_site MAR6
 use_site MAS1
 use_site MATE
 use_site MAUI
 use_site MCM4
 use_site MDO1
 use_site MKEA
 use_site MOB1
 use_site MONP
 use_site NANO
 use_site NEWP
 use_site NKLG
 use_site NLIB
 use_site NOT1
 use_site NOUM
 use_site NPRI
 use_site NRC1
 use_site NRIL
 use_site NYAL
 use_site ONSA
 use_site OUSD
 use_site PDEL
 use_site PENC
 use_site PERT
 use_site PIE1
 use_site POL2
 use_site POTS
 use_site PTBB
 use_site PUR3
 use_site RABT
 use_site RAMO
 use_site REYZ
 use_site RIGA
 use_site RIOG
 use_site SANT
 use_site SCH2
 use_site SEAT
 use_site SELE
 use_site SFER
 use_site SJDV
 use_site SNI1
 use_site SOFI
 use_site SOL1
 use_site STJO
 use_site SUWN
 use_site SYOG
 use_site THTI
 use_site TIDB
 use_site TIXI
 use_site TOW2
 use_site TRAB
 use_site TROM
 use_site TSKB
 use_site ULAB
 use_site UPO1
 use_site USNA
 use_site USNO
 use_site UZHL
 use_site VAAS
 use_site VILL
 use_site VIS0
 use_site VNDP
 use_site VTIS
 use_site WGTN
 use_site WHIT
 use_site WILL
 use_site WROC
 use_site YELL
-------------------------------------------------------------------------------

 Summary of GLORG command file glorg_comb.cmd
-------------------------------------------------------------------------------
* Standard glorg coordinate solution processing
x  apr_file ../tables/itrf05.apr
  apr_file ../tables/lfile.
  apr_file ../tables/itrf2005.apr.updated
  stab_site clear
 stab_site ALAC
 stab_site ALBH
 stab_site ALGO
 stab_site ALIC
 stab_site AMC2
 stab_site ARP3
 stab_site ARTU
 stab_site AUCK
 stab_site AZRY
 stab_site BAHR
 stab_site BARH
 stab_site BBRY
 stab_site BILI
 stab_site BOGO
 stab_site BOR1
 stab_site BRMU
 stab_site BRUS
 stab_site BUCU
 stab_site CAGS
 stab_site CAS1
 stab_site CASC
 stab_site CCJM
 stab_site CEDU
 stab_site CHAT
 stab_site CHUM
 stab_site CHUR
 stab_site CIC1
 stab_site COCO
 stab_site CRAO
 stab_site CRO1
 stab_site DAEJ
 stab_site DARW
 stab_site DAV1
 stab_site DRAO
 stab_site DUBO
 stab_site ELRO
 stab_site EPRT
 stab_site FLIN
 stab_site FTS1
 stab_site GENO
 stab_site GLPT
 stab_site GLSV
 stab_site GODE
 stab_site GOLD
 stab_site GRAS
 stab_site GRAZ
 stab_site HELG
 stab_site HERS
 stab_site HNPT
 stab_site HOB2
 stab_site HOFN
 stab_site HOLB
 stab_site HRAO
 stab_site IISC
 stab_site IRKT
 stab_site ISTA
 stab_site JOZE
 stab_site JPLM
 stab_site KABR
 stab_site KARR
 stab_site KELS
 stab_site KELY
 stab_site KERG
 stab_site KOSG
 stab_site KOUR
 stab_site KYW1
 stab_site LAMP
 stab_site MAC1
 stab_site MADR
 stab_site MAG0
 stab_site MALI
 stab_site MAR6
 stab_site MAS1
 stab_site MATE
 stab_site MAUI
 stab_site MCM4
 stab_site MDO1
 stab_site MKEA
 stab_site MOB1
 stab_site MONP
 stab_site NANO
 stab_site NEWP
 stab_site NKLG
 stab_site NLIB
 stab_site NOT1
 stab_site NOUM
 stab_site NPRI
 stab_site NRC1
 stab_site NRIL
 stab_site NYAL
 stab_site ONSA
 stab_site OUSD
 stab_site PDEL
 stab_site PENC
 stab_site PERT
 stab_site PIE1
 stab_site POL2
 stab_site POTS
 stab_site PTBB
 stab_site PUR3
 stab_site RABT
 stab_site RAMO
 stab_site REYZ
 stab_site RIGA
 stab_site RIOG
 stab_site SANT
 stab_site SCH2
 stab_site SEAT
 stab_site SELE
 stab_site SFER
 stab_site SJDV
 stab_site SNI1
 stab_site SOFI
 stab_site SOL1
 stab_site STJO
 stab_site SUWN
 stab_site SYOG
 stab_site THTI
 stab_site TIDB
 stab_site TIXI
 stab_site TOW2
 stab_site TRAB
 stab_site TROM
 stab_site TSKB
 stab_site ULAB
 stab_site UPO1
 stab_site USNA
 stab_site USNO
 stab_site UZHL
 stab_site VAAS
 stab_site VILL
 stab_site VIS0
 stab_site VNDP
 stab_site VTIS
 stab_site WGTN
 stab_site WHIT
 stab_site WILL
 stab_site WROC
 stab_site YELL
x stab_site bjfs bjsh jixn dlha dxin xnin guan kmin kunm luzh tash wush wuhn xiaa xiag xiam yanc zhnz
# Set parameters to estimate in stabilization
  pos_org  xrot yrot zrot xtran ytran ztran scale
x no rotation if regional stabilzation
x  pos_org  xtran ytran ztran
# Set height ratios
 cnd_hgtv 10 10 2.0 2.0
x  downweight heights in stablization
x  cnd_hgtv 1000 1000 2.0 2.0
# Iterations and editing
  stab_ite 6 0.8 4.
-------------------------------------------------------------------------------

 EXPERIMENT LIST from comb.srt
     #  Name                                                                  SCALE Diag PPM  Forw Chi2 Back Chi2 Status
     1 /home/tianyf/gpse/rerun.vsbl/comb/090729/glbf/h0812281200_vsbl.glx     1.000   0.000     0.040    -1.000   USED        

 SUMMARY POSITION ESTIMATES FROM GLOBK Ver 5.16X       
   Long.     Lat.       dE adj.   dN adj.   dE +-     dN +-   RHO        dH adj.   dH +-  SITE
   (deg)    (deg)        (mm)      (mm)      (mm)      (mm)               (mm)      (mm)
  355.750   40.429      -2.02     -3.43      2.97      2.17 -0.061        6.84      8.07 MAD2_2PS 
  355.750   40.429       2.90     -0.84      2.58      1.43 -0.195       -7.20      6.11 MADR_8PS*
  338.045   64.139      -5.08    -10.13      3.79      3.64  0.017       -1.43      9.05 REYK_2PS 
  302.099  -63.321    -224.94     84.13    485.30    381.32  0.379      -23.04    317.30 OHI2_GPS 
  302.099  -63.321    -225.44     83.09    485.30    381.30  0.379      -24.90    317.36 OHI3_GPS 
  291.175   76.537      11.57    -20.32      5.13      5.69 -0.027       22.94      9.67 THU2_GPS 
  291.175   76.537       3.85    -19.92      5.12      5.69 -0.026       10.06      9.82 THU3_GPS 
  284.376   45.454      -6.21     -3.26      6.11      2.50 -0.076       34.82     17.55 NRC1_GPS 
  243.111   35.425      30.48     -4.01     16.90      6.99  0.295       22.75     22.96 GOL2_1HT 
  243.111   35.425      28.52      0.44     16.89      6.97  0.296       14.24     22.95 GOLD_1HT 
  241.090   35.201      35.86     -1.42     17.30      7.31  0.304       19.86     23.08 ARM1_GNR 
  241.089   35.201      30.33     -4.34     17.30      7.30  0.304       17.83     22.98 ARM2_GNR 
  212.501   64.978      32.70      7.50     11.36      7.61 -0.018       21.13     12.15 FAIR_6DN 
  127.374   36.399      -2.13      1.74      1.98      1.78  0.229      -17.87     13.46 DAEJ_GPS*
  120.987   24.798      -8.85     -2.87      4.43      3.05  0.325      -26.57     17.65 TCMS_GPS 
  120.987   24.798      -9.81     -4.95      4.41      3.03  0.325      -23.03     17.50 TNML_GPS 
  115.892   39.609      -0.84      7.95      3.72      3.08 -0.289      -12.27     12.89 BJFS_6EQ 
  104.316   52.219      -6.31     15.76      4.89      4.26 -0.385       -0.77     10.14 IRKJ_GPS 
  104.316   52.219      -9.32     13.90     19.91      8.38 -0.337       18.95     29.69 IRKT_GPS 
  102.797   25.030     -16.83     -9.53      9.39      4.85  0.173      -16.07     17.37 KUNM_1SU 
   91.104   29.657      -4.99      1.72     11.01      5.39 -0.026        6.80     13.92 LHAZ_GPS 
   18.940   69.663     -14.11     -9.26      3.97      4.31  0.116        9.74      9.08 TRO1_3PS 
   18.938   69.663     -15.87    -11.25      3.86      4.14  0.120       25.08      8.12 TROM_GPS 
   16.704   40.649       1.05      0.88      2.93      1.92  0.059        4.83      8.42 MATE_1PS*
   12.879   49.144     154.70    144.39      2.51      2.61  0.224       30.84      7.27 WTZA_GPS 
   12.879   49.144     950.87   1266.72      2.76      2.84  0.217       -3.34      8.07 WTZJ_GPS 
   12.879   49.144      -5.31     -6.20      2.52      2.62  0.230       -8.21      7.32 WTZZ_GPS 
   12.879   49.144      -3.49     -6.27      2.67      2.76  0.218      -10.01      7.89 WTZR_2PS 
    8.973   39.136      -1.33      1.34      2.43      1.92  0.046       16.99      8.71 CAGZ_GPS 
    8.973   39.136       2.01     -1.46      2.41      1.94 -0.007        8.75      8.95 CAGL_2PS 
    7.465   46.877       0.02     -2.48      1.97      2.19  0.098       -6.64      7.07 ZIMM_1PS 
POS STATISTICS: For    3 RefSites WRMS ENU   2.21   1.18   8.66  mm    NRMS ENU   0.92   0.71   1.08 L0812281200_vsbl.glx

 PARAMETER ESTIMATES FROM GLOBK Vers 5.16X       
  #      PARAMETER                            Estimate       Adjustment     Sigma
Int. MAD2_2PS  4849202.33860  -360328.88600  4114913.25460    0.00000    0.00000    0.00000 2009.269
   1. MAD2_2PS X coordinate  (m)           4849202.34587      0.00727      0.00674
   2. MAD2_2PS Y coordinate  (m)           -360328.88857     -0.00257      0.00285
   3. MAD2_2PS Z coordinate  (m)           4114913.25640      0.00180      0.00501
Unc. MAD2_2PS  4849202.34587  -360328.88857  4114913.25640    0.00000    0.00000    0.00000 2008.990  0.0067  0.0028  0.0050
Apr. MAD2_2PS  4849202.34587  -360328.88857  4114913.25640    0.00000    0.00000    0.00000 2008.990  0.0067  0.0028  0.0050  -1.0000 -1.0000 -1.0000
Loc.  MAD2_2PS N coordinate  (m)           4500553.78826     -0.00343      0.00217
Loc.  MAD2_2PS E coordinate  (m)          30144706.99363     -0.00202      0.00297
Loc.  MAD2_2PS U coordinate  (m)               829.45882      0.00684      0.00807
     NE,NU,EU position correlations         -0.0609      -0.2806       0.3237

Int. MADR_8PS  4849202.41200  -360329.06100  4114913.13200   -0.00670    0.01880    0.01450 2000.000
   4. MADR_8PS X coordinate  (m)           4849202.34703     -0.00472      0.00520
   5. MADR_8PS Y coordinate  (m)           -360328.88869      0.00326      0.00241
   6. MADR_8PS Z coordinate  (m)           4114913.25710     -0.00529      0.00364
Unc. MADR_8PS  4849202.34703  -360328.88869  4114913.25710   -0.00670    0.01880    0.01450 2008.990  0.0052  0.0024  0.0036
Apr. MADR_8PS  4849202.34703  -360328.88869  4114913.25710   -0.00670    0.01880    0.01450 2008.990  0.0052  0.0024  0.0036  -1.0000 -1.0000 -1.0000
Loc.  MADR_8PS N coordinate  (m)           4500553.78804     -0.00084      0.00143
Loc.  MADR_8PS E coordinate  (m)          30144706.99360      0.00290      0.00258
Loc.  MADR_8PS U coordinate  (m)               829.46016     -0.00720      0.00611
     NE,NU,EU position correlations         -0.1953      -0.4117       0.5085

Int. REYK_2PS  2587384.41500 -1043033.50900  5716564.00300   -0.02160   -0.00280    0.00590 2000.000
   7. REYK_2PS X coordinate  (m)           2587384.22673      0.00596      0.00512
   8. REYK_2PS Y coordinate  (m)          -1043033.54206     -0.00788      0.00423
   9. REYK_2PS Z coordinate  (m)           5716564.05033     -0.00573      0.00809
Unc. REYK_2PS  2587384.22673 -1043033.54206  5716564.05033   -0.02160   -0.00280    0.00590 2008.990  0.0051  0.0042  0.0081
Apr. REYK_2PS  2587384.22673 -1043033.54206  5716564.05033   -0.02160   -0.00280    0.00590 2008.990  0.0051  0.0042  0.0081  -1.0000 -1.0000 -1.0000
Loc.  REYK_2PS N coordinate  (m)           7139896.86144     -0.01013      0.00364
Loc.  REYK_2PS E coordinate  (m)          16413892.63480     -0.00508      0.00379
Loc.  REYK_2PS U coordinate  (m)                93.01613     -0.00143      0.00905
     NE,NU,EU position correlations          0.0166      -0.1264      -0.1228

Int. OHI2_GPS  1525811.77500 -2432478.20900 -5676165.58600    0.01930   -0.00260   -0.00040 2000.000
  10. OHI2_GPS X coordinate  (m)           1525811.79236     -0.15619      0.55693
  11. OHI2_GPS Y coordinate  (m)          -2432478.40669     -0.17431      0.38155
  12. OHI2_GPS Z coordinate  (m)          -5676165.53106      0.05854      0.16074
Unc. OHI2_GPS  1525811.79236 -2432478.40669 -5676165.53106    0.01930   -0.00260   -0.00040 2008.990  0.5569  0.3816  0.1607
Apr. OHI2_GPS  1525811.79236 -2432478.40669 -5676165.53106    0.01930   -0.00260   -0.00040 2008.990  0.5569  0.3816  0.1607  -1.0000 -1.0000 -1.0000
Loc.  OHI2_GPS N coordinate  (m)          -7048870.38362      0.08413      0.38132
Loc.  OHI2_GPS E coordinate  (m)          15099535.14680     -0.22494      0.48530
Loc.  OHI2_GPS U coordinate  (m)                32.46466     -0.02304      0.31730
     NE,NU,EU position correlations          0.3791       0.8613       0.3615

Int. OHI3_GPS  1525808.94500 -2432478.72600 -5676166.27200    0.01930   -0.00260   -0.00040 2000.000
  13. OHI3_GPS X coordinate  (m)           1525808.96100     -0.15755      0.55694
  14. OHI3_GPS Y coordinate  (m)          -2432478.92246     -0.17308      0.38156
  15. OHI3_GPS Z coordinate  (m)          -5676166.21587      0.05972      0.16079
Unc. OHI3_GPS  1525808.96100 -2432478.92246 -5676166.21587    0.01930   -0.00260   -0.00040 2008.990  0.5569  0.3816  0.1608
Apr. OHI3_GPS  1525808.96100 -2432478.92246 -5676166.21587    0.01930   -0.00260   -0.00040 2008.990  0.5569  0.3816  0.1608  -1.0000 -1.0000 -1.0000
Loc.  OHI3_GPS N coordinate  (m)          -7048871.64336      0.08309      0.38130
Loc.  OHI3_GPS E coordinate  (m)          15099532.48131     -0.22544      0.48530
Loc.  OHI3_GPS U coordinate  (m)                32.59722     -0.02490      0.31736
     NE,NU,EU position correlations          0.3790       0.8613       0.3615

Int. THU2_GPS   538093.45090 -1389088.06350  6180979.25050    0.00000    0.00000    0.00000 2009.269
  16. THU2_GPS X coordinate  (m)            538093.47077      0.01987      0.00553
  17. THU2_GPS Y coordinate  (m)          -1389088.08276     -0.01926      0.00642
  18. THU2_GPS Z coordinate  (m)           6180979.26804      0.01754      0.00897
Unc. THU2_GPS   538093.47077 -1389088.08276  6180979.26804    0.00000    0.00000    0.00000 2008.990  0.0055  0.0064  0.0090
Apr. THU2_GPS   538093.47077 -1389088.08276  6180979.26804    0.00000    0.00000    0.00000 2008.990  0.0055  0.0064  0.0090  -1.0000 -1.0000 -1.0000
Loc.  THU2_GPS N coordinate  (m)           8520065.16162     -0.02032      0.00569
Loc.  THU2_GPS E coordinate  (m)           7545667.93095      0.01157      0.00513
Loc.  THU2_GPS U coordinate  (m)                36.14492      0.02294      0.00967
     NE,NU,EU position correlations         -0.0274      -0.3857       0.1521

Int. THU3_GPS   538093.65500 -1389088.02200  6180979.20900   -0.02180   -0.00470    0.00610 2000.000
  19. THU3_GPS X coordinate  (m)            538093.47040      0.01144      0.00553
  20. THU3_GPS Y coordinate  (m)          -1389088.08313     -0.01887      0.00643
  21. THU3_GPS Z coordinate  (m)           6180979.26897      0.00512      0.00912
Unc. THU3_GPS   538093.47040 -1389088.08313  6180979.26897   -0.02180   -0.00470    0.00610 2008.990  0.0055  0.0064  0.0091
Apr. THU3_GPS   538093.47040 -1389088.08313  6180979.26897   -0.02180   -0.00470    0.00610 2008.990  0.0055  0.0064  0.0091  -1.0000 -1.0000 -1.0000
Loc.  THU3_GPS N coordinate  (m)           8520065.16162     -0.01992      0.00569
Loc.  THU3_GPS E coordinate  (m)           7545667.93047      0.00385      0.00512
Loc.  THU3_GPS U coordinate  (m)                36.14587      0.01006      0.00982
     NE,NU,EU position correlations         -0.0263      -0.3831       0.1566

Int. NRC1_GPS  1112777.27400 -4341475.83700  4522955.79000   -0.01560   -0.00310    0.00460 2000.000
  22. NRC1_GPS X coordinate  (m)           1112777.13436      0.00064      0.00719
  23. NRC1_GPS Y coordinate  (m)          -4341475.89240     -0.02753      0.01353
  24. NRC1_GPS Z coordinate  (m)           4522955.85380      0.02244      0.01081
Unc. NRC1_GPS  1112777.13436 -4341475.89240  4522955.85380   -0.01560   -0.00310    0.00460 2008.990  0.0072  0.0135  0.0108
Apr. NRC1_GPS  1112777.13436 -4341475.89240  4522955.85380   -0.01560   -0.00310    0.00460 2008.990  0.0072  0.0135  0.0108  -1.0000 -1.0000 -1.0000
Loc.  NRC1_GPS N coordinate  (m)           5059934.23737     -0.00326      0.00250
Loc.  NRC1_GPS E coordinate  (m)          22205982.32886     -0.00621      0.00611
Loc.  NRC1_GPS U coordinate  (m)                82.53959      0.03482      0.01755
     NE,NU,EU position correlations         -0.0759      -0.9505       0.1127

Int. GOL2_1HT -2353614.39360 -4641385.30460  3676976.41770   -0.01660    0.00610   -0.00230 2009.269
  25. GOL2_1HT X coordinate  (m)          -2353614.37127      0.01774      0.01391
  26. GOL2_1HT Y coordinate  (m)          -4641385.33871     -0.03242      0.02157
  27. GOL2_1HT Z coordinate  (m)           3676976.42819      0.00985      0.01423
Unc. GOL2_1HT -2353614.37127 -4641385.33871  3676976.42819   -0.01660    0.00610   -0.00230 2008.990  0.0139  0.0216  0.0142
Apr. GOL2_1HT -2353614.37127 -4641385.33871  3676976.42819   -0.01660    0.00610   -0.00230 2008.990  0.0139  0.0216  0.0142  -1.0000 -1.0000 -1.0000
Loc.  GOL2_1HT N coordinate  (m)           3943510.31165     -0.00401      0.00699
Loc.  GOL2_1HT E coordinate  (m)          22052721.54084      0.03048      0.01690
Loc.  GOL2_1HT U coordinate  (m)               986.68505      0.02275      0.02296
     NE,NU,EU position correlations          0.2953      -0.0377       0.4933

Int. GOLD_1HT -2353614.23800 -4641385.36300  3676976.44300   -0.01710    0.00500   -0.00250 2000.000
  28. GOLD_1HT X coordinate  (m)          -2353614.37148      0.02030      0.01391
  29. GOLD_1HT Y coordinate  (m)          -4641385.34108     -0.02305      0.02157
  30. GOLD_1HT Z coordinate  (m)           3676976.42909      0.00858      0.01422
Unc. GOLD_1HT -2353614.37148 -4641385.34108  3676976.42909   -0.01710    0.00500   -0.00250 2008.990  0.0139  0.0216  0.0142
Apr. GOLD_1HT -2353614.37148 -4641385.34108  3676976.42909   -0.01710    0.00500   -0.00250 2008.990  0.0139  0.0216  0.0142  -1.0000 -1.0000 -1.0000
Loc.  GOLD_1HT N coordinate  (m)           3943510.31110      0.00044      0.00697
Loc.  GOLD_1HT E coordinate  (m)          22052721.54174      0.02852      0.01689
Loc.  GOLD_1HT U coordinate  (m)               986.68738      0.01424      0.02295
     NE,NU,EU position correlations          0.2959      -0.0375       0.4938

Int. ARM1_GNR -2522429.80560 -4567409.55210  3656178.12040   -0.01990    0.02250   -0.00860 2009.269
  31. ARM1_GNR X coordinate  (m)          -2522429.77697      0.02313      0.01419
  32. ARM1_GNR Y coordinate  (m)          -4567409.59061     -0.03229      0.02186
  33. ARM1_GNR Z coordinate  (m)           3656178.13301      0.01023      0.01437
Unc. ARM1_GNR -2522429.77697 -4567409.59061  3656178.13301   -0.01990    0.02250   -0.00860 2008.990  0.0142  0.0219  0.0144
Apr. ARM1_GNR -2522429.77697 -4567409.59061  3656178.13301   -0.01990    0.02250   -0.00860 2008.990  0.0142  0.0219  0.0144  -1.0000 -1.0000 -1.0000
Loc.  ARM1_GNR N coordinate  (m)           3918585.41623     -0.00142      0.00731
Loc.  ARM1_GNR E coordinate  (m)          21929883.89757      0.03586      0.01730
Loc.  ARM1_GNR U coordinate  (m)                76.77457      0.01986      0.02308
     NE,NU,EU position correlations          0.3036      -0.0306       0.4897

Int. ARM2_GNR -2522440.29710 -4567403.18860  3656178.82110   -0.01710    0.02220   -0.00760 2009.269
  34. ARM2_GNR X coordinate  (m)          -2522440.27409      0.01829      0.01416
  35. ARM2_GNR Y coordinate  (m)          -4567403.22436     -0.02962      0.02180
  36. ARM2_GNR Z coordinate  (m)           3656178.82988      0.00668      0.01432
Unc. ARM2_GNR -2522440.27409 -4567403.22436  3656178.82988   -0.01710    0.02220   -0.00760 2008.990  0.0142  0.0218  0.0143
Apr. ARM2_GNR -2522440.27409 -4567403.22436  3656178.82988   -0.01710    0.02220   -0.00760 2008.990  0.0142  0.0218  0.0143  -1.0000 -1.0000 -1.0000
Loc.  ARM2_GNR N coordinate  (m)           3918586.27568     -0.00434      0.00730
Loc.  ARM2_GNR E coordinate  (m)          21929871.64488      0.03033      0.01730
Loc.  ARM2_GNR U coordinate  (m)                76.76926      0.01783      0.02298
     NE,NU,EU position correlations          0.3044      -0.0299       0.4918

Int. FAIR_6DN -2281621.73250 -1453595.90620  5756961.73940   -0.01980    0.00180   -0.04740 2009.269
  37. FAIR_6DN X coordinate  (m)          -2281621.71131      0.01571      0.00828
  38. FAIR_6DN Y coordinate  (m)          -1453595.93546     -0.02876      0.01161
  39. FAIR_6DN Z coordinate  (m)           5756961.77481      0.02231      0.01145
Unc. FAIR_6DN -2281621.71131 -1453595.93546  5756961.77481   -0.01980    0.00180   -0.04740 2008.990  0.0083  0.0116  0.0115
Apr. FAIR_6DN -2281621.71131 -1453595.93546  5756961.77481   -0.01980    0.00180   -0.04740 2008.990  0.0083  0.0116  0.0115  -1.0000 -1.0000 -1.0000
Loc.  FAIR_6DN N coordinate  (m)           7233317.66794      0.00750      0.00761
Loc.  FAIR_6DN E coordinate  (m)          10005118.57429      0.03270      0.01136
Loc.  FAIR_6DN U coordinate  (m)               318.99881      0.02113      0.01215
     NE,NU,EU position correlations         -0.0178      -0.0034       0.3820

Int. DAEJ_GPS -3120041.84500  4084614.92200  3764026.95400   -0.02600   -0.00940   -0.00920 2000.000
  40. DAEJ_GPS X coordinate  (m)          -3120042.06774      0.01107      0.00707
  41. DAEJ_GPS Y coordinate  (m)           4084614.82649     -0.01098      0.00977
  42. DAEJ_GPS Z coordinate  (m)           3764026.86211     -0.00916      0.00653
Unc. DAEJ_GPS -3120042.06774  4084614.82649  3764026.86211   -0.02600   -0.00940   -0.00920 2008.990  0.0071  0.0098  0.0065
Apr. DAEJ_GPS -3120042.06774  4084614.82649  3764026.86211   -0.02600   -0.00940   -0.00920 2008.990  0.0071  0.0098  0.0065  -1.0000 -1.0000 -1.0000
Loc.  DAEJ_GPS N coordinate  (m)           4051965.82312      0.00174      0.00178
Loc.  DAEJ_GPS E coordinate  (m)          11412829.89996     -0.00213      0.00198
Loc.  DAEJ_GPS U coordinate  (m)               116.81658     -0.01787      0.01346
     NE,NU,EU position correlations          0.2286      -0.9883      -0.2021

Int. TCMS_GPS -2982782.80900  4966660.15800  2658809.49200   -0.02730   -0.01120   -0.00920 2000.000
  43. TCMS_GPS X coordinate  (m)          -2982783.03509      0.01940      0.01018
  44. TCMS_GPS Y coordinate  (m)           4966660.04216     -0.01512      0.01282
  45. TCMS_GPS Z coordinate  (m)           2658809.39558     -0.01369      0.00850
Unc. TCMS_GPS -2982783.03509  4966660.04216  2658809.39558   -0.02730   -0.01120   -0.00920 2008.990  0.0102  0.0128  0.0085
Apr. TCMS_GPS -2982783.03509  4966660.04216  2658809.39558   -0.02730   -0.01120   -0.00920 2008.990  0.0102  0.0128  0.0085  -1.0000 -1.0000 -1.0000
Loc.  TCMS_GPS N coordinate  (m)           2760499.12648     -0.00287      0.00305
Loc.  TCMS_GPS E coordinate  (m)          12226434.42594     -0.00885      0.00443
Loc.  TCMS_GPS U coordinate  (m)                77.22775     -0.02657      0.01765
     NE,NU,EU position correlations          0.3247       0.2557       0.3994

Int. TNML_GPS -2982778.98900  4966662.68600  2658805.75900   -0.02730   -0.01120   -0.00920 2000.000
  46. TNML_GPS X coordinate  (m)          -2982779.21638      0.01812      0.01013
  47. TNML_GPS Y coordinate  (m)           4966662.57416     -0.01112      0.01269
  48. TNML_GPS Z coordinate  (m)           2658805.66216     -0.01411      0.00845
Unc. TNML_GPS -2982779.21638  4966662.57416  2658805.66216   -0.02730   -0.01120   -0.00920 2008.990  0.0101  0.0127  0.0084
Apr. TNML_GPS -2982779.21638  4966662.57416  2658805.66216   -0.02730   -0.01120   -0.00920 2008.990  0.0101  0.0127  0.0084  -1.0000 -1.0000 -1.0000
Loc.  TNML_GPS N coordinate  (m)           2760495.63431     -0.00495      0.00303
Loc.  TNML_GPS E coordinate  (m)          12226429.85136     -0.00981      0.00441
Loc.  TNML_GPS U coordinate  (m)                75.84759     -0.02303      0.01750
     NE,NU,EU position correlations          0.3254       0.2609       0.4051

Int. BJFS_6EQ -2148743.91900  4426641.28300  4044655.93600   -0.03180   -0.00330   -0.00530 2000.000
  49. BJFS_6EQ X coordinate  (m)          -2148744.19786      0.00710      0.00726
  50. BJFS_6EQ Y coordinate  (m)           4426641.24062     -0.01271      0.00936
  51. BJFS_6EQ Z coordinate  (m)           4044655.88669     -0.00165      0.00702
Unc. BJFS_6EQ -2148744.19786  4426641.24062  4044655.88669   -0.03180   -0.00330   -0.00530 2008.990  0.0073  0.0094  0.0070
Apr. BJFS_6EQ -2148744.19786  4426641.24062  4044655.88669   -0.03180   -0.00330   -0.00530 2008.990  0.0073  0.0094  0.0070  -1.0000 -1.0000 -1.0000
Loc.  BJFS_6EQ N coordinate  (m)           4409209.28745      0.00795      0.00308
Loc.  BJFS_6EQ E coordinate  (m)           9939262.43057     -0.00084      0.00372
Loc.  BJFS_6EQ U coordinate  (m)                87.44538     -0.01227      0.01289
     NE,NU,EU position correlations         -0.2894      -0.6015       0.5391

Int. IRKJ_GPS  -968328.45500  3794426.52400  5018167.26700   -0.02530   -0.00020   -0.00370 2000.000
  52. IRKJ_GPS X coordinate  (m)           -968328.67321      0.00930      0.00597
  53. IRKJ_GPS Y coordinate  (m)           3794426.51127     -0.01094      0.00769
  54. IRKJ_GPS Z coordinate  (m)           5018167.24282      0.00909      0.00707
Unc. IRKJ_GPS  -968328.67321  3794426.51127  5018167.24282   -0.02530   -0.00020   -0.00370 2008.990  0.0060  0.0077  0.0071
Apr. IRKJ_GPS  -968328.67321  3794426.51127  5018167.24282   -0.02530   -0.00020   -0.00370 2008.990  0.0060  0.0077  0.0071  -1.0000 -1.0000 -1.0000
Loc.  IRKJ_GPS N coordinate  (m)           5812994.76979      0.01576      0.00426
Loc.  IRKJ_GPS E coordinate  (m)           7114267.60343     -0.00631      0.00489
Loc.  IRKJ_GPS U coordinate  (m)               502.04266     -0.00077      0.01014
     NE,NU,EU position correlations         -0.3849      -0.4944       0.3989

Int. IRKT_GPS  -968332.26600  3794425.41100  5018167.74500   -0.02530   -0.00020   -0.00370 2000.000
  55. IRKT_GPS X coordinate  (m)           -968332.48465      0.00886      0.01914
  56. IRKT_GPS Y coordinate  (m)           3794425.41218      0.00298      0.02124
  57. IRKT_GPS Z coordinate  (m)           5018167.73522      0.02349      0.02303
Unc. IRKT_GPS  -968332.48465  3794425.41218  5018167.73522   -0.02530   -0.00020   -0.00370 2008.990  0.0191  0.0212  0.0230
Apr. IRKT_GPS  -968332.48465  3794425.41218  5018167.73522   -0.02530   -0.00020   -0.00370 2008.990  0.0191  0.0212  0.0230  -1.0000 -1.0000 -1.0000
Loc.  IRKT_GPS N coordinate  (m)           5812995.16840      0.01390      0.00838
Loc.  IRKT_GPS E coordinate  (m)           7114271.55966     -0.00932      0.01991
Loc.  IRKT_GPS U coordinate  (m)               502.35679      0.01895      0.02969
     NE,NU,EU position correlations         -0.3373      -0.1819      -0.3027

Int. KUNM_1SU -1281255.56100  5640746.05900  2682880.04800   -0.03170    0.00350   -0.01470 2000.000
  58. KUNM_1SU X coordinate  (m)          -1281255.82731      0.01875      0.01135
  59. KUNM_1SU Y coordinate  (m)           5640746.08390     -0.00658      0.01441
  60. KUNM_1SU Z coordinate  (m)           2682879.90040     -0.01541      0.00878
Unc. KUNM_1SU -1281255.82731  5640746.08390  2682879.90040   -0.03170    0.00350   -0.01470 2008.990  0.0113  0.0144  0.0088
Apr. KUNM_1SU -1281255.82731  5640746.08390  2682879.90040   -0.03170    0.00350   -0.01470 2008.990  0.0113  0.0144  0.0088  -1.0000 -1.0000 -1.0000
Loc.  KUNM_1SU N coordinate  (m)           2786275.43251     -0.00953      0.00485
Loc.  KUNM_1SU E coordinate  (m)          10368693.29385     -0.01683      0.00939
Loc.  KUNM_1SU U coordinate  (m)              1986.20330     -0.01607      0.01737
     NE,NU,EU position correlations          0.1733       0.0659       0.5348

Int. LHAZ_GPS  -106941.21000  5549269.92300  3139214.93600   -0.04550   -0.00820    0.01320 2000.000
  61. LHAZ_GPS X coordinate  (m)           -106941.61427      0.00489      0.01112
  62. LHAZ_GPS Y coordinate  (m)           5549269.85443      0.00517      0.01257
  63. LHAZ_GPS Z coordinate  (m)           3139215.05955      0.00485      0.00789
Unc. LHAZ_GPS  -106941.61427  5549269.85443  3139215.05955   -0.04550   -0.00820    0.01320 2008.990  0.0111  0.0126  0.0079
Apr. LHAZ_GPS  -106941.61427  5549269.85443  3139215.05955   -0.04550   -0.00820    0.01320 2008.990  0.0111  0.0126  0.0079  -1.0000 -1.0000 -1.0000
Loc.  LHAZ_GPS N coordinate  (m)           3301439.15510      0.00172      0.00539
Loc.  LHAZ_GPS E coordinate  (m)           8813208.90261     -0.00499      0.01101
Loc.  LHAZ_GPS U coordinate  (m)              3624.60483      0.00680      0.01392
     NE,NU,EU position correlations         -0.0259      -0.1054       0.4803

Int. TRO1_3PS  2102928.57200   721619.40900  5958196.22700   -0.01760    0.00920    0.00760 2000.000
  64. TRO1_3PS X coordinate  (m)           2102928.42974      0.01601      0.00527
  65. TRO1_3PS Y coordinate  (m)            721619.48230     -0.00943      0.00394
  66. TRO1_3PS Z coordinate  (m)           5958196.30123      0.00588      0.00858
Unc. TRO1_3PS  2102928.42974   721619.48230  5958196.30123   -0.01760    0.00920    0.00760 2008.990  0.0053  0.0039  0.0086
Apr. TRO1_3PS  2102928.42974   721619.48230  5958196.30123   -0.01760    0.00920    0.00760 2008.990  0.0053  0.0039  0.0086  -1.0000 -1.0000 -1.0000
Loc.  TRO1_3PS N coordinate  (m)           7754818.36373     -0.00926      0.00431
Loc.  TRO1_3PS E coordinate  (m)            732743.97166     -0.01411      0.00397
Loc.  TRO1_3PS U coordinate  (m)               138.11516      0.00974      0.00908
     NE,NU,EU position correlations          0.1162      -0.0437      -0.0464

Int. TROM_GPS  2102940.28400   721569.41300  5958192.13300   -0.01760    0.00900    0.00760 2000.000
  67. TROM_GPS X coordinate  (m)           2102940.14914      0.02341      0.00502
  68. TROM_GPS Y coordinate  (m)            721569.48518     -0.00875      0.00380
  69. TROM_GPS Z coordinate  (m)           5958192.22091      0.01957      0.00763
Unc. TROM_GPS  2102940.14914   721569.48518  5958192.22091   -0.01760    0.00900    0.00760 2008.990  0.0050  0.0038  0.0076
Apr. TROM_GPS  2102940.14914   721569.48518  5958192.22091   -0.01760    0.00900    0.00760 2008.990  0.0050  0.0038  0.0076  -1.0000 -1.0000 -1.0000
Loc.  TROM_GPS N coordinate  (m)           7754821.75990     -0.01125      0.00414
Loc.  TROM_GPS E coordinate  (m)            732693.02946     -0.01587      0.00386
Loc.  TROM_GPS U coordinate  (m)               132.50206      0.02508      0.00812
     NE,NU,EU position correlations          0.1202      -0.0763      -0.0564

Int. MATE_1PS  4641949.64700  1393045.33400  4133287.38500   -0.01790    0.01880    0.01550 2000.000
  70. MATE_1PS X coordinate  (m)           4641949.48871      0.00267      0.00720
  71. MATE_1PS Y coordinate  (m)           1393045.50496      0.00190      0.00279
  72. MATE_1PS Z coordinate  (m)           4133287.52818      0.00380      0.00486
Unc. MATE_1PS  4641949.48871  1393045.50496  4133287.52818   -0.01790    0.01880    0.01550 2008.990  0.0072  0.0028  0.0049
Apr. MATE_1PS  4641949.48871  1393045.50496  4133287.52818   -0.01790    0.01880    0.01550 2008.990  0.0072  0.0028  0.0049  -1.0000 -1.0000 -1.0000
Loc.  MATE_1PS N coordinate  (m)           4525040.71568      0.00088      0.00192
Loc.  MATE_1PS E coordinate  (m)           1410869.10135      0.00105      0.00293
Loc.  MATE_1PS U coordinate  (m)               535.66008      0.00483      0.00842
     NE,NU,EU position correlations          0.0590      -0.5270      -0.4065

Int. WTZA_GPS  4075578.43030   931852.73570  4801569.95180    0.00000    0.00000    0.00000 2001.005
  73. WTZA_GPS X coordinate  (m)           4075578.30940     -0.12090      0.00588
  74. WTZA_GPS Y coordinate  (m)            931852.86675      0.13105      0.00246
  75. WTZA_GPS Z coordinate  (m)           4801570.06987      0.11807      0.00504
Unc. WTZA_GPS  4075578.30940   931852.86675  4801570.06987    0.00000    0.00000    0.00000 2008.990  0.0059  0.0025  0.0050
Apr. WTZA_GPS  4075578.30940   931852.86675  4801570.06987    0.00000    0.00000    0.00000 2008.990  0.0059  0.0025  0.0050  -1.0000 -1.0000 -1.0000
Loc.  WTZA_GPS N coordinate  (m)           5470710.22696      0.14439      0.00261
Loc.  WTZA_GPS E coordinate  (m)            937828.25360      0.15470      0.00251
Loc.  WTZA_GPS U coordinate  (m)               665.92430      0.03084      0.00727
     NE,NU,EU position correlations          0.2243      -0.4047      -0.2260

Int. WTZJ_GPS  4075580.98410   931854.72330  4801567.47440    0.00000    0.00000    0.00000 2002.987
  76. WTZJ_GPS X coordinate  (m)           4075579.83871     -1.14539      0.00639
  77. WTZJ_GPS Y coordinate  (m)            931855.43682      0.71352      0.00274
  78. WTZJ_GPS Z coordinate  (m)           4801568.30369      0.82929      0.00569
Unc. WTZJ_GPS  4075579.83871   931855.43682  4801568.30369    0.00000    0.00000    0.00000 2008.990  0.0064  0.0027  0.0057
Apr. WTZJ_GPS  4075579.83871   931855.43682  4801568.30369    0.00000    0.00000    0.00000 2008.990  0.0064  0.0027  0.0057  -1.0000 -1.0000 -1.0000
Loc.  WTZJ_GPS N coordinate  (m)           5470707.50840      1.26672      0.00284
Loc.  WTZJ_GPS E coordinate  (m)            937830.41373      0.95087      0.00276
Loc.  WTZJ_GPS U coordinate  (m)               665.93841     -0.00334      0.00807
     NE,NU,EU position correlations          0.2170      -0.3568      -0.1849

Int. WTZZ_GPS  4075579.50600   931853.02600  4801568.98100   -0.01510    0.01730    0.01140 2000.000
  79. WTZZ_GPS X coordinate  (m)           4075579.37070      0.00049      0.00592
  80. WTZZ_GPS Y coordinate  (m)            931853.17624     -0.00533      0.00246
  81. WTZZ_GPS Z coordinate  (m)           4801569.07325     -0.01026      0.00507
Unc. WTZZ_GPS  4075579.37070   931853.17624  4801569.07325   -0.01510    0.01730    0.01140 2008.990  0.0059  0.0025  0.0051
Apr. WTZZ_GPS  4075579.37070   931853.17624  4801569.07325   -0.01510    0.01730    0.01140 2008.990  0.0059  0.0025  0.0051  -1.0000 -1.0000 -1.0000
Loc.  WTZZ_GPS N coordinate  (m)           5470708.73904     -0.00620      0.00262
Loc.  WTZZ_GPS E coordinate  (m)            937828.31861     -0.00531      0.00252
Loc.  WTZZ_GPS U coordinate  (m)               665.89241     -0.00821      0.00732
     NE,NU,EU position correlations          0.2295      -0.4091      -0.2236

Int. WTZR_2PS  4075580.63300   931853.71200  4801568.08100   -0.01510    0.01730    0.01140 2000.000
  82. WTZR_2PS X coordinate  (m)           4075580.49619     -0.00102      0.00626
  83. WTZR_2PS Y coordinate  (m)            931853.86376     -0.00381      0.00265
  84. WTZR_2PS Z coordinate  (m)           4801568.17185     -0.01166      0.00554
Unc. WTZR_2PS  4075580.49619   931853.86376  4801568.17185   -0.01510    0.01730    0.01140 2008.990  0.0063  0.0027  0.0055
Apr. WTZR_2PS  4075580.49619   931853.86376  4801568.17185   -0.01510    0.01730    0.01140 2008.990  0.0063  0.0027  0.0055  -1.0000 -1.0000 -1.0000
Loc.  WTZR_2PS N coordinate  (m)           5470707.20230     -0.00627      0.00276
Loc.  WTZR_2PS E coordinate  (m)            937828.73712     -0.00349      0.00267
Loc.  WTZR_2PS U coordinate  (m)               666.02860     -0.01001      0.00789
     NE,NU,EU position correlations          0.2179      -0.3693      -0.1898

Int. CAGZ_GPS  4893380.03700   772650.38000  4004179.95800   -0.01320    0.01970    0.01270 2000.000
  85. CAGZ_GPS X coordinate  (m)           4893379.93073      0.01243      0.00730
  86. CAGZ_GPS Y coordinate  (m)            772650.55777      0.00062      0.00262
  87. CAGZ_GPS Z coordinate  (m)           4004180.08392      0.01172      0.00503
Unc. CAGZ_GPS  4893379.93073   772650.55777  4004180.08392   -0.01320    0.01970    0.01270 2008.990  0.0073  0.0026  0.0050
Apr. CAGZ_GPS  4893379.93073   772650.55777  4004180.08392   -0.01320    0.01970    0.01270 2008.990  0.0073  0.0026  0.0050  -1.0000 -1.0000 -1.0000
Loc.  CAGZ_GPS N coordinate  (m)           4356587.39834      0.00134      0.00192
Loc.  CAGZ_GPS E coordinate  (m)            774756.17728     -0.00133      0.00243
Loc.  CAGZ_GPS U coordinate  (m)               237.99356      0.01699      0.00871
     NE,NU,EU position correlations          0.0459      -0.4238      -0.0296

Int. CAGL_2PS  4893378.89000   772649.68800  4004182.09900   -0.01320    0.01970    0.01270 2000.000
  88. CAGL_2PS X coordinate  (m)           4893378.77862      0.00732      0.00747
  89. CAGL_2PS Y coordinate  (m)            772649.86834      0.00319      0.00263
  90. CAGL_2PS Z coordinate  (m)           4004182.21757      0.00436      0.00520
Unc. CAGL_2PS  4893378.77862   772649.86834  4004182.21757   -0.01320    0.01970    0.01270 2008.990  0.0075  0.0026  0.0052
Apr. CAGL_2PS  4893378.77862   772649.86834  4004182.21757   -0.01320    0.01970    0.01270 2008.990  0.0075  0.0026  0.0052  -1.0000 -1.0000 -1.0000
Loc.  CAGL_2PS N coordinate  (m)           4356589.84598     -0.00146      0.00194
Loc.  CAGL_2PS E coordinate  (m)            774755.67666      0.00201      0.00241
Loc.  CAGL_2PS U coordinate  (m)               238.37413      0.00875      0.00895
     NE,NU,EU position correlations         -0.0071      -0.4080      -0.0271

Int. ZIMM_1PS  4331297.13100   567555.78900  4633133.87200   -0.01260    0.01810    0.01270 2000.000
  91. ZIMM_1PS X coordinate  (m)           4331297.01497     -0.00273      0.00572
  92. ZIMM_1PS Y coordinate  (m)            567555.95143     -0.00034      0.00204
  93. ZIMM_1PS Z coordinate  (m)           4633133.97967     -0.00653      0.00466
Unc. ZIMM_1PS  4331297.01497   567555.95143  4633133.97967   -0.01260    0.01810    0.01270 2008.990  0.0057  0.0020  0.0047
Apr. ZIMM_1PS  4331297.01497   567555.95143  4633133.97967   -0.01260    0.01810    0.01270 2008.990  0.0057  0.0020  0.0047  -1.0000 -1.0000 -1.0000
Loc.  ZIMM_1PS N coordinate  (m)           5218334.68537     -0.00248      0.00219
Loc.  ZIMM_1PS E coordinate  (m)            568072.24781      0.00002      0.00197
Loc.  ZIMM_1PS U coordinate  (m)               956.33820     -0.00664      0.00707
     NE,NU,EU position correlations          0.0984      -0.4524      -0.0533

  94. TRANSLTN X coordinate  (m)                             -0.00007      0.00494
  95. TRANSLTN Y coordinate  (m)                             -0.00105      0.00494
  96. TRANSLTN Z coordinate  (m)                             -0.00019      0.00499
  97. SCALE    (ppb)                                         -0.45677      0.89951
  98. SCALRATE (ppb/yr)                                       0.00000      1.00000

Eph. #IC  8 363 12  0  0                    GPST J2000 IAU76 BERNE
  99. PRN_01   Inert.  X     (m)          25546638.75002     -0.64298      1.80403
 100. PRN_01   Inert.  Y     (m)          -6610479.82823     -0.88123      4.62547
 101. PRN_01   Inert.  Z     (m)          -2887347.04306     -0.17806      4.74703
 102. PRN_01   Inert.  dX/dT (mm/s)         215942.47662      0.03962      0.85061
 103. PRN_01   Inert.  dY/dT (mm/s)        2334605.00643      0.05643      0.19428
 104. PRN_01   Inert.  dZ/dT (mm/s)       -3086826.80002      0.00898      0.17422
 105. PRN_01   Direct Rad    (none)              1.01714      0.01714      0.54231
 106. PRN_01   Y Axis Bias   (none)             -0.00182     -0.00182      0.26837
 107. PRN_01   B Axis Bias   (none)             -0.00005     -0.00005      0.01998
 108. PRN_01   Sin Direct    (none)              0.00755      0.00755      0.49687
 109. PRN_01   Cos Y Bias    (none)             -0.00001     -0.00001      0.01998
 110. PRN_01   Cos B Bias    (none)              0.02957      0.02957      0.42149
 111. PRN_01   AntOffest X   (m)                 0.22480     -0.05420      1.63373
Eph.  2008 12 28 11 PRN_01    25546638.7500  -6610479.8282  -2887347.0431   215942.47662  2334605.00643 -3086826.80002   1.01714  -0.00182   0.00000  -0.00005   0.00000   0.00000   0.00755  -0.00001   0.00000   0.02957   0.00000   0.00000   0.00000   0.00000   0.22480   0.00000   0.95190
 Loc. PRN_01   Semimajor axis      (m)     26562868.2632      -0.3624       1.3072
 Loc. PRN_01   Eccentricity (none & m)      0.0097743115       0.2691       1.8157
 Loc. PRN_01   Inclination  (degs & m)     53.5929614642      -0.2615       2.7359
 Loc. PRN_01   RA Node      (degs & m)    160.8639886984      -1.2306       5.0265
 Loc. PRN_01   Arg. Perigee (degs & m)    274.5004296239       0.5827      19.0510
 Loc. PRN_01   M + w        (degs & m)    188.8848995268       0.8388       6.8481

 112. PRN_02   Inert.  X     (m)           5401750.93716      1.75116      3.34779
 113. PRN_02   Inert.  Y     (m)          20872148.42205     -0.50695      0.93466
 114. PRN_02   Inert.  Z     (m)         -15380509.84546     -0.02146      0.32509
 115. PRN_02   Inert.  dX/dT (mm/s)       -3103831.96689      0.00511      0.13279
 116. PRN_02   Inert.  dY/dT (mm/s)        -778822.25977      0.18223      0.48687
 117. PRN_02   Inert.  dZ/dT (mm/s)       -2203061.80499     -0.07399      0.07654
 118. PRN_02   Direct Rad    (none)              0.94086     -0.05914      0.09313
 119. PRN_02   Y Axis Bias   (none)             -0.00119     -0.00119      0.00371
 120. PRN_02   B Axis Bias   (none)              0.00211      0.00211      0.01959
 121. PRN_02   Sin Direct    (none)             -0.00364     -0.00364      0.00843
 122. PRN_02   Cos Y Bias    (none)              0.00345      0.00345      0.01654
 123. PRN_02   Cos B Bias    (none)              0.03460      0.03460      0.06926
 124. PRN_02   AntOffest X   (m)                -0.38653     -0.38653      0.53555
Eph.  2008 12 28 11 PRN_02     5401750.9372  20872148.4220 -15380509.8455 -3103831.96689  -778822.25977 -2203061.80499   0.94086  -0.00119   0.00000   0.00211   0.00000   0.00000  -0.00364   0.00345   0.00000   0.03460   0.00000   0.00000   0.00000   0.00000  -0.38653   0.00000   0.61400
 Loc. PRN_02   Semimajor axis      (m)     26559611.7208      -0.0417       0.1805
 Loc. PRN_02   Eccentricity (none & m)      0.0088556770      -0.0095       0.1026
 Loc. PRN_02   Inclination  (degs & m)     53.9305380383       0.6427       0.6297
 Loc. PRN_02   RA Node      (degs & m)    224.1827186363      -1.4852       4.1709
 Loc. PRN_02   Arg. Perigee (degs & m)    154.2817276781      -1.4346      18.1489
 Loc. PRN_02   M + w        (degs & m)    224.9683877441      -0.4022       0.6405

 125. PRN_03   Inert.  X     (m)           -130571.85433     -1.25733      2.72850
 126. PRN_03   Inert.  Y     (m)         -16543337.58201     -0.03901      0.50825
 127. PRN_03   Inert.  Z     (m)          20535024.27204     -0.02896      0.30536
 128. PRN_03   Inert.  dX/dT (mm/s)        3729896.03828     -0.04672      0.14505
 129. PRN_03   Inert.  dY/dT (mm/s)        -924518.86962     -0.19562      0.58513
 130. PRN_03   Inert.  dZ/dT (mm/s)        -675627.80316      0.05284      0.12239
 131. PRN_03   Direct Rad    (none)              1.04041      0.04041      0.11880
 132. PRN_03   Y Axis Bias   (none)             -0.00387     -0.00387      0.00300
 133. PRN_03   B Axis Bias   (none)              0.00057      0.00057      0.01919
 134. PRN_03   Sin Direct    (none)             -0.00196     -0.00196      0.01036
 135. PRN_03   Cos Y Bias    (none)             -0.00127     -0.00127      0.01758
 136. PRN_03   Cos B Bias    (none)              0.09511      0.09511      0.09483
 137. PRN_03   AntOffest X   (m)                 0.34897      0.06997      0.60022
Eph.  2008 12 28 11 PRN_03     -130571.8543 -16543337.5820  20535024.2720  3729896.03828  -924518.86962  -675627.80316   1.04041  -0.00387   0.00000   0.00057   0.00000   0.00000  -0.00196  -0.00127   0.00000   0.09511   0.00000   0.00000   0.00000   0.00000   0.34897   0.00000   2.61900
 Loc. PRN_03   Semimajor axis      (m)     26559515.7858      -0.0865       0.1924
 Loc. PRN_03   Eccentricity (none & m)      0.0115389167      -0.1201       0.1266
 Loc. PRN_03   Inclination  (degs & m)     53.0639903032      -0.2125       0.6073
 Loc. PRN_03   RA Node      (degs & m)    158.4831962923      -1.1705       4.1560
 Loc. PRN_03   Arg. Perigee (degs & m)     50.6660010471      -2.6053      10.5010
 Loc. PRN_03   M + w        (degs & m)    101.9900483518      -0.3347       1.0614

 138. PRN_04   Inert.  X     (m)          -7464871.44424     -0.26024      2.43265
 139. PRN_04   Inert.  Y     (m)          14425037.77151      0.12951      1.41662
 140. PRN_04   Inert.  Z     (m)         -21186871.50877      0.20523      0.36326
 141. PRN_04   Inert.  dX/dT (mm/s)       -2959560.61379     -0.10179      0.37577
 142. PRN_04   Inert.  dY/dT (mm/s)       -2404247.27596      0.08804      0.46723
 143. PRN_04   Inert.  dZ/dT (mm/s)        -560526.92523      0.11377      0.13487
 144. PRN_04   Direct Rad    (none)              1.03807      0.03807      0.15795
 145. PRN_04   Y Axis Bias   (none)             -0.01204     -0.01204      0.00442
 146. PRN_04   B Axis Bias   (none)             -0.00375     -0.00375      0.01844
 147. PRN_04   Sin Direct    (none)              0.00320      0.00320      0.00989
 148. PRN_04   Cos Y Bias    (none)             -0.00451     -0.00451      0.01816
 149. PRN_04   Cos B Bias    (none)             -0.10535     -0.10535      0.11323
 150. PRN_04   AntOffest X   (m)                 0.34001      0.06101      0.84274
Eph.  2008 12 28 11 PRN_04    -7464871.4442  14425037.7715 -21186871.5088 -2959560.61379 -2404247.27596  -560526.92523   1.03807  -0.01204   0.00000  -0.00375   0.00000   0.00000   0.00320  -0.00451   0.00000  -0.10535   0.00000   0.00000   0.00000   0.00000   0.34001   0.00000   2.27900
 Loc. PRN_04   Semimajor axis      (m)     26558639.9961       0.0515       0.1498
 Loc. PRN_04   Eccentricity (none & m)      0.0086510301      -0.0356       0.1703
 Loc. PRN_04   Inclination  (degs & m)     53.8867546586      -0.5626       0.6271
 Loc. PRN_04   RA Node      (degs & m)    225.2459284228      -1.3947       4.1580
 Loc. PRN_04   Arg. Perigee (degs & m)     26.4194406087      -6.3801      12.5330
 Loc. PRN_04   M + w        (degs & m)    260.0243267497       0.9294       1.1040

 151. PRN_05   Inert.  X     (m)          13961690.50436      0.58136      1.39161
 152. PRN_05   Inert.  Y     (m)           8780509.47347     -1.07853      2.19187
 153. PRN_05   Inert.  Z     (m)         -21093063.10407      0.01193      0.11818
 154. PRN_05   Inert.  dX/dT (mm/s)       -1149079.78946      0.18854      0.56042
 155. PRN_05   Inert.  dY/dT (mm/s)        3587963.48754      0.07354      0.18065
 156. PRN_05   Inert.  dZ/dT (mm/s)         755589.87699     -0.04801      0.02979
 157. PRN_05   Direct Rad    (none)              1.01577      0.01577      0.01289
 158. PRN_05   Y Axis Bias   (none)              0.00045      0.00045      0.00623
 159. PRN_05   B Axis Bias   (none)             -0.01307     -0.01307      0.01545
 160. PRN_05   Sin Direct    (none)              0.00094      0.00094      0.01181
 161. PRN_05   Cos Y Bias    (none)             -0.00392     -0.00392      0.01821
 162. PRN_05   Cos B Bias    (none)              0.05461      0.05461      0.07437
 163. PRN_05   AntOffest X   (m)                 0.17503     -0.10397      0.09761
Eph.  2008 12 28 11 PRN_05    13961690.5044   8780509.4735 -21093063.1041 -1149079.78946  3587963.48754   755589.87699   1.01577   0.00045   0.00000  -0.01307   0.00000   0.00000   0.00094  -0.00392   0.00000   0.05461   0.00000   0.00000   0.00000   0.00000   0.17503   0.00000   2.46300
 Loc. PRN_05   Semimajor axis      (m)     26558482.8030      -0.0792       0.1598
 Loc. PRN_05   Eccentricity (none & m)      0.0094030039       0.0477       0.1524
 Loc. PRN_05   Inclination  (degs & m)     54.1998116118      -0.0982       0.2284
 Loc. PRN_05   RA Node      (degs & m)     99.4413489797      -1.1945       4.1452
 Loc. PRN_05   Arg. Perigee (degs & m)     74.5130152946      -5.0648      11.1615
 Loc. PRN_05   M + w        (degs & m)    284.2954157142      -0.3477       0.2633

 164. PRN_06   Inert.  X     (m)           4786665.42764     -1.30036      2.83480
 165. PRN_06   Inert.  Y     (m)         -17055850.72915     -0.06515      0.91878
 166. PRN_06   Inert.  Z     (m)          19980618.18751      0.19751      0.36899
 167. PRN_06   Inert.  dX/dT (mm/s)        3670632.21415      0.00515      0.05888
 168. PRN_06   Inert.  dY/dT (mm/s)        -290066.46339     -0.19739      0.57597
 169. PRN_06   Inert.  dZ/dT (mm/s)       -1135421.92817      0.07483      0.13319
 170. PRN_06   Direct Rad    (none)              1.09175      0.09175      0.12569
 171. PRN_06   Y Axis Bias   (none)             -0.00213     -0.00213      0.00252
 172. PRN_06   B Axis Bias   (none)             -0.00014     -0.00014      0.01964
 173. PRN_06   Sin Direct    (none)             -0.00873     -0.00873      0.01049
 174. PRN_06   Cos Y Bias    (none)              0.00230      0.00230      0.01767
 175. PRN_06   Cos B Bias    (none)              0.04686      0.04686      0.11912
 176. PRN_06   AntOffest X   (m)                 0.60401      0.32501      0.62595
Eph.  2008 12 28 11 PRN_06     4786665.4276 -17055850.7292  19980618.1875  3670632.21415  -290066.46339 -1135421.92817   1.09175  -0.00213   0.00000  -0.00014   0.00000   0.00000  -0.00873   0.00230   0.00000   0.04686   0.00000   0.00000   0.00000   0.00000   0.60401   0.00000   2.67600
 Loc. PRN_06   Semimajor axis      (m)     26559689.3039      -0.1176       0.2595
 Loc. PRN_06   Eccentricity (none & m)      0.0056329420       0.0782       0.2312
 Loc. PRN_06   Inclination  (degs & m)     53.4889558245       0.0334       0.6242
 Loc. PRN_06   RA Node      (degs & m)    162.2864410585      -0.9547       4.1660
 Loc. PRN_06   Arg. Perigee (degs & m)    274.5529324508      -0.8847      11.8513
 Loc. PRN_06   M + w        (degs & m)    111.6015415903      -0.6696       1.1781

 177. PRN_07   Inert.  X     (m)         -20694388.14683     -0.22683      0.83216
 178. PRN_07   Inert.  Y     (m)          -5311836.16457      0.71843      3.23574
 179. PRN_07   Inert.  Z     (m)          15691480.26922     -0.06078      0.10922
 180. PRN_07   Inert.  dX/dT (mm/s)        -892881.33872     -0.11772      0.47742
 181. PRN_07   Inert.  dY/dT (mm/s)       -3056162.97041      0.04859      0.13931
 182. PRN_07   Inert.  dZ/dT (mm/s)       -2220065.67571     -0.01071      0.01443
 183. PRN_07   Direct Rad    (none)              0.96182     -0.03818      0.00830
 184. PRN_07   Y Axis Bias   (none)              0.01009      0.01009      0.00454
 185. PRN_07   B Axis Bias   (none)              0.01304      0.01304      0.01281
 186. PRN_07   Sin Direct    (none)             -0.00262     -0.00262      0.01685
 187. PRN_07   Cos Y Bias    (none)             -0.00042     -0.00042      0.01824
 188. PRN_07   Cos B Bias    (none)              0.05780      0.05780      0.04263
 189. PRN_07   AntOffest X   (m)                -0.10831     -0.10831      0.10059
Eph.  2008 12 28 11 PRN_07   -20694388.1468  -5311836.1646  15691480.2692  -892881.33872 -3056162.97041 -2220065.67571   0.96182   0.01009   0.00000   0.01304   0.00000   0.00000  -0.00262  -0.00042   0.00000   0.05780   0.00000   0.00000   0.00000   0.00000  -0.10831   0.00000   0.70000
 Loc. PRN_07   Semimajor axis      (m)     26560178.0886      -0.0752       0.1292
 Loc. PRN_07   Eccentricity (none & m)      0.0022948493      -0.0820       0.1037
 Loc. PRN_07   Inclination  (degs & m)     55.3487150072       0.0671       0.0836
 Loc. PRN_07   RA Node      (degs & m)     44.9017876615      -1.1104       4.1461
 Loc. PRN_07   Arg. Perigee (degs & m)    165.9128870886       2.2114      17.7680
 Loc. PRN_07   M + w        (degs & m)    134.1193764103       0.0733       0.1473

 190. PRN_08   Inert.  X     (m)         -13178338.56239      0.30161      1.08744
 191. PRN_08   Inert.  Y     (m)           6939865.38902      0.45502      2.06579
 192. PRN_08   Inert.  Z     (m)          21883447.10771      0.05171      0.07041
 193. PRN_08   Inert.  dX/dT (mm/s)       -2329994.04541     -0.12241      0.48019
 194. PRN_08   Inert.  dY/dT (mm/s)       -3074607.41379      0.10021      0.36386
 195. PRN_08   Inert.  dZ/dT (mm/s)        -475037.79130     -0.00330      0.01986
 196. PRN_08   Direct Rad    (none)              1.02295      0.02295      0.01023
 197. PRN_08   Y Axis Bias   (none)             -0.00082     -0.00082      0.00543
 198. PRN_08   B Axis Bias   (none)              0.00066      0.00066      0.01620
 199. PRN_08   Sin Direct    (none)              0.01351      0.01351      0.02518
 200. PRN_08   Cos Y Bias    (none)              0.00419      0.00419      0.01810
 201. PRN_08   Cos B Bias    (none)             -0.02200     -0.02200      0.05270
 202. PRN_08   AntOffest X   (m)                 0.31626      0.03726      0.09601
Eph.  2008 12 28 11 PRN_08   -13178338.5624   6939865.3890  21883447.1077 -2329994.04541 -3074607.41379  -475037.79130   1.02295  -0.00082   0.00000   0.00066   0.00000   0.00000   0.01351   0.00419   0.00000  -0.02200   0.00000   0.00000   0.00000   0.00000   0.31626   0.00000   2.40500
 Loc. PRN_08   Semimajor axis      (m)     26558794.8777      -0.0515       0.1652
 Loc. PRN_08   Eccentricity (none & m)      0.0105177570      -0.0466       0.0775
 Loc. PRN_08   Inclination  (degs & m)     56.5651425778       0.0879       0.0967
 Loc. PRN_08   RA Node      (degs & m)     48.1810231944      -1.0911       4.1459
 Loc. PRN_08   Arg. Perigee (degs & m)    170.1112114052       4.8912      11.7884
 Loc. PRN_08   M + w        (degs & m)     98.9944254241      -0.0043       0.1799

 203. PRN_09   Inert.  X     (m)          20337801.88780      0.82180      2.64249
 204. PRN_09   Inert.  Y     (m)          16916089.73674     -0.96926      3.17735
 205. PRN_09   Inert.  Z     (m)          -2136666.10934     -0.04134      0.20752
 206. PRN_09   Inert.  dX/dT (mm/s)       -1257082.73225      0.08875      0.28126
 207. PRN_09   Inert.  dY/dT (mm/s)        1793129.82759      0.06159      0.19755
 208. PRN_09   Inert.  dZ/dT (mm/s)        3199388.39175     -0.01025      0.02172
 209. PRN_09   Direct Rad    (none)              1.02459      0.02459      0.01003
 210. PRN_09   Y Axis Bias   (none)              0.00104      0.00104      0.00663
 211. PRN_09   B Axis Bias   (none)             -0.00371     -0.00371      0.01806
 212. PRN_09   Sin Direct    (none)              0.01004      0.01004      0.02605
 213. PRN_09   Cos Y Bias    (none)             -0.00028     -0.00028      0.01924
 214. PRN_09   Cos B Bias    (none)              0.00727      0.00727      0.05373
 215. PRN_09   AntOffest X   (m)                 0.26711     -0.01189      0.09726
Eph.  2008 12 28 11 PRN_09    20337801.8878  16916089.7367  -2136666.1093 -1257082.73225  1793129.82759  3199388.39175   1.02459   0.00104   0.00000  -0.00371   0.00000   0.00000   0.01004  -0.00028   0.00000   0.00727   0.00000   0.00000   0.00000   0.00000   0.26711   0.00000   2.34000
 Loc. PRN_09   Semimajor axis      (m)     26561660.4458      -0.0894       0.1986
 Loc. PRN_09   Eccentricity (none & m)      0.0201306828       0.0055       0.0965
 Loc. PRN_09   Inclination  (degs & m)     55.8611903728      -0.0324       0.1890
 Loc. PRN_09   RA Node      (degs & m)     42.8916239966      -1.2445       4.1477
 Loc. PRN_09   Arg. Perigee (degs & m)     83.1968241057       5.1721       9.3761
 Loc. PRN_09   M + w        (degs & m)    356.7233704610      -0.0323       0.2247

 216. PRN_10   Inert.  X     (m)           -959489.94356      1.11944      3.93314
 217. PRN_10   Inert.  Y     (m)          25184381.98413      0.05213      0.15911
 218. PRN_10   Inert.  Z     (m)           8765364.10519     -0.01781      0.11574
 219. PRN_10   Inert.  dX/dT (mm/s)       -2378739.12343      0.04357      0.14766
 220. PRN_10   Inert.  dY/dT (mm/s)         942217.04439      0.09739      0.37123
 221. PRN_10   Inert.  dZ/dT (mm/s)       -2885131.33566     -0.00366      0.01261
 222. PRN_10   Direct Rad    (none)              1.01395      0.01395      0.00498
 223. PRN_10   Y Axis Bias   (none)             -0.00432     -0.00432      0.00656
 224. PRN_10   B Axis Bias   (none)             -0.00280     -0.00280      0.01577
 225. PRN_10   Sin Direct    (none)              0.00005      0.00005      0.01630
 226. PRN_10   Cos Y Bias    (none)             -0.00096     -0.00096      0.01746
 227. PRN_10   Cos B Bias    (none)              0.00158      0.00158      0.03008
 228. PRN_10   AntOffest X   (m)                 0.27291     -0.00609      0.02161
Eph.  2008 12 28 11 PRN_10     -959489.9436  25184381.9841   8765364.1052 -2378739.12343   942217.04439 -2885131.33566   1.01395  -0.00432   0.00000  -0.00280   0.00000   0.00000   0.00005  -0.00096   0.00000   0.00158   0.00000   0.00000   0.00000   0.00000   0.27291   0.00000   2.38900
 Loc. PRN_10   Semimajor axis      (m)     26562562.5879       0.0014       0.1832
 Loc. PRN_10   Eccentricity (none & m)      0.0083654063      -0.0388       0.1149
 Loc. PRN_10   Inclination  (degs & m)     55.0097612024       0.0045       0.0769
 Loc. PRN_10   RA Node      (degs & m)    286.2715307246      -1.1996       4.1511
 Loc. PRN_10   Arg. Perigee (degs & m)     33.0081538173      -3.1718      15.2261
 Loc. PRN_10   M + w        (degs & m)    155.5576740675       0.1210       0.1257

 229. PRN_11   Inert.  X     (m)         -22585738.69937     -0.76836      2.13445
 230. PRN_11   Inert.  Y     (m)         -13575334.83339      1.51261      3.57103
 231. PRN_11   Inert.  Z     (m)          -1208673.38931     -0.18631      0.83476
 232. PRN_11   Inert.  dX/dT (mm/s)        1168431.03503     -0.15097      0.35679
 233. PRN_11   Inert.  dY/dT (mm/s)       -2167651.36004     -0.07504      0.18437
 234. PRN_11   Inert.  dZ/dT (mm/s)        3024958.65985      0.02185      0.03698
 235. PRN_11   Direct Rad    (none)              1.07182      0.07182      0.10924
 236. PRN_11   Y Axis Bias   (none)              0.00061      0.00061      0.00222
 237. PRN_11   B Axis Bias   (none)              0.00080      0.00080      0.01967
 238. PRN_11   Sin Direct    (none)              0.00190      0.00190      0.00968
 239. PRN_11   Cos Y Bias    (none)              0.00010      0.00010      0.01944
 240. PRN_11   Cos B Bias    (none)             -0.04199     -0.04199      0.06934
 241. PRN_11   AntOffest X   (m)                 0.46330      0.46330      0.62545
Eph.  2008 12 28 11 PRN_11   -22585738.6994 -13575334.8334  -1208673.3893  1168431.03503 -2167651.36004  3024958.65985   1.07182   0.00061   0.00000   0.00080   0.00000   0.00000   0.00190   0.00010   0.00000  -0.04199   0.00000   0.00000   0.00000   0.00000   0.46330   0.00000   0.97100
 Loc. PRN_11   Semimajor axis      (m)     26562015.3258      -0.0418       0.3149
 Loc. PRN_11   Eccentricity (none & m)      0.0091419546       0.1106       0.2925
 Loc. PRN_11   Inclination  (degs & m)     50.9513522184       0.1340       0.3727
 Loc. PRN_11   RA Node      (degs & m)    213.1406011412      -1.5590       4.2481
 Loc. PRN_11   Arg. Perigee (degs & m)     38.1525454930       1.9650      16.7029
 Loc. PRN_11   M + w        (degs & m)    357.3087390607      -0.0669       1.1532

 242. PRN_12   Inert.  X     (m)          10905714.69296      0.89796      2.08043
 243. PRN_12   Inert.  Y     (m)          13166100.32578     -0.77122      1.71946
 244. PRN_12   Inert.  Z     (m)         -20227585.04623      0.04977      0.09258
 245. PRN_12   Inert.  dX/dT (mm/s)       -1733258.20509      0.16491      0.50988
 246. PRN_12   Inert.  dY/dT (mm/s)        3264739.92613      0.10213      0.27175
 247. PRN_12   Inert.  dZ/dT (mm/s)        1195857.51430     -0.05270      0.04130
 248. PRN_12   Direct Rad    (none)              0.97385     -0.02615      0.01444
 249. PRN_12   Y Axis Bias   (none)              0.00648      0.00648      0.00532
 250. PRN_12   B Axis Bias   (none)             -0.01241     -0.01241      0.01445
 251. PRN_12   Sin Direct    (none)              0.00623      0.00623      0.01045
 252. PRN_12   Cos Y Bias    (none)             -0.00613     -0.00613      0.01753
 253. PRN_12   Cos B Bias    (none)              0.08200      0.08200      0.07043
 254. PRN_12   AntOffest X   (m)                -0.07541     -0.07541      0.13039
Eph.  2008 12 28 11 PRN_12    10905714.6930  13166100.3258 -20227585.0462 -1733258.20509  3264739.92613  1195857.51430   0.97385   0.00648   0.00000  -0.01241   0.00000   0.00000   0.00623  -0.00613   0.00000   0.08200   0.00000   0.00000   0.00000   0.00000  -0.07541   0.00000   0.70000
 Loc. PRN_12   Semimajor axis      (m)     26559699.8743      -0.1585       0.1521
 Loc. PRN_12   Eccentricity (none & m)      0.0030142562      -0.1172       0.1538
 Loc. PRN_12   Inclination  (degs & m)     55.4010731217      -0.2230       0.2627
 Loc. PRN_12   RA Node      (degs & m)    105.0681999163      -1.2107       4.1456
 Loc. PRN_12   Arg. Perigee (degs & m)    312.3062726477      -3.7139      16.5687
 Loc. PRN_12   M + w        (degs & m)    292.0197666037      -0.4492       0.3102

 255. PRN_13   Inert.  X     (m)         -25665228.16139     -0.05539      0.16769
 256. PRN_13   Inert.  Y     (m)            897278.78577      1.03577      4.00832
 257. PRN_13   Inert.  Z     (m)          -6919848.91204      0.08496      0.20061
 258. PRN_13   Inert.  dX/dT (mm/s)         741829.68376     -0.09924      0.34575
 259. PRN_13   Inert.  dY/dT (mm/s)       -2209096.39287     -0.00187      0.11804
 260. PRN_13   Inert.  dZ/dT (mm/s)       -3088187.81304     -0.01604      0.01300
 261. PRN_13   Direct Rad    (none)              0.99218     -0.00782      0.00914
 262. PRN_13   Y Axis Bias   (none)              0.00449      0.00449      0.00419
 263. PRN_13   B Axis Bias   (none)             -0.00501     -0.00501      0.01488
 264. PRN_13   Sin Direct    (none)              0.02714      0.02714      0.01857
 265. PRN_13   Cos Y Bias    (none)             -0.00316     -0.00316      0.01941
 266. PRN_13   Cos B Bias    (none)             -0.05722     -0.05722      0.04369
 267. PRN_13   AntOffest X   (m)                -0.03370     -0.03370      0.10615
Eph.  2008 12 28 11 PRN_13   -25665228.1614    897278.7858  -6919848.9120   741829.68376 -2209096.39287 -3088187.81304   0.99218   0.00449   0.00000  -0.00501   0.00000   0.00000   0.02714  -0.00316   0.00000  -0.05722   0.00000   0.00000   0.00000   0.00000  -0.03370   0.00000   1.20300
 Loc. PRN_13   Semimajor axis      (m)     26562444.1885       0.0616       0.1046
 Loc. PRN_13   Eccentricity (none & m)      0.0036253475       0.0171       0.0788
 Loc. PRN_13   Inclination  (degs & m)     57.0066686700       0.1766       0.1609
 Loc. PRN_13   RA Node      (degs & m)    347.9224493249      -0.9252       4.1508
 Loc. PRN_13   Arg. Perigee (degs & m)     86.9328260010       0.2695      17.9731
 Loc. PRN_13   M + w        (degs & m)    197.6834285520      -0.1986       0.1923

 268. PRN_14   Inert.  X     (m)          19393726.04335     -0.83465      2.04247
 269. PRN_14   Inert.  Y     (m)         -13044749.32716     -0.96116      3.03083
 270. PRN_14   Inert.  Z     (m)         -12595616.95139     -0.16339      0.13349
 271. PRN_14   Inert.  dX/dT (mm/s)        2554970.36876      0.07876      0.18814
 272. PRN_14   Inert.  dY/dT (mm/s)        1198911.24722     -0.13378      0.39876
 273. PRN_14   Inert.  dZ/dT (mm/s)        2655714.51730     -0.01270      0.01203
 274. PRN_14   Direct Rad    (none)              0.99535     -0.00465      0.00791
 275. PRN_14   Y Axis Bias   (none)              0.00943      0.00943      0.00514
 276. PRN_14   B Axis Bias   (none)              0.00857      0.00857      0.01771
 277. PRN_14   Sin Direct    (none)             -0.00073     -0.00073      0.02511
 278. PRN_14   Cos Y Bias    (none)             -0.00283     -0.00283      0.01924
 279. PRN_14   Cos B Bias    (none)             -0.02610     -0.02610      0.02511
 280. PRN_14   AntOffest X   (m)                -0.07824     -0.07824      0.07610
Eph.  2008 12 28 11 PRN_14    19393726.0434 -13044749.3272 -12595616.9514  2554970.36876  1198911.24722  2655714.51730   0.99535   0.00943   0.00000   0.00857   0.00000   0.00000  -0.00073  -0.00283   0.00000  -0.02610   0.00000   0.00000   0.00000   0.00000  -0.07824   0.00000   1.17800
 Loc. PRN_14   Semimajor axis      (m)     26559735.5120      -0.0947       0.1258
 Loc. PRN_14   Eccentricity (none & m)      0.0044892680      -0.0762       0.0818
 Loc. PRN_14   Inclination  (degs & m)     56.6393977207       0.0037       0.1205
 Loc. PRN_14   RA Node      (degs & m)    346.8559419246      -1.2406       4.1483
 Loc. PRN_14   Arg. Perigee (degs & m)    239.5519387219      -6.6553      17.9169
 Loc. PRN_14   M + w        (degs & m)    324.8767665280      -0.1300       0.1615

 281. PRN_15   Inert.  X     (m)          11648964.88953      0.51053      1.85953
 282. PRN_15   Inert.  Y     (m)          11879744.76007     -0.50493      1.81907
 283. PRN_15   Inert.  Z     (m)          20727114.83523      0.02923      0.06945
 284. PRN_15   Inert.  dX/dT (mm/s)       -3368293.38969      0.07231      0.25849
 285. PRN_15   Inert.  dY/dT (mm/s)        1654584.69915      0.14815      0.52606
 286. PRN_15   Inert.  dZ/dT (mm/s)         950246.98827     -0.00673      0.02268
 287. PRN_15   Direct Rad    (none)              0.97624     -0.02376      0.00849
 288. PRN_15   Y Axis Bias   (none)              0.01283      0.01283      0.00492
 289. PRN_15   B Axis Bias   (none)              0.01153      0.01153      0.01351
 290. PRN_15   Sin Direct    (none)             -0.01320     -0.01320      0.01827
 291. PRN_15   Cos Y Bias    (none)              0.01152      0.01152      0.01820
 292. PRN_15   Cos B Bias    (none)             -0.00056     -0.00056      0.04670
 293. PRN_15   AntOffest X   (m)                -0.01056     -0.01056      0.10956
Eph.  2008 12 28 11 PRN_15    11648964.8895  11879744.7601  20727114.8352 -3368293.38969  1654584.69915   950246.98827   0.97624   0.01283   0.00000   0.01153   0.00000   0.00000  -0.01320   0.01152   0.00000  -0.00056   0.00000   0.00000   0.00000   0.00000  -0.01056   0.00000   0.70000
 Loc. PRN_15   Semimajor axis      (m)     26559754.2303       0.0245       0.0888
 Loc. PRN_15   Eccentricity (none & m)      0.0013290712      -0.0160       0.0673
 Loc. PRN_15   Inclination  (degs & m)     54.8146240881       0.0053       0.0986
 Loc. PRN_15   RA Node      (degs & m)    344.1225751126      -1.2034       4.1493
 Loc. PRN_15   Arg. Perigee (degs & m)    309.6006121565      -4.4209      18.6846
 Loc. PRN_15   M + w        (degs & m)     72.4579544697       0.0743       0.2118

 294. PRN_16   Inert.  X     (m)           5313891.55544     -1.31556      4.05740
 295. PRN_16   Inert.  Y     (m)         -25979551.28409     -0.25609      0.83552
 296. PRN_16   Inert.  Z     (m)           3002941.83986     -0.03714      0.13999
 297. PRN_16   Inert.  dX/dT (mm/s)        2224214.24329      0.01829      0.02090
 298. PRN_16   Inert.  dY/dT (mm/s)          95898.34497     -0.10103      0.34808
 299. PRN_16   Inert.  dZ/dT (mm/s)       -3148011.49195      0.02105      0.01739
 300. PRN_16   Direct Rad    (none)              1.00226      0.00226      0.00888
 301. PRN_16   Y Axis Bias   (none)             -0.00312     -0.00312      0.00565
 302. PRN_16   B Axis Bias   (none)              0.01179      0.01179      0.01739
 303. PRN_16   Sin Direct    (none)              0.00059      0.00059      0.01169
 304. PRN_16   Cos Y Bias    (none)              0.00815      0.00815      0.01781
 305. PRN_16   Cos B Bias    (none)              0.06432      0.06432      0.03913
 306. PRN_16   AntOffest X   (m)                -0.02632     -0.02632      0.09686
Eph.  2008 12 28 11 PRN_16     5313891.5554 -25979551.2841   3002941.8399  2224214.24329    95898.34497 -3148011.49195   1.00226  -0.00312   0.00000   0.01179   0.00000   0.00000   0.00059   0.00815   0.00000   0.06432   0.00000   0.00000   0.00000   0.00000  -0.02632   0.00000   1.30700
 Loc. PRN_16   Semimajor axis      (m)     26562679.2989      -0.1583       0.2223
 Loc. PRN_16   Eccentricity (none & m)      0.0048339028       0.1408       0.1809
 Loc. PRN_16   Inclination  (degs & m)     55.4915024306      -0.1745       0.1068
 Loc. PRN_16   RA Node      (degs & m)    106.0251964534      -1.3380       4.1471
 Loc. PRN_16   Arg. Perigee (degs & m)    337.6118209676       4.9301      16.0380
 Loc. PRN_16   M + w        (degs & m)    172.2911646281       0.0516       0.1598

 307. PRN_17   Inert.  X     (m)         -21277328.04770      0.64930      2.11751
 308. PRN_17   Inert.  Y     (m)          12593192.54358      1.33758      3.41839
 309. PRN_17   Inert.  Z     (m)          -9899022.50716      0.09584      0.81348
 310. PRN_17   Inert.  dX/dT (mm/s)       -2197110.88216     -0.07716      0.28099
 311. PRN_17   Inert.  dY/dT (mm/s)       -1474975.97303      0.10897      0.34479
 312. PRN_17   Inert.  dZ/dT (mm/s)        2814816.20507     -0.01193      0.10663
 313. PRN_17   Direct Rad    (none)              1.03160      0.03160      0.11488
 314. PRN_17   Y Axis Bias   (none)              0.00687      0.00687      0.00323
 315. PRN_17   B Axis Bias   (none)              0.00042      0.00042      0.01973
 316. PRN_17   Sin Direct    (none)             -0.00151     -0.00151      0.00855
 317. PRN_17   Cos Y Bias    (none)              0.00199      0.00199      0.01903
 318. PRN_17   Cos B Bias    (none)              0.03254      0.03254      0.05998
 319. PRN_17   AntOffest X   (m)                 0.38027      0.38027      0.62270
Eph.  2008 12 28 11 PRN_17   -21277328.0477  12593192.5436  -9899022.5072 -2197110.88216 -1474975.97303  2814816.20507   1.03160   0.00687   0.00000   0.00042   0.00000   0.00000  -0.00151   0.00199   0.00000   0.03254   0.00000   0.00000   0.00000   0.00000   0.38027   0.00000   0.64500
 Loc. PRN_17   Semimajor axis      (m)     26560872.1822       0.0676       0.1866
 Loc. PRN_17   Eccentricity (none & m)      0.0040504050       0.0073       0.0939
 Loc. PRN_17   Inclination  (degs & m)     54.9761375086      -0.1762       0.6074
 Loc. PRN_17   RA Node      (degs & m)    165.6758391926      -1.5959       4.1855
 Loc. PRN_17   Arg. Perigee (degs & m)    200.9065768083      -1.7022      18.5160
 Loc. PRN_17   M + w        (degs & m)    332.6622063732       0.1068       1.3082

 320. PRN_18   Inert.  X     (m)          16910597.96931     -0.43369      1.28963
 321. PRN_18   Inert.  Y     (m)          -8248080.65971     -0.74771      2.63828
 322. PRN_18   Inert.  Z     (m)          19092843.86872      0.07272      0.06642
 323. PRN_18   Inert.  dX/dT (mm/s)          46887.74515      0.16215      0.55353
 324. PRN_18   Inert.  dY/dT (mm/s)        3545176.93657     -0.00143      0.01226
 325. PRN_18   Inert.  dZ/dT (mm/s)        1470433.47100     -0.00400      0.01305
 326. PRN_18   Direct Rad    (none)              1.01185      0.01185      0.00741
 327. PRN_18   Y Axis Bias   (none)              0.00306      0.00306      0.00788
 328. PRN_18   B Axis Bias   (none)             -0.00389     -0.00389      0.01653
 329. PRN_18   Sin Direct    (none)              0.00771      0.00771      0.01433
 330. PRN_18   Cos Y Bias    (none)              0.00596      0.00596      0.01810
 331. PRN_18   Cos B Bias    (none)             -0.00488     -0.00488      0.04247
 332. PRN_18   AntOffest X   (m)                 0.04045      0.04045      0.04511
Eph.  2008 12 28 11 PRN_18    16910597.9693  -8248080.6597  19092843.8687    46887.74515  3545176.93657  1470433.47100   1.01185   0.00306   0.00000  -0.00389   0.00000   0.00000   0.00771   0.00596   0.00000  -0.00488   0.00000   0.00000   0.00000   0.00000   0.04045   0.00000   1.13300
 Loc. PRN_18   Semimajor axis      (m)     26560039.1064       0.0045       0.1985
 Loc. PRN_18   Eccentricity (none & m)      0.0099288522      -0.0072       0.1528
 Loc. PRN_18   Inclination  (degs & m)     54.0948312563       0.0619       0.0684
 Loc. PRN_18   RA Node      (degs & m)    286.7163392580      -1.2802       4.1501
 Loc. PRN_18   Arg. Perigee (degs & m)    220.3428340011       2.9432       9.2985
 Loc. PRN_18   M + w        (degs & m)     61.9801677671       0.0305       0.1598

 333. PRN_19   Inert.  X     (m)         -12396283.47443     -0.28843      2.49504
 334. PRN_19   Inert.  Y     (m)         -12047427.79121      0.64779      2.01581
 335. PRN_19   Inert.  Z     (m)          20168556.51087      0.22587      0.94895
 336. PRN_19   Inert.  dX/dT (mm/s)        3362281.18639     -0.04461      0.26601
 337. PRN_19   Inert.  dY/dT (mm/s)       -1512029.10961     -0.13461      0.53572
 338. PRN_19   Inert.  dZ/dT (mm/s)        1188843.75418     -0.04682      0.20211
 339. PRN_19   Direct Rad    (none)              1.02767      0.02767      0.11091
 340. PRN_19   Y Axis Bias   (none)              0.00521      0.00521      0.00168
 341. PRN_19   B Axis Bias   (none)             -0.00039     -0.00039      0.01871
 342. PRN_19   Sin Direct    (none)             -0.00558     -0.00558      0.00887
 343. PRN_19   Cos Y Bias    (none)              0.00224      0.00224      0.01912
 344. PRN_19   Cos B Bias    (none)              0.08804      0.08804      0.10015
 345. PRN_19   AntOffest X   (m)                 0.17008      0.17008      0.60380
Eph.  2008 12 28 11 PRN_19   -12396283.4744 -12047427.7912  20168556.5109  3362281.18639 -1512029.10961  1188843.75418   1.02767   0.00521   0.00000  -0.00039   0.00000   0.00000  -0.00558   0.00224   0.00000   0.08804   0.00000   0.00000   0.00000   0.00000   0.17008   0.00000   0.66800
 Loc. PRN_19   Semimajor axis      (m)     26560111.4919       0.0170       0.1446
 Loc. PRN_19   Eccentricity (none & m)      0.0049919467      -0.1163       0.1530
 Loc. PRN_19   Inclination  (degs & m)     54.8405082945       0.1993       0.8355
 Loc. PRN_19   RA Node      (degs & m)    168.9151408236      -1.3834       4.1746
 Loc. PRN_19   Arg. Perigee (degs & m)    336.8158198185       0.9686      17.8658
 Loc. PRN_19   M + w        (degs & m)     67.6648014225       0.5952       2.0694

 346. PRN_20   Inert.  X     (m)         -13167451.43293     -0.44493      1.56161
 347. PRN_20   Inert.  Y     (m)          -9983768.75199      0.25001      2.07117
 348. PRN_20   Inert.  Z     (m)         -20905703.57003      0.20197      0.15236
 349. PRN_20   Inert.  dX/dT (mm/s)        1430589.60213     -0.11087      0.54710
 350. PRN_20   Inert.  dY/dT (mm/s)       -3500516.72458     -0.06258      0.22362
 351. PRN_20   Inert.  dZ/dT (mm/s)         779754.23398      0.00998      0.02080
 352. PRN_20   Direct Rad    (none)              0.99230     -0.00770      0.00727
 353. PRN_20   Y Axis Bias   (none)              0.01014      0.01014      0.00568
 354. PRN_20   B Axis Bias   (none)              0.01354      0.01354      0.01626
 355. PRN_20   Sin Direct    (none)             -0.00065     -0.00065      0.01321
 356. PRN_20   Cos Y Bias    (none)              0.00068      0.00068      0.01801
 357. PRN_20   Cos B Bias    (none)             -0.09519     -0.09519      0.05333
 358. PRN_20   AntOffest X   (m)                -0.01840     -0.01840      0.04823
Eph.  2008 12 28 11 PRN_20   -13167451.4329  -9983768.7520 -20905703.5700  1430589.60213 -3500516.72458   779754.23398   0.99230   0.01014   0.00000   0.01354   0.00000   0.00000  -0.00065   0.00068   0.00000  -0.09519   0.00000   0.00000   0.00000   0.00000  -0.01840   0.00000   1.15400
 Loc. PRN_20   Semimajor axis      (m)     26559259.2423       0.1774       0.1819
 Loc. PRN_20   Eccentricity (none & m)      0.0038122113      -0.2493       0.2042
 Loc. PRN_20   Inclination  (degs & m)     54.0699991943      -0.2273       0.1746
 Loc. PRN_20   RA Node      (degs & m)    283.6350615770      -0.9938       4.1511
 Loc. PRN_20   Arg. Perigee (degs & m)     75.4390378042       4.3022      13.9779
 Loc. PRN_20   M + w        (degs & m)    284.5479326178      -0.0358       0.1556

 359. PRN_21   Inert.  X     (m)          18980557.06142      0.06942      0.46028
 360. PRN_21   Inert.  Y     (m)            -77851.06464     -0.69864      3.00438
 361. PRN_21   Inert.  Z     (m)          18552800.93250     -0.07550      0.49237
 362. PRN_21   Inert.  dX/dT (mm/s)        1478473.61909      0.13309      0.50559
 363. PRN_21   Inert.  dY/dT (mm/s)        3216796.59022     -0.07078      0.23154
 364. PRN_21   Inert.  dZ/dT (mm/s)       -1579229.70620     -0.02020      0.04087
 365. PRN_21   Direct Rad    (none)              1.00371      0.00371      0.09948
 366. PRN_21   Y Axis Bias   (none)             -0.00066     -0.00066      0.00283
 367. PRN_21   B Axis Bias   (none)              0.00043      0.00043      0.01926
 368. PRN_21   Sin Direct    (none)             -0.00911     -0.00911      0.00880
 369. PRN_21   Cos Y Bias    (none)             -0.00022     -0.00022      0.01857
 370. PRN_21   Cos B Bias    (none)             -0.04361     -0.04361      0.07911
 371. PRN_21   AntOffest X   (m)                 0.09745      0.09745      0.60560
Eph.  2008 12 28 11 PRN_21    18980557.0614    -77851.0646  18552800.9325  1478473.61909  3216796.59022 -1579229.70620   1.00371  -0.00066   0.00000   0.00043   0.00000   0.00000  -0.00911  -0.00022   0.00000  -0.04361   0.00000   0.00000   0.00000   0.00000   0.09745   0.00000   1.30000
 Loc. PRN_21   Semimajor axis      (m)     26559379.3496       0.0013       0.2534
 Loc. PRN_21   Eccentricity (none & m)      0.0144701324      -0.0338       0.1301
 Loc. PRN_21   Inclination  (degs & m)     53.5165400689       0.0255       0.6227
 Loc. PRN_21   RA Node      (degs & m)    226.0546388570      -1.2519       4.1712
 Loc. PRN_21   Arg. Perigee (degs & m)    207.8404357848      -0.0826      15.1417
 Loc. PRN_21   M + w        (degs & m)    121.2710308302       0.1536       0.6341

 372. PRN_22   Inert.  X     (m)          14544733.89680     -0.93620      3.00399
 373. PRN_22   Inert.  Y     (m)         -19235631.84750     -0.70650      2.27044
 374. PRN_22   Inert.  Z     (m)          11354374.58244      0.06944      0.10703
 375. PRN_22   Inert.  dX/dT (mm/s)        1256196.24718      0.12918      0.39054
 376. PRN_22   Inert.  dY/dT (mm/s)        2500609.18455     -0.05845      0.19609
 377. PRN_22   Inert.  dZ/dT (mm/s)        2658990.40895     -0.00705      0.01382
 378. PRN_22   Direct Rad    (none)              1.00164      0.00164      0.00783
 379. PRN_22   Y Axis Bias   (none)              0.00704      0.00704      0.00690
 380. PRN_22   B Axis Bias   (none)              0.00423      0.00423      0.01509
 381. PRN_22   Sin Direct    (none)              0.01112      0.01112      0.01433
 382. PRN_22   Cos Y Bias    (none)              0.00198      0.00198      0.01808
 383. PRN_22   Cos B Bias    (none)              0.00306      0.00306      0.04722
 384. PRN_22   AntOffest X   (m)                 0.00117      0.00117      0.05067
Eph.  2008 12 28 11 PRN_22    14544733.8968 -19235631.8475  11354374.5824  1256196.24718  2500609.18455  2658990.40895   1.00164   0.00704   0.00000   0.00423   0.00000   0.00000   0.01112   0.00198   0.00000   0.00306   0.00000   0.00000   0.00000   0.00000   0.00117   0.00000   0.79200
 Loc. PRN_22   Semimajor axis      (m)     26560986.8794       0.0474       0.1747
 Loc. PRN_22   Eccentricity (none & m)      0.0049823624       0.0165       0.1313
 Loc. PRN_22   Inclination  (degs & m)     53.9618122445      -0.0406       0.0767
 Loc. PRN_22   RA Node      (degs & m)    287.0613115557      -1.3826       4.1510
 Loc. PRN_22   Arg. Perigee (degs & m)    256.4165436542       8.7996      12.6105
 Loc. PRN_22   M + w        (degs & m)     31.3868694332       0.0163       0.2017

 385. PRN_23   Inert.  X     (m)         -21347592.56892     -0.20992      0.77837
 386. PRN_23   Inert.  Y     (m)          -4878721.49807      1.01393      3.33462
 387. PRN_23   Inert.  Z     (m)         -14885237.09965     -0.09465      0.20471
 388. PRN_23   Inert.  dX/dT (mm/s)        2131702.49137     -0.09263      0.34996
 389. PRN_23   Inert.  dY/dT (mm/s)       -2235097.65054     -0.08054      0.33356
 390. PRN_23   Inert.  dZ/dT (mm/s)       -2358086.59268      0.00232      0.01787
 391. PRN_23   Direct Rad    (none)              1.01245      0.01245      0.00856
 392. PRN_23   Y Axis Bias   (none)              0.00151      0.00151      0.00402
 393. PRN_23   B Axis Bias   (none)              0.00224      0.00224      0.01583
 394. PRN_23   Sin Direct    (none)              0.01362      0.01362      0.02163
 395. PRN_23   Cos Y Bias    (none)              0.00030      0.00030      0.01912
 396. PRN_23   Cos B Bias    (none)             -0.01074     -0.01074      0.04101
 397. PRN_23   AntOffest X   (m)                 0.04719      0.04719      0.09766
Eph.  2008 12 28 11 PRN_23   -21347592.5689  -4878721.4981 -14885237.0996  2131702.49137 -2235097.65054 -2358086.59268   1.01245   0.00151   0.00000   0.00224   0.00000   0.00000   0.01362   0.00030   0.00000  -0.01074   0.00000   0.00000   0.00000   0.00000   0.04719   0.00000   0.60200
 Loc. PRN_23   Semimajor axis      (m)     26560085.2172      -0.0094       0.1498
 Loc. PRN_23   Eccentricity (none & m)      0.0057428501      -0.0578       0.1258
 Loc. PRN_23   Inclination  (degs & m)     55.6107696679       0.1299       0.1434
 Loc. PRN_23   RA Node      (degs & m)    345.1467734347      -1.2115       4.1500
 Loc. PRN_23   Arg. Perigee (degs & m)    165.1581480199      -2.7980      15.7360
 Loc. PRN_23   M + w        (degs & m)    222.3849623713       0.1211       0.1958

 398. PRN_24   Inert.  X     (m)          21008682.44499      0.65799      2.24618
 399. PRN_24   Inert.  Y     (m)          14316044.73748     -1.12952      3.29721
 400. PRN_24   Inert.  Z     (m)           8299496.33441      0.29741      0.50061
 401. PRN_24   Inert.  dX/dT (mm/s)        -548910.19468      0.16132      0.39329
 402. PRN_24   Inert.  dY/dT (mm/s)        2471930.04293      0.03593      0.08805
 403. PRN_24   Inert.  dZ/dT (mm/s)       -2896736.54082     -0.00182      0.02244
 404. PRN_24   Direct Rad    (none)              1.04728      0.04728      0.07915
 405. PRN_24   Y Axis Bias   (none)             -0.01313     -0.01313      0.00328
 406. PRN_24   B Axis Bias   (none)             -0.00258     -0.00258      0.01986
 407. PRN_24   Sin Direct    (none)             -0.00815     -0.00815      0.00909
 408. PRN_24   Cos Y Bias    (none)             -0.00219     -0.00219      0.01770
 409. PRN_24   Cos B Bias    (none)             -0.02253     -0.02253      0.08038
 410. PRN_24   AntOffest X   (m)                 0.20309     -0.07591      0.42087
Eph.  2008 12 28 11 PRN_24    21008682.4450  14316044.7375   8299496.3344  -548910.19468  2471930.04293 -2896736.54082   1.04728  -0.01313   0.00000  -0.00258   0.00000   0.00000  -0.00815  -0.00219   0.00000  -0.02253   0.00000   0.00000   0.00000   0.00000   0.20309   0.00000   2.45500
 Loc. PRN_24   Semimajor axis      (m)     26561455.8998       0.0286       0.3454
 Loc. PRN_24   Eccentricity (none & m)      0.0070726573      -0.0152       0.3275
 Loc. PRN_24   Inclination  (degs & m)     54.4724961282       0.1842       0.3240
 Loc. PRN_24   RA Node      (degs & m)    227.7514184251      -1.2044       4.1764
 Loc. PRN_24   Arg. Perigee (degs & m)    322.9537596766      -5.6305      17.0717
 Loc. PRN_24   M + w        (degs & m)    157.7896098573      -0.2715       0.6065

 411. PRN_25   Inert.  X     (m)         -22802875.67792     -0.48592      1.54825
 412. PRN_25   Inert.  Y     (m)          -9900072.23553      0.88547      3.56367
 413. PRN_25   Inert.  Z     (m)           9963554.45516     -0.10584      0.13799
 414. PRN_25   Inert.  dX/dT (mm/s)         -77047.59737     -0.11337      0.40492
 415. PRN_25   Inert.  dY/dT (mm/s)       -2590560.61416      0.01484      0.01607
 416. PRN_25   Inert.  dZ/dT (mm/s)       -2836000.44475     -0.01175      0.01362
 417. PRN_25   Direct Rad    (none)              1.03750      0.03750      0.00999
 418. PRN_25   Y Axis Bias   (none)             -0.00328     -0.00328      0.00518
 419. PRN_25   B Axis Bias   (none)              0.00212      0.00212      0.01766
 420. PRN_25   Sin Direct    (none)             -0.00588     -0.00588      0.02611
 421. PRN_25   Cos Y Bias    (none)             -0.00521     -0.00521      0.01901
 422. PRN_25   Cos B Bias    (none)             -0.01299     -0.01299      0.05368
 423. PRN_25   AntOffest X   (m)                 0.30635      0.02735      0.11398
Eph.  2008 12 28 11 PRN_25   -22802875.6779  -9900072.2355   9963554.4552   -77047.59737 -2590560.61416 -2836000.44475   1.03750  -0.00328   0.00000   0.00212   0.00000   0.00000  -0.00588  -0.00521   0.00000  -0.01299   0.00000   0.00000   0.00000   0.00000   0.30635   0.00000   2.29500
 Loc. PRN_25   Semimajor axis      (m)     26561178.4490       0.1054       0.2089
 Loc. PRN_25   Eccentricity (none & m)      0.0117304125      -0.1088       0.1351
 Loc. PRN_25   Inclination  (degs & m)     55.4774786376       0.0790       0.0898
 Loc. PRN_25   RA Node      (degs & m)     39.4718382995      -1.2326       4.1469
 Loc. PRN_25   Arg. Perigee (degs & m)    288.6619993947       2.2389      10.0054
 Loc. PRN_25   M + w        (degs & m)    154.1051582408       0.0053       0.1492

 424. PRN_26   Inert.  X     (m)           3638702.78862      0.70862      2.16322
 425. PRN_26   Inert.  Y     (m)          13813211.16757     -0.09543      0.57730
 426. PRN_26   Inert.  Z     (m)          21876252.58341     -0.02159      0.06118
 427. PRN_26   Inert.  dX/dT (mm/s)       -3830473.67978      0.04922      0.14181
 428. PRN_26   Inert.  dY/dT (mm/s)         904546.90334      0.16934      0.59821
 429. PRN_26   Inert.  dZ/dT (mm/s)         115301.98033      0.00333      0.03263
 430. PRN_26   Direct Rad    (none)              1.02172      0.02172      0.00972
 431. PRN_26   Y Axis Bias   (none)             -0.00287     -0.00287      0.00498
 432. PRN_26   B Axis Bias   (none)             -0.00292     -0.00292      0.01939
 433. PRN_26   Sin Direct    (none)              0.00501      0.00501      0.02752
 434. PRN_26   Cos Y Bias    (none)              0.00152      0.00152      0.01924
 435. PRN_26   Cos B Bias    (none)             -0.00889     -0.00889      0.06548
 436. PRN_26   AntOffest X   (m)                 0.30701      0.02801      0.11955
Eph.  2008 12 28 11 PRN_26     3638702.7886  13813211.1676  21876252.5834 -3830473.67978   904546.90334   115301.98033   1.02172  -0.00287   0.00000  -0.00292   0.00000   0.00000   0.00501   0.00152   0.00000  -0.00889   0.00000   0.00000   0.00000   0.00000   0.30701   0.00000   2.30700
 Loc. PRN_26   Semimajor axis      (m)     26558121.6553      -0.0615       0.1942
 Loc. PRN_26   Eccentricity (none & m)      0.0193294625      -0.1057       0.1382
 Loc. PRN_26   Inclination  (degs & m)     56.8831700078      -0.0840       0.1030
 Loc. PRN_26   RA Node      (degs & m)    347.8082735984      -1.1691       4.1525
 Loc. PRN_26   Arg. Perigee (degs & m)     55.1305819601      -0.2102       5.1751
 Loc. PRN_26   M + w        (degs & m)     87.3905924812       0.0245       0.2557

 437. PRN_27   Inert.  X     (m)         -13838542.59450      0.34550      1.21400
 438. PRN_27   Inert.  Y     (m)           7747264.61362      0.52262      2.16929
 439. PRN_27   Inert.  Z     (m)          21986629.06222      0.03422      0.07625
 440. PRN_27   Inert.  dX/dT (mm/s)       -2503584.61385     -0.11185      0.43485
 441. PRN_27   Inert.  dY/dT (mm/s)       -2783837.46602      0.10698      0.39098
 442. PRN_27   Inert.  dZ/dT (mm/s)        -624139.93183      0.00117      0.02125
 443. PRN_27   Direct Rad    (none)              1.02457      0.02457      0.01074
 444. PRN_27   Y Axis Bias   (none)             -0.00477     -0.00477      0.00517
 445. PRN_27   B Axis Bias   (none)             -0.00224     -0.00224      0.01858
 446. PRN_27   Sin Direct    (none)              0.01796      0.01796      0.02920
 447. PRN_27   Cos Y Bias    (none)              0.00457      0.00457      0.01897
 448. PRN_27   Cos B Bias    (none)             -0.03110     -0.03110      0.05326
 449. PRN_27   AntOffest X   (m)                 0.31866      0.03966      0.10688
Eph.  2008 12 28 11 PRN_27   -13838542.5945   7747264.6136  21986629.0622 -2503584.61385 -2783837.46602  -624139.93183   1.02457  -0.00477   0.00000  -0.00224   0.00000   0.00000   0.01796   0.00457   0.00000  -0.03110   0.00000   0.00000   0.00000   0.00000   0.31866   0.00000   2.47200
 Loc. PRN_27   Semimajor axis      (m)     26574752.2607      -0.0642       0.2102
 Loc. PRN_27   Eccentricity (none & m)      0.0210806343       0.0586       0.1704
 Loc. PRN_27   Inclination  (degs & m)     55.7441538427       0.0608       0.1007
 Loc. PRN_27   RA Node      (degs & m)     41.5152594032      -1.0813       4.1490
 Loc. PRN_27   Arg. Perigee (degs & m)    264.2075645785       1.6263       3.7703
 Loc. PRN_27   M + w        (degs & m)    101.8300847931      -0.0272       0.1966

 450. PRN_28   Inert.  X     (m)         -14990573.61822      0.78178      2.78511
 451. PRN_28   Inert.  Y     (m)          17818459.74059      0.56859      2.34545
 452. PRN_28   Inert.  Z     (m)          13488487.79350      0.13550      0.21524
 453. PRN_28   Inert.  dX/dT (mm/s)       -1002348.23196     -0.10696      0.42342
 454. PRN_28   Inert.  dY/dT (mm/s)       -2707127.82048      0.02452      0.15759
 455. PRN_28   Inert.  dZ/dT (mm/s)        2506811.11408     -0.00092      0.02233
 456. PRN_28   Direct Rad    (none)              0.99190     -0.00810      0.01588
 457. PRN_28   Y Axis Bias   (none)              0.00304      0.00304      0.00494
 458. PRN_28   B Axis Bias   (none)              0.00574      0.00574      0.01819
 459. PRN_28   Sin Direct    (none)             -0.00609     -0.00609      0.01037
 460. PRN_28   Cos Y Bias    (none)              0.00214      0.00214      0.01747
 461. PRN_28   Cos B Bias    (none)              0.05483      0.05483      0.06934
 462. PRN_28   AntOffest X   (m)                -0.10960     -0.10960      0.15508
Eph.  2008 12 28 11 PRN_28   -14990573.6182  17818459.7406  13488487.7935 -1002348.23196 -2707127.82048  2506811.11408   0.99190   0.00304   0.00000   0.00574   0.00000   0.00000  -0.00609   0.00214   0.00000   0.05483   0.00000   0.00000   0.00000   0.00000  -0.10960   0.00000   0.91100
 Loc. PRN_28   Semimajor axis      (m)     26560543.2316       0.1537       0.2824
 Loc. PRN_28   Eccentricity (none & m)      0.0144031213      -0.1297       0.2408
 Loc. PRN_28   Inclination  (degs & m)     55.3861913540       0.0569       0.1631
 Loc. PRN_28   RA Node      (degs & m)    106.5071374592      -1.1971       4.1485
 Loc. PRN_28   Arg. Perigee (degs & m)    241.1551528845       4.9986      12.3323
 Loc. PRN_28   M + w        (degs & m)     36.8520747209       0.1455       0.2719

 463. PRN_29   Inert.  X     (m)          25408219.32623      0.07023      0.33862
 464. PRN_29   Inert.  Y     (m)           -733157.20591     -0.73891      4.01943
 465. PRN_29   Inert.  Z     (m)          -7667561.21316      0.52284      1.16166
 466. PRN_29   Inert.  dX/dT (mm/s)        -840465.24911      0.14989      0.40041
 467. PRN_29   Inert.  dY/dT (mm/s)        2347909.48017      0.05117      0.13610
 468. PRN_29   Inert.  dZ/dT (mm/s)       -2966676.14935     -0.00635      0.02105
 469. PRN_29   Direct Rad    (none)              1.05986      0.05986      0.11521
 470. PRN_29   Y Axis Bias   (none)              0.00158      0.00158      0.00251
 471. PRN_29   B Axis Bias   (none)             -0.00052     -0.00052      0.01981
 472. PRN_29   Sin Direct    (none)             -0.00027     -0.00027      0.00907
 473. PRN_29   Cos Y Bias    (none)              0.00274      0.00274      0.01943
 474. PRN_29   Cos B Bias    (none)              0.07992      0.07992      0.08199
 475. PRN_29   AntOffest X   (m)                 0.55513      0.55513      0.60298
Eph.  2008 12 28 11 PRN_29    25408219.3262   -733157.2059  -7667561.2132  -840465.24911  2347909.48017 -2966676.14935   1.05986   0.00158   0.00000  -0.00052   0.00000   0.00000  -0.00027   0.00274   0.00000   0.07992   0.00000   0.00000   0.00000   0.00000   0.55513   0.00000   0.70000
 Loc. PRN_29   Semimajor axis      (m)     26562591.3673      -0.0808       0.1364
 Loc. PRN_29   Eccentricity (none & m)      0.0032313162      -0.1236       0.1257
 Loc. PRN_29   Inclination  (degs & m)     54.9858395031      -0.3287       0.5772
 Loc. PRN_29   RA Node      (degs & m)    166.1469810952      -0.5087       4.2308
 Loc. PRN_29   Arg. Perigee (degs & m)    282.4474248456      -0.8994      18.7241
 Loc. PRN_29   M + w        (degs & m)    201.0137786124      -0.8167       1.4509

 476. PRN_30   Inert.  X     (m)          15955915.35242      0.02142      0.24202
 477. PRN_30   Inert.  Y     (m)           -964207.09314     -1.07714      2.50420
 478. PRN_30   Inert.  Z     (m)         -21580876.26399      0.11801      0.16218
 479. PRN_30   Inert.  dX/dT (mm/s)        -461616.28454      0.20946      0.58919
 480. PRN_30   Inert.  dY/dT (mm/s)        3768599.50319      0.02819      0.07334
 481. PRN_30   Inert.  dZ/dT (mm/s)        -510183.53384     -0.02884      0.02009
 482. PRN_30   Direct Rad    (none)              1.01195      0.01195      0.01369
 483. PRN_30   Y Axis Bias   (none)             -0.00411     -0.00411      0.00603
 484. PRN_30   B Axis Bias   (none)             -0.00346     -0.00346      0.01703
 485. PRN_30   Sin Direct    (none)             -0.00533     -0.00533      0.01304
 486. PRN_30   Cos Y Bias    (none)             -0.00606     -0.00606      0.01809
 487. PRN_30   Cos B Bias    (none)              0.04275      0.04275      0.07479
 488. PRN_30   AntOffest X   (m)                 0.23270     -0.04630      0.10832
Eph.  2008 12 28 11 PRN_30    15955915.3524   -964207.0931 -21580876.2640  -461616.28454  3768599.50319  -510183.53384   1.01195  -0.00411   0.00000  -0.00346   0.00000   0.00000  -0.00533  -0.00606   0.00000   0.04275   0.00000   0.00000   0.00000   0.00000   0.23270   0.00000   2.46600
 Loc. PRN_30   Semimajor axis      (m)     26558593.6832       0.0009       0.1665
 Loc. PRN_30   Eccentricity (none & m)      0.0112059293      -0.0448       0.1681
 Loc. PRN_30   Inclination  (degs & m)     54.5397851709      -0.0739       0.2251
 Loc. PRN_30   RA Node      (degs & m)    102.4753799664      -1.3206       4.1462
 Loc. PRN_30   Arg. Perigee (degs & m)     81.1357463123      -4.6363       7.5144
 Loc. PRN_30   M + w        (degs & m)    260.5836334595      -0.2010       0.1818

 489. PRN_31   Inert.  X     (m)           4393133.86165     -0.62735      2.45335
 490. PRN_31   Inert.  Y     (m)         -15660547.73462     -0.09762      0.71041
 491. PRN_31   Inert.  Z     (m)         -20806987.35500      0.00800      0.10774
 492. PRN_31   Inert.  dX/dT (mm/s)        3100479.43595      0.09995      0.33757
 493. PRN_31   Inert.  dY/dT (mm/s)        2159335.54739     -0.13561      0.48449
 494. PRN_31   Inert.  dZ/dT (mm/s)        -949475.23010      0.00990      0.02253
 495. PRN_31   Direct Rad    (none)              0.97337     -0.02663      0.00823
 496. PRN_31   Y Axis Bias   (none)              0.00659      0.00659      0.00532
 497. PRN_31   B Axis Bias   (none)              0.00626      0.00626      0.01862
 498. PRN_31   Sin Direct    (none)              0.00661      0.00661      0.02848
 499. PRN_31   Cos Y Bias    (none)              0.00014      0.00014      0.01833
 500. PRN_31   Cos B Bias    (none)              0.02683      0.02683      0.03767
 501. PRN_31   AntOffest X   (m)                -0.02897     -0.02897      0.08386
Eph.  2008 12 28 11 PRN_31     4393133.8616 -15660547.7346 -20806987.3550  3100479.43595  2159335.54739  -949475.23010   0.97337   0.00659   0.00000   0.00626   0.00000   0.00000   0.00661   0.00014   0.00000   0.02683   0.00000   0.00000   0.00000   0.00000  -0.02897   0.00000   0.75000
 Loc. PRN_31   Semimajor axis      (m)     26558363.6655      -0.0796       0.1930
 Loc. PRN_31   Eccentricity (none & m)      0.0070371377      -0.0512       0.1406
 Loc. PRN_31   Inclination  (degs & m)     55.6580729410      -0.0012       0.1442
 Loc. PRN_31   RA Node      (degs & m)     44.7415653588      -1.2371       4.1479
 Loc. PRN_31   Arg. Perigee (degs & m)    290.2398597709      -3.2535      14.0787
 Loc. PRN_31   M + w        (degs & m)    253.0778543194       0.0394       0.1519

 502. PRN_32   Inert.  X     (m)          -7059099.53522     -0.79022      2.73943
 503. PRN_32   Inert.  Y     (m)         -17522191.57726      0.37374      1.12483
 504. PRN_32   Inert.  Z     (m)         -18159464.88419     -0.06919      0.13606
 505. PRN_32   Inert.  dX/dT (mm/s)        2245746.07960     -0.12040      0.42413
 506. PRN_32   Inert.  dY/dT (mm/s)       -2715983.40164     -0.10564      0.35093
 507. PRN_32   Inert.  dZ/dT (mm/s)        1730820.26072     -0.02128      0.01593
 508. PRN_32   Direct Rad    (none)              1.03010      0.03010      0.00509
 509. PRN_32   Y Axis Bias   (none)             -0.00804     -0.00804      0.00692
 510. PRN_32   B Axis Bias   (none)             -0.00409     -0.00409      0.01763
 511. PRN_32   Sin Direct    (none)              0.00537      0.00537      0.01560
 512. PRN_32   Cos Y Bias    (none)             -0.01031     -0.01031      0.01775
 513. PRN_32   Cos B Bias    (none)             -0.02084     -0.02084      0.03455
 514. PRN_32   AntOffest X   (m)                 0.27862     -0.00038      0.01309
Eph.  2008 12 28 11 PRN_32    -7059099.5352 -17522191.5773 -18159464.8842  2245746.07960 -2715983.40164  1730820.26072   1.03010  -0.00804   0.00000  -0.00409   0.00000   0.00000   0.00537  -0.01031   0.00000  -0.02084   0.00000   0.00000   0.00000   0.00000   0.27862   0.00000   2.57500
 Loc. PRN_32   Semimajor axis      (m)     26559637.0500      -0.0495       0.1459
 Loc. PRN_32   Eccentricity (none & m)      0.0137347787      -0.0484       0.1145
 Loc. PRN_32   Inclination  (degs & m)     55.3309984222       0.0013       0.1058
 Loc. PRN_32   RA Node      (degs & m)    289.7288136747      -1.0750       4.1500
 Loc. PRN_32   Arg. Perigee (degs & m)    289.8937906707      -4.3981      10.9435
 Loc. PRN_32   M + w        (degs & m)    302.2396725627      -0.2319       0.1358

 515. X-pole position        (mas)              -3.58160     -0.40121      0.27824
 516. Y-pole position        (mas)             142.11495     -0.31944      0.32713
 517. X-pole rate            (ms/d)             -2.57740      1.65540      1.60947
 518. Y-pole rate            (ms/d)              1.32346     -0.03047      1.36935

 519. UT1-AT                 (ms)           -33585.10634      5.37263      2.14680
 520. UT1-AT rate            (ms/d)             -0.37095     -0.01491      0.09694
      Pole/UT1 correlations: XY, XU, YU         -0.0219     0.0000     0.0031

IERS  MJD      Xpole   Ypole  UT1-UTC    LOD  Xsig  Ysig   UTsig  LODsig  Nr Nf Nt    Xrt    Yrt  Xrtsig  Yrtsig XYcorr XUTcor YUTcor
IERS             (10**-6")       (0.1 usec)    (10**-6")     (0.1 usec)              (10**-6"/d)    (10**-6"/d)
IERS54828.50   -3582  142115 -5851063   3710   278   327   21468     969  50  0 32  -2577   1323   1609   1369   -0.022  0.000  0.003


