#!/bin/sh

ids=`grep '^ ' ../ids`
#ids=`grep '^ ' ./ids_online`
#ids=`cat ../ids_12`

for id in $ids; do
  if [ $id -eq 1 ]; then
    echo continue
    cmdstr="systemctl disable slurmctld"
    echo  disable slurmd service on node${id} with command $cmdstr
    ssh node${id} $cmdstr

  fi

  cmdstr="systemctl disable slurmd"
  echo  disable slurmd service on node${id} with command $cmdstr
  ssh node${id} $cmdstr
  #exit
done


