#!/bin/sh

ids=`grep '^ ' ../ids`
#ids=`cat ../ids_12`

for id in $ids; do
  if [ $id -eq 1 ]; then
    echo continue
  fi

  cmdstr="systemctl enable slurmd"
  echo  enable slurmd service on node${id} with command $cmdstr
  ssh node${id} $cmdstr
  #exit
done


