#!/bin/sh


host_name=`hostname`
echo host name $host_name
id_cur=`echo $host_name | sed -e 's/[a-z]//g' | sed -e 's/[A-Z]//g'`
echo current host id $id_cur
host_type=`echo $host_name | sed -e 's/[0-9]//g'`
echo host type $host_type

file_ids=../ids.${host_name}
if [ ! -s $file_ids ]; then
  echo "[$PROG]ERROR:file $file_ids not exist!!"
  exit
fi

ids=`grep '^ ' $file_ids`
#ids=`cat ../ids_12`
echo ids $ids
#exit

for id in $ids; do
  if [ $id -eq $id_cur ]; then
    #echo continue
    #echo continue
    cmdstr1="systemctl stop slurmctld"
    echo  stopping slurmd service on ${host_type}${id} with command $cmdstr1
    ssh ${host_type}${id} $cmdstr1

  fi

  cmdstr1="systemctl stop slurmd"
  echo  stopping slurmd service on ${host_type}${id} with command $cmdstr1
  ssh ${host_type}${id} $cmdstr1


  #exit
done


