#!/bin/sh


host_name=`hostname`
echo host name $host_name
id_cur=`echo $host_name | sed -e 's/[a-z]//g' | sed -e 's/[A-Z]//g'`
echo current host id $id_cur
host_type=`echo $host_name | sed -e 's/[0-9]//g'`
echo host type $host_type

#file_ids=./${host_name}/ids_online
file_ids=../ids.${host_name}
if [ ! -s $file_ids ]; then
  echo "[$PROG]ERROR:file $file_ids not exist!!"
  exit
fi

ids=`grep '^ ' $file_ids`
#ids=`cat ../ids_12`
echo ids $ids
#exit

for id in $ids; do

  cmdstr2="systemctl restart slurmd"
  cmdstr1="systemctl daemon-reload"
  echo  starting slurmd service on ${host_type}${id} with command $cmdstr1 and $cmdstr2
  ssh ${host_type}${id} $cmdstr1
  ssh ${host_type}${id} $cmdstr2

  if [ $id -eq $id_cur ]; then
    cmdstr2="systemctl restart slurmctld"
    echo  starting slurmctld service on ${host_type}${id} with command $cmdstr2
    ssh ${host_type}${id} $cmdstr2
  fi

  #exit
done

sinfo
