#!/bin/sh

systemctl enable firewalld
systemctl restart firewalld

#vncserver
firewall-cmd --zone=public --add-port=5901/tcp --permanent
firewall-cmd --add-service vnc-server

#samba
firewall-cmd --add-service=samba

#nfs
firewall-cmd  --permanent    --add-port=111/tcp
firewall-cmd  --permanent    --add-port=111/udp
firewall-cmd  --permanent    --add-port=2049/tcp
firewall-cmd  --permanent    --add-port=2049/udp
#
firewall-cmd  --permanent    --add-port=32803/tcp
firewall-cmd  --permanent    --add-port=32769/udp
firewall-cmd  --permanent    --add-port=892/tcp
firewall-cmd  --permanent    --add-port=892/udp
firewall-cmd  --permanent    --add-port=662/tcp
firewall-cmd  --permanent    --add-port=662/udp
firewall-cmd  --permanent    --add-port=2020/tcp
firewall-cmd  --permanent    --add-port=2020/udp

#slurm
firewall-cmd  --permanent    --add-port=6817/tcp
firewall-cmd  --permanent    --add-port=6818/tcp
firewall-cmd  --permanent    --add-port=7321/tcp

#
firewall-cmd --permanent --zone=public --add-rich-rule='rule family="ipv4" source address="10.4.0.0/16" accept'
firewall-cmd --permanent --zone=public --add-rich-rule='rule family="ipv4" source address="10.4.0.0/16" invert="true" drop'

firewall-cmd --reload
firewall-cmd --list-port

systemctl restart firewalld
