#!/bin/sh

ids=`grep '^ ' ../ids`
#ids='18'
#ids="19 20"


if [ 1 -eq 1 ]; then
file='./public.xml'
for id in $ids; do
  echo scp ./$file node${id}:/etc/firewalld/zones/
  echo scp ./$file node${id}:/etc/firewalld/zones/ | sh
done
fi
