#!/bin/sh

ids=`grep '^ ' ../ids`
#ids=`cat ../ids_12`
#ids="2 3 4 5 6 7 8 9 10 11"
ids='19 20'

for id in $ids; do
  if [ $id -le 1 ]; then
    echo continue
    continue
  fi

  cmdstr1="yum -y install gdal.x86_64 gdal-devel compat-glib* compat-libstdc++* libstdc++*"
  cmdstr1='yum -y install samba'
  echo  starting yum installer on node${id} with command $cmdstr1 and $cmdstr2
  ssh node${id} $cmdstr1
  #ssh node${id} $cmdstr2


  #exit
done


