PRO MJD2DECYRS,MJDS,DECYRS
  IF N_PARAMS() LT 1 THEN BEGIN
    MJDS=54942.5
  ENDIF
  
  DECYRS=DBLARR(N_ELEMENTS(MJDS))
  
  FOR I=0,N_ELEMENTS(MJDS)-1 DO BEGIN
    DOY,MJDS[I],DYEAR=DYEAR
    DECYRS[I]=DYEAR
  ENDFOR
  
END