#!/bin/sh

ids=`cat ../ids`

for id in $ids; do
  if [ ! -d $node${id} ]; then
    mkdir -p ./node${id}
  fi
  
  if [ -s ./node${id}/id_rsa.pub ]; then
    continue
  fi

  echo scp node${id}:/root/.ssh/id_rsa.pub ./node${id}/
  echo scp node${id}:/root/.ssh/id_rsa.pub ./node${id}/ | sh

  if [ -s ./node${id}/id_rsa.pub ]; then
    cat node${id}/id_rsa.pub >> authorized_keys
  else
    echo "[]Error: not infor for node$id!!"
  fi


#  exit
done

#cat node*/id_rsa.pub > authorized_keys
#chmod 600 authorized_keys
