#!/bin/sh

ids=`grep '^ ' ../ids`
#ids=`cat ../ids_12`
ids=" 4 5 6 7 9 10 12"

for id in $ids; do
  if [ $id -eq 6 ]; then
    echo continue
    continue
  fi

  paths="/usr/local/dcw-gmt-1.1.4 /usr/local/gshhg-gmt-2.3.7 /usr/local/GMT-6.0.0 /usr/local/gmt5sar20200529" 
  for path in $paths; do
    cmdstr1="mkdir -p $path"
    echo  making directories on gpsac${id} with command $cmdstr1
    ssh gpsac${id} $cmdstr1

    cmdstr2="mount gpsac6:${path} ${path}"
    echo  mounting directories on gpsac${id} with command $cmdstr2
    ssh gpsac${id} $cmdstr2
  done

  #exit
done


