#!/bin/sh

ids=`grep '^ ' ../ids`
#ids=`cat ../ids_12`
#ids="2 3 4 5 6 7 8 9 10 11"
#ids='13 14 15 16 17 18'

for id in $ids; do
  if [ $id -le 1 ]; then
    echo continue
    continue
  fi

  paths="/usr/local/dcw-gmt-1.1.4/ /usr/local/GMT-6.0.0 /usr/local/gmt5sar20200529" 
  paths="/usr/local/gshhg-gmt-2.3.7/"
  paths='/g13a /g13b /g13c /g13d /g13e /g13f /g13g /g13h'
  for path in $paths; do
    cmdstr1="mkdir -p $path"
    echo  making directories on node${id} with command $cmdstr1
    ssh node${id} $cmdstr1

    cmdstr2="mount node1:${path} ${path}"
    #echo  mounting directories on node${id} with command $cmdstr2
    #ssh node${id} $cmdstr2
  done

  #exit
done


