#!/bin/sh

ids=`grep '^ ' ../ids`
#ids=`cat ../ids_12`
ids="2 3 4 5 6 7 8 9 10"

for id in $ids; do
  if [ $id -le 1 ]; then
    echo continue
    continue
  fi

  paths="/usr/local/GMT-6.0.0i /usr/local/gmt5sar20200529i"
  paths='/usr/local/gmt5sar20170823i'
  paths='/usr/local/dcw-gmt-1.1.3 /usr/local/GMT-5.4.3i '
  for path in $paths; do

    cmdstr2="umount ${path}"
    echo  unmounting directories on node${id} with command $cmdstr2
    ssh node${id} $cmdstr2

    cmdstr1="rm -rf $path"
    echo  deleting directories on node${id} with command $cmdstr1
    ssh node${id} $cmdstr1

  done

  #exit
done


