#!/bin/sh


ids='4 5 6 7 9 10 12 13 14 15 16 18 19'
for id in $ids; do

  echo "cat sh_mounts | grep mount | grep -v '#' | grep g${id} | awk '{print \"umount\",\$3}' "


done


#remount all
#cat sh_mounts | grep mount | grep -v '#' | grep -v g4 | grep -v node1 | grep -v iGPS | grep -v usr|sh
