.TH CMC_CAL_OPTIMAL 1 "23 Nov 2007" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
cmc_cal_optimal \- Common-mode filter using regional stacking algorithm.
.SH SYNOPSIS
cmc_cal_optimal  \fIpath\fP \fInetFile\fP \fIopath\fP
.SH DESCRIPTION
.TP
\fIpath\fP is the input path name.
.TP
\fInetFile\fP is coordiantes for sites.
.TP
\fIopath\fP is the output path.
.PP
The calculation of CMC is based upon the residual position time series. Therefore, remove first linear trend, seasonal variations and any other signals that are not so regional.
.PP
This program first calls \fBts_corr\fP to calculate inter-station time series correlations. It will create an sub-directory (corr) in the output location.
.SH OPTIONS
.TP
NONE.
.SH EXAMPLES
cmc_cal_optimal tibet.resid/ gps_global_cmonoc.net tibet.resid.cmc0/
.SH "SEE ALSO"
ts_corr, cme_cal_stacking, iGPSftk, iGPS
