.TH GET_RNX 1 "23 Nov 2007" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
get_rnx \- Download RINEX observations files from remote IGS centers.
.SH SYNOPSIS
get_rnx  \fBYEAR|YR\fP \fIDOY\fP \fINDAYS\fP \fI--site=sit1,...|--sitefile=sfile\fP \fI[--dir=output_directory ]\fP \fI[--archive=sopac|cddis|kasi]\fP \fI[--ftp_prog=wget|ftp|ncftp]\fP
.SH DESCRIPTION
\fB \fP


 
     Output path is the parent directory of rinex files.
.TP
\fIYEAR|YR\fP
Starting year. Four-digit or two-digit formated year string could be used. e.g. 2002, 02, 99.
.TP
\fIDOY\fP
staring day-of-year.
.TP
\fINDAYS\fP
Number of days to download data.
.TP
\fI--site=sites|--sitefile=filename\fP
Sites names, or file contains the sites names. \fIsites\fP are in the format of sit1,sit2,sit3,... The format of \fIsitefile\fP is identical to that of IGS site files.
     Sample of SITEFILE:
       bjfs lhas
       wuhn #urum
       ++++
       shao
.TP
\fI--archive=sopac|cddis|kasi [Optional]\fP
IGS data center should be used. The default is sopac.
.TP
\fI--ftp_prog=wget|ftp|ncftp\fP
.br
Optional.
.br
Which ftp client should be used?
.br
Default is \fIftp\fP.
.SH OPTIONS
.TP
NONE.
.SH MODIFICATIONS
.TP
MOD MAY-06-2008 Tian
.br
+Add \fI--ftp_prog=\fP parameter.
.SH EXAMPLES
 get_rnx 2000 1 2 --site=bjfs,shao
.SH LICENSES
.TP
 (c) Copyright by Tian 2007.
 License: free to use/edit for academic purpose.
.SH "SEE ALSO"
.IR get_hfile (1),
.IR get_nav (1),
.IR get_orb (1),
.IR get_met (1),
.IR iGPSftk (1)
