.TH GET_ORB 1 "23 Nov 2007" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
get_orb \- Download IGS orbit files from remote IGS centers.
.SH SYNOPSIS
.PP
\fBget_orb\fR \fBYEAR|YR\fP \fBDOY\fP \fBNDAYS\fP [\fB--archive\fP=\fIsopac|cddis|kasi\fP] \fB[--dir=\fP\fIOUTPUT_DIR\fP] [\fB--orbt=\fP\fIigsf|igsr|siof|gfile\fP]
.SH DESCRIPTION
.TP
\fBYEAR|YR\fP
Starting year. Four-digit or two-digit formated year string could be used. 
.br
For example: 2002, 02, 99.
.TP
\fBDOY\fP
Staring day-of-year.
.TP
\fBNDAYS\fP
Number of days to download data.
.TP
\fB--archive\fP=\fIsopac|cddis|kasi\fP
IGS data center to download data from. 
.br
The default is \fIsopac\fP.
.TP
\fB--dir=\fP\fIOUTPUT_DIR\fP
Optional. \fBOUTPUT_DIR\fR path is the parent directory of orbit files.
The output directory name. e.g.: /igs/pur/products. The structure of directories looks like:
.br
	/igs
.br
		/products
.br
			/1200
.br
				/igs12001.sp3.Z
.br
				/...
.br
			/...
.br
			/${GPSW}/${ORBT}${GPSW}${GPSD}.sp3.Z
.TP
\fB--orbt=\fP\fIigsf|igsr|siof|gfile\fP
Orbit type. Default is \fIigsf\fP.
.SH OPTIONS
.TP
NONE.
.SH EXAMPLES
get_orb 2000 1 2 --orbt=igsr
.br
get_orb 2001 200 3
.br
get_orb 2007 1 365 --dir=/igs_data/pub/products
.br
get_orb 2007 1 365 --archive=kasi --orbt=igsr 
.SH LICENSES
.TP
(c) Copyright by Tian 2007.
.br
Free to use/modify for academic purposes.
.SH "SEE ALSO"
.IR get_hfile (1),
.IR get_nav (1),
.IR get_rnx (1),
.IR get_met (1),
.IR iGPSftk (1)
