.TH GETFILEEXT 1 "23 Nov 2007" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
getfileext \- Return the filename extension from the file name .
.SH SYNOPSIS
call \fBgetfileext\fP (\fIfile\fP, \fIext\fP)
.SH DESCRIPTION
\fBgetfileext\fP return the extension from given file name.
.TP
\fIfile\fP
this is the input full path/file name.
.TP
\fIext\fP
this is the extension name.
.SH OPTIONS
.TP
NONE.
.SH EXAMPLES
 character*512 file,fileext
 file='/usr/local/test/bjfs.xyz'
 call getfilename(file,fileext)

 fileext should be "xyz"
.SH "SEE ALSO"
.IR desuffix (1),
.IR getfileext (1),
.IR getlun (1),
.IR getpathname (1),
.IR pathsep (1),
.IR iGPSftk (1)
