.TH GETFILENAME 1 "23 Nov 2007" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
getfilename \- Return the filename from the full pathname .
.SH SYNOPSIS
call \fBgetfilename\fP (\fIfullname\fP, \fIfile\fP)
.SH DESCRIPTION
\fBgetfilename\fP return the filename from given full pathname.
.TP
\fIfullname\fP
this is the input full path/file name.
.TP
\fIfile\fP
this is the file name
.SH OPTIONS
.TP
NONE.
.SH EXAMPLES
 character*512 fullname,file
 file='/usr/local/test/bjfs.xyz'
 call getfilename(fullname,file)

 file should be "bjfs.xyz"
.SH "SEE ALSO"
.IR desuffix (1),
.IR getfileext (1),
.IR getlun (1),
.IR getpathname (1),
.IR pathsep (1),
.IR iGPSftk (1)
