.TH GETLUN 1 "23 Nov 2007" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
getlun \- Return a free file unit.
.SH SYNOPSIS
call \fBgetlun\fP (\fIext\fP)
.SH DESCRIPTION
\fBgetlun\fP return a system free unit.
.TP
\fIlun\fP
this is the returned file unit [output].
.SH OPTIONS
.TP
NONE.
.SH EXAMPLES
 integer*4 lun
 call getlun(lun)
.SH "SEE ALSO"
.IR desuffix (1),
.IR getfileext (1),
.IR getfilename (1),
.IR getpathname (1),
.IR pathsep (1),
.IR iGPSftk (1)
