.TH L_L_R2LLRS_PANGA 1 "04/23/2008" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
l_l_r2llrs_panga \- Convert PANGA LAT/LON/RAD format into SIO/NEU form.
.SH SYNOPSIS
l_l_r2llrs_panga  \fI \fP
.SH DESCRIPTION
\fB \fP
The PANGA time series are stored in separate files for each component (lat/lon/rad). And the length of each component may vary for the same station, which makes it difficult for general time series analysis. This program combines the coordiantes from three files into one which conforms to the SIO/NEU format.
.TP
\fIpath\fP
Input data path.
\fIopath\fP
Oputput data path.
.
.SH OPTIONS
.TP
.
.SH MODIFICATIONS
.TP
MOD TIAN APR-23-2008
.br
The extentions of output file names are changed from .llr to .neu.
.TP
CREATED TIAN 2007
.br
Revised from l_l_r2llrs program code.
.SH BUGS
.TP
.
.SH EXAMPLES
.TP
l_l_r2llrs_panga /l_l_r /llrneu
.SH LICENSE
.TP
(c) Copyright by Tian.
.PP
License: free to use/edit for academic purpose.
.SH "SEE ALSO"
.IR l_l_r2llrs (1),
.IR iGPSftk (1)
