.TH L_L_R2LLRS 1 "02 Nov 2008" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
l_l_r2llrs \- Convert JPL LAT/LON/RAD format into SIO/NEU form.
.SH SYNOPSIS
l_l_r2llrs  path opath
.SH DESCRIPTION
\fIl_l_r2llrs\fP
convert JPL time series in LAT/LON/RAD format into SIO NEU format. Note: the number of observations in JPL LAT, LON and RAD file are the same. However, for PANGA LAT/LON/RAD file format, they may be different.
.TP
\fIpath\fP
Input data path.
.TP
\fIopath\fP
Oputput data path.
.SH MODIFICATIONS
.TP
MOD TIAN NOV-02-2008
.br
The extentions of output file names are changed from .llr to .neu.
.TP
CREATED TIAN 2007
.SH BUGS
.TP
.SH EXAMPLES
.TP
l_l_r2llrs /l_l_r /llrneu
.SH LICENSE
.TP
(c) Copyright by Tian. Free to use/modify for non-commercial purposes.
.SH "SEE ALSO"
.IR l_l_r2llrs_panga (1),
.IR iGPSftk (1)
