.TH NDOYR 1 "23 Nov 2007" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
ndoyr \- Return a the number of days in one year.
.SH SYNOPSIS
n_days_of_year = \fBndoyr\fP (\fIyear\fP)
.SH DESCRIPTION
\fBndoyr\fP return a the number of days in given year.
.TP
\fIyear\fP
this is the input year.
.SH OPTIONS
.TP
NONE.
.SH EXAMPLES
 integer*4 year,ndoyr,ndaysyr
 ndaysyr=ndoyr(year)
.SH "SEE ALSO"
.IR iGPSftk (1)
