.TH NEU_EXTRACT_BY_NEU 1 "02 Nov 2008" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
neu_extract_by_neu \- Extract time series from continuous (day by day) mass loading displacements created by \fImload\fP of \fIQOCA\fR program according to the epochs in one GPS time series (say SIO/neu files).
.SH SYNOPSIS
neu_extract_by_neu path opath
.SH DESCRIPTION
\fIneu_extract_by_neu\fP
\fImload\fR usually outputs continuous displacements series for a time span constrainted by meteorological observations (say, NCEP Reanalysis surface pressure observations--pres.sfc.YEAR). However, there are more or less data gaps in observed GPS positions time series. This purpose of this program is to extract the corresponding displacement time series according GPS series.
.PP
\fIpath\fR
Input data path.
.PP
\fIopath\fR
Oputput data path.
.SH MODIFICATIONS
.PP
MOD TIAN NOV-02-2008
.PP
CREATED TIAN 2007
.SH EXAMPLES
.PP
neu_extract_by_neu /qoca/aload.neu /qoca/aload.neu.byneu
.SH LICENSE
.PP
(c) Copyright by Tian. Free to use/modify for non-commercial purposes.
.SH "SEE ALSO"
.IR qocaload2cats (1),
.IR qocaload2sios (1),
.IR load_comb2 (1),
.IR iGPSftk (1)
