.TH PBO2CATS 1 "04/19/2008" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
pbo2cats \- Convert PBO XYZ coordinates time series to CATS input format.
.SH SYNOPSIS
pbo2cats  \fIpath\fP \fIopath\fP
.SH DESCRIPTION
\fB pbo2cats \fP
PBO coordinates time series can be downloaded from ftp://data-out.unavco.org/pub/products/position.
.TP
\fIpath\fP
Input path.
.PP
\fIopath\fP
Output path.
.SH OPTIONS
.TP
.
.SH MODIFICATIONS
.TP
.
.SH BUGS
.TP
.
.SH EXAMPLES
.TP
pbo2cats
.SH LICENSE
.TP
(c) Copyright by Tian.
.PP
License: free to use/edit for academic purpose.
.SH "SEE ALSO"
.IR  (1),
.IR iGPSftk (1)
