.TH QUEYR_PBO 1 "23 Nov 2007" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
query_pbo \- Read a JPL L,L,R time series.
.SH SYNOPSIS
call \fBquery_pbo\fP (\fIfile\fP, \fInrow\fP \fI, ncol\fP, \fIfirstepoch\fP, \fIlastepoch\fP, \fIxyzref\fP, \fIneuref\fP)
.SH DESCRIPTION
\fBquery_pbo\fP will query a \fIPBO\fP format coordinates time series file.
.TP
\fIfile\fP
this is the input \fI.lat,.lon,.rad\fP format (ASCII) files.
.TP
\fInrow,ncol\fP
those are the output variables which contain the dimensions of data array (N_RWO, N_COLUMN).
.TP
\fIfirstepoch\fP
the eopch of first coordinate time series.
.TP
\fIlastepoch\fP
the eopch of last coordinates time series.
.TP
\fIxyzref\fP
the XYZ reference coordinates.
.TP
\fIneuref\fP
the NEU [WGS84] reference coordinates.
.SH OPTIONS
.TP
NONE.
.SH EXAMPLES
 implicit none
 include '../../inc/cgps.h'
 character*512 file
 real*8 data(nmax_row,nmax_col)
 integer*4 nrow,ncol
 integer*4 i,j
 file='/export/home/tianyf/data/pbo/bjfs.xyz'
 call \fBread_l_l_r\fP (file, \fBdata\fP, nrow, \fBncol\fP)
.SH "SEE ALSO"
.IR file_info (1),
.IR read_cmonoc (1),
.IR read_l_l_r (1),
.IR read_l_l_r_panga (1),
.IR read_pbo (1),
.IR read_poletide_bull_a (1),
.IR read_sio (1),
.IR read_usgs (1),
.IR iGPSftk (1)
