.TH READ_COLS 1 "03 Nov 2008" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
read_cols \- Read a data matrix from ascii text file.
.SH SYNOPSIS
call \fBread_cols (file,data,nrow,ncol,headers,nhead,cmt)
.SH DESCRIPTION
\fIread_cols\fP will read a ascii data matrix form a file (say, \fISIO\fP NEU/XYZ format coordinates time series file).
.TP
\fIfile\fP
is the \fI.neu/.xyz\fP format (ASCII) file [character*(*); input].
.TP
\fIdata\fP
is the array that will contain the data matrix [real*8 (NMAX_ROW,NMAX_COL); output].
.TP
\fInrow,ncol\fP
are the dimensions of data array (N_ROW, N_COLUMN) [integer*4; output].
.TP
\fIheaders\fP
is the array which contains the header lines [character*(*); output].
.TP
\fInhead\fP
is the number of header lines in SIO coordinates time series file [integer*4; output].
.PP
\fIcmt\fP
is the comment line indication. For SIO/NEU, it is "#" [character*; input].
.SH BUGS
.PP
MOD TIAN NOV-03-2008
.br
Fixed a bug. When the number of header lines is zero, the returned data matrix is errneous.
.SH EXAMPLES
      implicit none
      include '../../inc/cgps.h'
      character*512 file,headers(NMAX_HEADER),cmt
      real*8 data(NAMX_ROW,NMAX_COL)
      integer*4 nrow,ncol,nhead
      integer*4 i,j

      cmt='#'
      file='/export/home/tianyf/data/pbo/bjfs.xyz'
      call \fBread_cols\fP(file,\fBdata\fP,nrow,\fBncol\fP,headers,nhead,cmt)
      do i=1,nrow
        write(*,*) (data(i,j),j=1,ncol)
      enddo
.SH "SEE ALSO"
.IR file_info (1),
.IR l_l_r_read (1),
.IR read_cmonoc (1),
.IR read_l_l_r_panga (1),
.IR read_pbo (1),
.IR read_poletide_bull_a (1),
.IR read_usgs (1),
.IR iGPSftk (1)
