.TH READ_L_L_R 1 "23 Nov 2007" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
read_l_l_r \- Read a JPL L,L,R time series.
.SH SYNOPSIS
call \fBread_l_l_r\fP (\fIfile\fP, \fIdata\fP \fI, nrow\fP \fI, ncol\fP)
.SH DESCRIPTION
\fBread_l_l_r\fP will read a \fIPBO\fP format coordinates time series file.
.TP
\fIfile\fP
this is the input \fI.lat,.lon,.rad\fP format (ASCII) files.
.TP
\fIdata\fP
this is the output array that will contain the data matrix.
.TP
\fInrow,ncol\fP
those are the output variables which contain the dimensions of data array (N_RWO, N_COLUMN).
.SH OPTIONS
.TP
NONE.
.SH EXAMPLES
 implicit none
 include '../../inc/cgps.h'
 character*512 file
 real*8 data(nmax_row,nmax_col)
 integer*4 nrow,ncol
 integer*4 i,j
 file='/export/home/tianyf/data/pbo/bjfs.xyz'
 call \fBread_l_l_r\fP (file, \fBdata\fP, nrow, \fBncol\fP)
.SH "SEE ALSO"
.IR file_info (1),
.IR query_pbo (1),
.IR read_cmonoc (1),
.IR read_l_l_r_panga (1),
.IR read_pbo (1),
.IR read_poletide_bull_a (1),
.IR read_sio (1),
.IR read_usgs (1),
.IR iGPSftk (1)
