.TH RUN_CMONOC_REG 1 "25 JAN 2010" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
run_cmonoc_reg \- Run GAMIT to process CMONOC survey-mode GPS data.
.SH SYNOPSIS
run_cmonoc_reg \fB--path=PATH\fP \fB--obstat=OBS_STAT_FILE\fP \fB--stable=FIDUCIAL_SITE_FILE\fP
.SH DESCRIPTION
\fBrun_cmonoc_reg \fP
Calculate radial displacements caused by seasonal mass variations of major rivers (say, the Yangtze). By convolving the river mass with load Green's Function.
.TP
\fI--path=PATH\fP
Input files path.
.TP
\fI--obstat=OBS_STAT_FILE\fP
Observations statistics file.
Sample:
               a001 a002 a003 a004 a005
 1999 132   50    0    0    1    1    0
 1999 133   46    0    0    1    1    0
 1999 134   58    0    0    1    1    0
 1999 135   47    0    0    1    1    0
 1999 136   47    0    0    1    0    0
 1999 137   68    1    1    1    0    1
 1999 138   68    1    1    1    0    1
 1999 139   68    1    1    1    0    1
 1999 140   44    1    1    1    0    1
 1999 141   30    1    1    1    0    1
 1999 142   24    1    1    1    0    1
.TP
\fIF--stable=FIDUCIAL_SITE_FILE\fP
Stable sites (for defining reference frame; or transforming the frame) file in iGPS site list file (*.sit) format. Sample:
 bjfs bjsh
 chan
 chun
 urum
 guao
 wuhn whjf shao
 kmin KUNM
 lhas
 lhaz
.SH OPTIONS
.TP
NONE.
.SH EXAMPLES
run_cmonoc_reg --path=/solut/gmf.survey.mode/reg5
   --obstat=/solut/gmf.survey.mode/reg5/sh/STAT
   --stable=/solut/gmf.survey.mode/reg5/sh/stable.sit
.SH "SEE ALSO"
.IR iGPSftk (1)