.TH NDOYR 1 "23 Nov 2007" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
sh_get_data* \- A revied version of gamit counterpart.
.SH SYNOPSIS
sh_get_data  \fB\fP \fI\fP
.SH DESCRIPTION
\fB \fP
GAG GPS archive has a different directories structure from that of KASI/CDDIS.
Thus, we cannot just ncftp get -R the YYd directory from those IGS data servers.
Instead, the get_* executables under ~/gpsf/cgps/dc/get directory should be used
to download data and products from IGS data&products centers.
Scripts sh_get_data_YEAR have been obsolete.
.TP
.SH OPTIONS
.TP
NONE.
.SH EXAMPLES
 sh_get_data
.SH "SEE ALSO"
.IR get_rnx (1),
.IR get_nav (1),
.IR get_orb (1),
.IR get_met (1),
.IR iGPSftk (1)
