'\" te
.\"  Copyright (c) 2008 Tian. Free for non-commercial uses\&.
.TH sio2estn 1 "02 Nov 2008" "iGPSftk" "ORTRAN Programs for GPS"
.SH "NAME"
sio2estn \- Convert SIO/NEU to 
.SH "SYNOPSIS"
.PP
\fBuptime\fR
.SH "DESCRIPTION"
.PP
The \fBuptime\fR command prints the current time, the length of time the system has been up, and the average number of jobs in the run queue over the last 1, 5 and 15 minutes\&. It is,
essentially,  the first line of a \fBw\fR(1) command\&.
.SH "EXAMPLES"
.PP
Below is an example of the output \fBuptime\fR provides:
.sp
.RS
.PP
.nf
\fBexample% uptime
10:47am  up 27 day(s), 50 mins,  1 user,  load average: 0\&.18, 0\&.26, 0\&.20\fR
.fi
.RE
.sp
.SH "ATTRIBUTES"
.PP
See \fBattributes\fR(5) for descriptions of the following
attributes:
.sp
.TS
tab() box;
cw(2.750000i)| cw(2.750000i)
lw(2.750000i)| lw(2.750000i).
\fBATTRIBUTE TYPE\fR\fBATTRIBUTE VALUE\fR
AvailabilitySUNWcsu
.TE
.sp
.SH "SEE ALSO"
.PP
\fBw\fR(1), \fBwho\fR(1), \fBwhodo\fR(1M), \fBattributes\fR(5)
.SH "NOTES"
.PP
\fBwho\fR -\fBb\fR gives the time the system was last booted\&.
...\" created by instant / solbook-to-man, Wed 22 Dec 2004, 13:42
