.TH SIO2CATS 1 "23 Nov 2007" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
sio2cats \- Convert SIO NEU/XYZ time series to CAT input format.
.SH SYNOPSIS
sio2cats  \fI path \fP \fIopath\fP \fI[TYPE]\fP
.SH DESCRIPTION
\fB \fP
NONE
.TP
\fIpath\fP
this is the input path name.
.TP
\fIopath\fP
this is the output path name.
.TP
\fI[TYPE]\fP
Input time series tpye. Options are sioneu, sioxyz. Default it sioneu.
.SH OPTIONS
.TP
NONE.
.SH EXAMPLES
sio2cats /data/sioxyzs /sio_cats sioxyz
.SH "SEE ALSO"
.IR asc2bin_sio (1),
.IR asc2bin_sios (1),
.IR sio2cats (1),
.IR pbo2cats (1),
.IR iGPSftk (1)
