.TH STRSPLIT 1 "23 Nov 2007" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
strsplit \- An alternative to IDL's STRSPLIT function.
.SH SYNOPSIS
call strsplit ( \fBstr\fP, \fIsep\fP, \fIn\fP, \fIstrs\fP)
.SH DESCRIPTION
\fBstrsplit\fP split the given string into several segments.
.TP
\fIstr\fP
this is the input string.
.TP
\fIsep\fP
the field separator. Default to be blank (' ').
.TP
\fIn\fP
number of segments.
.TP
\fIstrs\fP
result of splited strings.
.SH OPTIONS
.TP
NONE.
.SH EXAMPLES
 character*512 str,strs(100)
 integer*4 n
 character*1 sep
 sep=','
 str='1,2,3,4,5'
 call strsplit(str,sep,n,strs)
.SH "SEE ALSO"
.IR iGPSftk (1)
