.TH UNIMAKE_IGPSFTK 1 "23 Nov 2007" "iGPSftk" "FORTRAN ToolKit for GNSS"
.SH NAME
unimake_igpsftk \- The iGPSftk version similar to the one used by GAMIT (~/gg/com/unimake).
.SH SYNOPSIS
The same as ~/gg/com/unimake.  \fB\fP \fI\fP
.SH DESCRIPTION
\fB \fP
A few modifications were made, e.g., a ARCH (e.g. Linux_x86_64) suffix is added to the generated Makefile, in order to use in varied operating systems (e.g. Linux/FreeBSD/Cygwin/Solaris). For more information, please see the help of iGPSftk.
.SH "SEE ALSO"
.IR install_igpsftk (1),
.IR install_igpsftk_links (1),
.IR Makefile.generic (1),
.IR iGPSftk (1)
