#!/bin/sh

ids=`cat ../ids`
#ids='19 20'

file=network
for id in $ids; do
  if [ $id -eq 1 ]; then
    continue
  fi

  echo scp ./$file node${id}:/etc/sysconfig/
  echo scp ./$file node${id}:/etc/sysconfig/ | sh

  #exit
done


for id in $ids; do
  if [ $id -eq 1 ]; then
    continue
  fi

  echo "starting nis services on node${id} ..."
  ssh node${id} "authconfig --enablenis --nisdomain=node1 --nisserver=node1 --enablemkhomedir --update && systemctl restart rpcbind ypbind && systemctl enable rpcbind ypbind"
done
