#!/bin/sh

this_host=`hostname`
ids=`grep '^ ' ../ids.${this_host}`
#ids=`grep '^ ' ids_online`
#ids=`cat ../ids_12`
#ids=" 1 7 8 9 10 13 14 15 16 17 18"
#ids=`grep '^ ' ids_online`
#ids=18


for id in $ids; do
  if [ $id -eq  5 -o $id -eq  28 -o $id -eq 29 ]; then
    echo continue
    continue
  fi

  cmdstr2="systemctl restart slurmd"
  cmdstr1="systemctl daemon-reload"
  cmdstr3='timedatectl  set-timezone Asia/Shanghai'
  if [ $id -le 12 ]; then
    cmdstr4='yum -y install ntp ntpdate'
  else
    cmdstr4='yum -y install chrony'
  fi

  cmdstr5='systemctl enable chronyd'
  cmdstr6='systemctl restart chronyd'
 
  cmdstr7='systemctl enable ntpd'
  cmdstr8='systemctl restart ntpd'
  cmdstr9='mkdir -p /usr/local/idl71'
  cmdstr10='chown tianyf /usr/local/idl71'
  cmdstr11='rsync -avP gpsac4:/usr/local/idl71 /usr/local/'
  cmdstr12='yum -y install libXp gdal gdal-devel'
  cmdstr13='mkdir -p /g16a /g16b /g16c /g16d /g16e /g16f /g16g /g16h /g16i /g16j /g16n /g16o'
  cmdstr14='/home/tianyf/sh_mount_ac'
  cmdstr15='sh_lsattr_esa_data'
  cmdstr16='mkdir -p /g14e /g14f /g14g /g14i /g14o'
  cmdstr17='umount -fl /g12a /g12b /g12c /g12d /g12e /g12f /g12h'
  cmdstr18='mkdir -p /usr/local/MATLAB'
  cmdstr19='mount gpsac6:/usr/local/MATLAB /usr/local/MATLAB'
  cmdstr20='yum -y install ncurses-* java-1.8.0-openjdk.x86_64 libnsl'
  cmdstr21='mkdir -p /usr/local/anaconda3'
  cmdstr22='mkdir -p /home/tianyf/wafeng'
  cmdstr23='mount gpsac6:/usr/local/anaconda3 /usr/local/anaconda3'
  cmdstr24='rsync -avP  gpsac6:/home/tianyf/wafeng /home/tianyf/'
  cmdstr25='yum -y install cockpit'
  cmdstr26='systemctl start cockpit'
  cmdstr27='mkdir -p /g9a /g9b /g9c /g9d /g9h /g9n'
  cmdstr28='/home/tianyf/iGPS/sh/admin/mount/sh_mounts_tmp'
  cmdstr29='mkdir -p /usr/local/gmt5sar20220909'
  cmdstr30='chown tianyf /usr/local/gmt5sar20220909'
  cmdstr31='rsync -avP gpsac4:/usr/local/gmt5sar20220909 /usr/local/'
  cmdstr32='sh_recompile_gmt5sar'
  cmdstr33='umount /g16a /g16c /g16d /g16e /g16f /g16g /g16h /g16i /g16j /g16n /g16o'
  cmdstr34='umount /g17a /g17b /g17h /g17n'
  cmdstr35='mount gpsac4:/g4b /g4b'
  cmdstr36='umount /g3a /g3b /g3h'
  cmdstr37='rsync -avP --exclude "*temp" gpsac4:/home/tianyf/gpse/trns/solut/gmf/IGSF /home/tianyf/gpse/trns/solut/gmf/'
  cmdstr38='rsync -avP gpsac4:/usr/local/gamit-v10.71/tables /usr/local/gamit-v10.71/'
  cmdstr38='rsync -avP gpsac4:/usr/local/gamit-v10.71 /usr/local/'

  cmdstr39='umount -fl /g14a /g14b /g14c /g14d /g14e /g14f /g14g /g14h /g14h /g14i /g14n /g14o /g15a /g15b /g15c /g15d /g15e /g15f /g15h /g15n'
  cmdstr40=/home/tianyf/iGPS/sh/admin/ac/mount/sh_mount_tmp
  cmdstr41='umount -a -t nfs4'
  cmdstr42='umount -fl /g7b /g7c /g7d /g7e /g7f /g7g /g7h /g7i'
  cmdstr43='umount /g6d'
  cmdstr44='mkdir -p /g19a /g19b /g19c /g19d /g19e /g19f'
  cmdstr45='umount /g18h'
  cmdstr46='mkdir -p /g18a /g18b /g18c /g18d /g18e /g18f /g18g /g18h'
  cmdstr47='systemctl enable firewalld'
  if [ $id -le 12 ]; then
    cmdstr48='systemctl restart nfs'
  else
   cmdstr48='systemctl restart nfs-server'
  fi
  cmdstr49='rsync -avP g4:/var/opt/goa-var /var/opt/'
  cmdstr50="find /home/tianyf/gpse/trns/solut/gmf/IGSF/temp -name 'sh*.log' >> /g4b/gsar/went_wrong.g${id}"
  cmdstr51='umount /g18b /g18h /g19a /g19b /g19c /g19d /g19e /g19f /g19h'
  cmdstr52="df -h | grep 'g1[89]'"
  cmdstr53="/home/tianyf/sh_mount_ac | grep '^mount' | grep 'g1[89]' | sh"
  cmdstr54='rsync -avP gpsac4:/etc/ld.so.conf.d/gmt.conf /etc/ld.so.conf.d/'
  cmdstr55='ldconfig'
  cmdstr56='umount /g5a /g5b /g5c /g5d /g5h'

  #>>>
  cmdstr=$cmdstr56

  echo  on gpsac${id} running command $cmdstr
  ssh gpsac${id} $cmdstr
  #ssh gpsac${id} $cmdstr2


  #exit
done
