#!/bin/sh

ids=`grep '^ ' ../ids`
#ids=`cat ../ids_12`
#ids="4 5 8 9"
#ids='13 14 15 16 17 18'
#ids="19 20"
#ids=1

for id in $ids; do
  if [ $id -le 1 -o $id -eq -9 ]; then
    echo continue
    #continue
  fi
  echo "working at node${id}"
  #continue

  cmdstr1="sh /sar/admin/mount/sh_mounts"
  cmdstr1="sh /sar/admin/mount/sh_mounts_tmp"

  cmdstr2="mount idc.dhcp.com:/sar /sar"
  #cmdstr2="mount 10.4.35.76:/sar /sar"
  cmdstr3="umount -a -t nfs4"
  cmdstr4="df -h"
  cmdstr5='mount gpsac4:/home/tianyf/iGPS /home/tianyf/iGPS'
  cmdstr6='mount gpsac4:/home/tianyf/iGPS.addon/ /home/tianyf/iGPS.addon/'
  cmdstr7='mount node1:/usr/local/gamit-v10.71 /usr/local/gamit-v10.71'
  cmdstr8='rsync -avP node1:/opt/intel /opt/'
  cmdstr9='umount /opt /composer_xe_2015.3.187'
  cmdstr10='mount node1:/composer_xe_2015.3.187 /composer_xe_2015.3.187'
  cmdstr11='mkdir /usr/local/gmt5sar20210607i'
  cmdstr12='mount node1:/usr/local/GMT-6.0.0i /usr/local/GMT-6.0.0i'
  cmdstr13='mount node1:/usr/local/gmt5sar20200529i /usr/local/gmt5sar20200529i'
  cmdstr14='mkdir /usr/local/idl71'
  cmdstr15='mount node1:/usr/local/idl71 /usr/local/idl71'
  cmdstr16='umount /usr/local/GMT-6.0.0i /usr/local/GMT-6.0.0 /usr/local/gmt5sar20200529i /usr/local/gmt5sar20200529 /composer_xe_2015.3.187'
  cmdstr17='chown tianyf /usr/local/gmt5sar20210607i'
  cmdstr18='rsync -avP node1:/usr/local/gmt5sar20210607i /usr/local/'
  cmdstr19='sh_recompile_gmt5sar'
  cmdstr20='mkdir -p /usr/local/dcw-gmt-1.1.4 /usr/local/gshhg-gmt-2.3.7'
  cmdstr21='rsync -avP node1:/usr/local/dcw-gmt-1.1.4 /usr/local/'
  cmdstr22='mkdir -p /usr/local/gamit-v10.71'
  cmdstr23='sh /sar/admin/mount/sh_new_dirs'
  cmdstr24='umount /sar'
  cmdstr25='yum -y install libXp libXp-devel ftp lftp ncftp wget aria2'
  cmdstr26='mkdir -p /g14a /g14b /g14c /g14d /g14e /g14f /g14g /g14h /g14i /g14n /g14o /g15a /g15b /g15c /g15d /g15e /g15f /g15h /g15n /g15o /g16a /g16b /g16c /g16d /g16e /g16f /g16g /g16h /g16i /g16j /g16n /g16o'
  cmdstr27='umount /usr/local/gamit-v10.71'
  cmdstr28='ln -s /usr/local/gamit-v10.71 /home/tianyf/gg'
  cmdstr29='rsync -avP node1:/home/tianyf/gpse/trns/solut  /home/tianyf/gpse/trns/'
  cmdstr30='mkdir -p /g3d /g3c /g4e'
  cmdstr31='mount gpsac3:/g3d /g3d'
  cmdstr32='mount -t cifs -o username=ICDSAR,password=123abc,uid=0,dir_mode=0755 //10.4.134.28/SARData2 /g4e'
  cmdstr33='umount /g4e '
  cmdstr34='rsync -avP --exclude "*temp*" node1:/home/tianyf/gpse/trns/solut/gmf/IGSR /home/tianyf/gpse/trns/solut/gmf/'
  cmdstr35='mkdir /g4f'
  cmdstr36='mount 10.4.134.54:/s1data /g4f'
  cmdstr37='umount /g14a /g14b /g14c /g14d /g14e /g14f /g14h /g14h /g14i /g14n /g14o /g15a /g15b /g15c /g15d /g15e /g15f /g15h /g15n'
  cmdstr38='umount -fl /g12a /g12b /g12c /g12d /g12e /g12f /g12h'
  cmdstr39='mkdir -p /usr/local/MATLAB'
  cmdstr40='mount node1:/usr/local/MATLAB /usr/local/MATLAB'
  cmdstr41='rsync -avP node1:/usr/local/bin/xcorr* /usr/local/bin'
  cmdstr42='mkdir -p /home/tianyf/wafeng'
  cmdstr43='mount node1:/home/tianyf/wafeng /home/tianyf/wafeng'
  cmdstr44='yum -y install slurm* slurm-slurmd*'
  cmdstr45='mv -f /usr/local/slurm /usr/local/slurm.old'
  cmdstr46='chmod -R 0700 /etc/munge /var/log/munge && chmod -R 0711 /var/lib/munge && chmod -R 0755 /var/run/munge'
  cmdstr47='rsync -avP node1:/sar/admin/slurm.8/munge.key /etc/munge/'
  cmdstr48='chown munge:munge /etc/munge/munge.key && chmod 0600 /etc/munge/munge.key'
  cmdstr49='systemctl start munge.service && systemctl enable munge.service'
  cmdstr50='systemctl restart slurmd'
  cmdstr51='rsync -avP node1:/sar/admin/slurm.8/slurm.conf /etc/slurm/'
  cmdstr52='systemctld stop httpd'
  cmdstr53='mount gpsac16:/g16o /g16o'
  cmdstr54='systemctl stop vncserver@:1'
  cmdstr55='vncserver -kill :1'
  cmdstr56='umount -a -fl -t nfs4'
  cmdstr57='umount -a -fl -t nfs'
  cmdstr58='poweroff'
  cmdstr59='mkdir -p /g9a /g9b /g9c /g9d /g9h /g9n'
  cmdstr60='mount 10.4.134.13:/mnt/disk_4 /disk_4'
  cmdstr61='umount -fl /g16a /g16c /g16d /g16e /g16f /g16g /g16h /g16i /g16j /g16n /g16o'
  cmdstr62='mkdir -p /g17a /g17b /g17h /g17n'
  cmdstr63='umount -fl /disk_4'
  cmdstr64='umount /g17a /g17b/ /g17h /g17n'
  cmdstr65='umount -fl /g4b'
  cmdstr66='mount 10.4.134.42:/home/dell/work3/Data_FTP /disk_4'
  cmdstr67='umount -fl /g7b /g7c /g7d /g7e /g7f /g7g /g7h /g7i'
  cmdstr68='mkdir -p /g18a /g18h'
  cmdstr69='mount gpsac18:/home/tianyf /g18h'
  cmdstr70='umount /g16h -fl'
  cmdstr71='mkdir -p /g18b /g18h /g19a /g19b /g19c /g19e /g19h'
  cmdstr72='systemctl stop vsftpd'
  cmdstr73='systemctl enable firewalld'



  #run the specified command
  cmdstr=$cmdstr73

  echo  mounting directories on node${id} with command $cmdstr 
  ssh node${id} $cmdstr

  #ssh node${id} $cmdstr5
  #ssh node${id} $cmdstr6
  #ssh node${id} $cmdstr7

  #rsync -avP /opt/intel node${id}:/opt/

  #echo rsync -avP /usr/local/dcw-gmt-1.1.4 node${id}:/usr/local/
  #echo rsync -avP /usr/local/dcw-gmt-1.1.4 node${id}:/usr/local/ | sh

  #echo rsync -avP /usr/local/gshhg-gmt-2.3.7 node${id}:/usr/local/
  #echo rsync -avP /usr/local/gshhg-gmt-2.3.7 node${id}:/usr/local/ | sh


  #exit
done


