#!/bin/sh

# Name:
#   sh_tar_sbas
#   

# Purpose:
#   

# Example:
#   

# Modifications:
#   

# Algorigthm:
#   

# Dependency:
#   

dirs=`find /sar/proc_gmtsar/interseismic/ -maxdepth 1 -type d -name "[adt]**"`

host=10.4.134.16
opath='/cygdrive/i/INSAR/sar/proc_gmtsar/interseismic'

for dir in $dirs; do
  echo $dir
  for i in 1; do
    dir_sbass=`find ${dir}/f123.${i} -maxdepth 1 -type d -iname "sbas*"`
    for dir_sbas in $dir_sbass; do
      echo $dir_sbas
      opath_t="${opath}/`echo $dir_sbas | sed -e 's/\/sar\/proc_gmtsar\/interseismic\///g'`"
      echo "ssh $host \"mkdir -p $opath_t\" "
      echo "ssh $host \"mkdir -p $opath_t\" " | sh
      echo "ssh $host \"mkdir -p $opath_t\/r4\" " | sh


      rsync -avP $dir_sbas/vel_ll*.kml ${host}:$opath_t/
      rsync -avP $dir_sbas/vel_ll*.png ${host}:$opath_t/
      rsync -avP $dir_sbas/vel_mask_ll* ${host}:$opath_t/
      rsync -avP $dir_sbas/data.in ${host}:$opath_t/
      rsync -avP $dir_sbas/baseline* ${host}:$opath_t/
      rsync -avP $dir_sbas/r4/disp*.png ${host}:$opath_t/r4/
      rsync -avP $dir_sbas/*.tab ${host}:$opath_t/r4/

      rsync -avP $dir_sbas/*.tab ${host}:$opath_t/
      #exit
    done
  done
done
