FUNCTION STRING_SPLITS, STRS, SEP
  TMP=STRing_SPLIT(STRS[0],SEP)
  ;HELP, TMP
  OSTRS=STRARR(N_ELEMENTS(TMP),N_ELEMENTS(STRS))
  FOR I=0ULL, N_ELEMENTS(STRS)-1 DO BEGIN
    OSTRS[*,I]=STRing_SPLIT(STRS[I],SEP)
  ENDFOR
  
  RETURN, OSTRS
END

PRO STRING_SPLITS
  TMPS=['1.A','11.AA','23.BC','125.ABE','221.BBA']
  TMPS2=STRing_SPLITS(TMPS,'.')
  HELP, TMPS2
  PRINT,TMPS2
END