FUNCTION STRSPLITS, STRS, SEP, _EXTRA=_EX
  IF N_ELEMENTS(SEP) EQ 0 THEN SEP=' '
  TMP=STRSPLIT(STRS[0],SEP,_EXTRA=_EX)
  ;HELP, TMP
  OSTRS=STRARR(N_ELEMENTS(TMP),N_ELEMENTS(STRS))
  FOR I=0ULL, N_ELEMENTS(STRS)-1 DO BEGIN
    OSTRS[*,I]=STRSPLIT(STRS[I],SEP,_EXTRA=_EX)
  ENDFOR
  
  RETURN, OSTRS
END

PRO STRSPLITS
  TMPS=['1.A','11.AA','23.BC','125.ABE','221.BBA']
  TMPS2=STRSPLITS(TMPS,'.',/EXTRACT)
  HELP, TMPS2
  PRINT,TMPS2
END